// Autogenerated by Thrift Compiler ()
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package thrifttest

import (
	"bytes"
	"fmt"
	"github.com/upfluence/thrift/lib/go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

const Namespace = "thrift.test"

const MyNumberz = 1

func init() {
	thrift.RegisterStruct((*Bonk)(nil))
	thrift.RegisterStruct((*Bools)(nil))
	thrift.RegisterStruct((*Xtruct)(nil))
	thrift.RegisterStruct((*Xtruct2)(nil))
	thrift.RegisterStruct((*Xtruct3)(nil))
	thrift.RegisterStruct((*Insanity)(nil))
	thrift.RegisterStruct((*CrazyNesting)(nil))
	thrift.RegisterStruct((*Xception)(nil))
	thrift.RegisterStruct((*Xception2)(nil))
	thrift.RegisterStruct((*EmptyStruct)(nil))
	thrift.RegisterStruct((*OneField)(nil))
	thrift.RegisterStruct((*VersioningTestV1)(nil))
	thrift.RegisterStruct((*VersioningTestV2)(nil))
	thrift.RegisterStruct((*ListTypeVersioningV1)(nil))
	thrift.RegisterStruct((*ListTypeVersioningV2)(nil))
	thrift.RegisterStruct((*GuessProtocolStruct)(nil))
	thrift.RegisterStruct((*LargeDeltas)(nil))
	thrift.RegisterStruct((*NestedListsI32x2)(nil))
	thrift.RegisterStruct((*NestedListsI32x3)(nil))
	thrift.RegisterStruct((*NestedMixedx2)(nil))
	thrift.RegisterStruct((*ListBonks)(nil))
	thrift.RegisterStruct((*NestedListsBonk)(nil))
	thrift.RegisterStruct((*BoolTest)(nil))
	thrift.RegisterStruct((*StructA)(nil))
	thrift.RegisterStruct((*StructB)(nil))
	thrift.RegisterService(thriftTestServiceDefinition)
	thrift.RegisterStruct((*ThriftTestTestVoidArgs)(nil))
	thrift.RegisterStruct((*ThriftTestTestVoidResult)(nil))
	thrift.RegisterStruct((*ThriftTestTestStringArgs)(nil))
	thrift.RegisterStruct((*ThriftTestTestStringResult)(nil))
	thrift.RegisterStruct((*ThriftTestTestByteArgs)(nil))
	thrift.RegisterStruct((*ThriftTestTestByteResult)(nil))
	thrift.RegisterStruct((*ThriftTestTestI32Args)(nil))
	thrift.RegisterStruct((*ThriftTestTestI32Result)(nil))
	thrift.RegisterStruct((*ThriftTestTestI64Args)(nil))
	thrift.RegisterStruct((*ThriftTestTestI64Result)(nil))
	thrift.RegisterStruct((*ThriftTestTestDoubleArgs)(nil))
	thrift.RegisterStruct((*ThriftTestTestDoubleResult)(nil))
	thrift.RegisterStruct((*ThriftTestTestBinaryArgs)(nil))
	thrift.RegisterStruct((*ThriftTestTestBinaryResult)(nil))
	thrift.RegisterStruct((*ThriftTestTestStructArgs)(nil))
	thrift.RegisterStruct((*ThriftTestTestStructResult)(nil))
	thrift.RegisterStruct((*ThriftTestTestNestArgs)(nil))
	thrift.RegisterStruct((*ThriftTestTestNestResult)(nil))
	thrift.RegisterStruct((*ThriftTestTestMapArgs)(nil))
	thrift.RegisterStruct((*ThriftTestTestMapResult)(nil))
	thrift.RegisterStruct((*ThriftTestTestStringMapArgs)(nil))
	thrift.RegisterStruct((*ThriftTestTestStringMapResult)(nil))
	thrift.RegisterStruct((*ThriftTestTestSetArgs)(nil))
	thrift.RegisterStruct((*ThriftTestTestSetResult)(nil))
	thrift.RegisterStruct((*ThriftTestTestListArgs)(nil))
	thrift.RegisterStruct((*ThriftTestTestListResult)(nil))
	thrift.RegisterStruct((*ThriftTestTestEnumArgs)(nil))
	thrift.RegisterStruct((*ThriftTestTestEnumResult)(nil))
	thrift.RegisterStruct((*ThriftTestTestTypedefArgs)(nil))
	thrift.RegisterStruct((*ThriftTestTestTypedefResult)(nil))
	thrift.RegisterStruct((*ThriftTestTestMapMapArgs)(nil))
	thrift.RegisterStruct((*ThriftTestTestMapMapResult)(nil))
	thrift.RegisterStruct((*ThriftTestTestInsanityArgs)(nil))
	thrift.RegisterStruct((*ThriftTestTestInsanityResult)(nil))
	thrift.RegisterStruct((*ThriftTestTestMultiArgs)(nil))
	thrift.RegisterStruct((*ThriftTestTestMultiResult)(nil))
	thrift.RegisterStruct((*ThriftTestTestExceptionArgs)(nil))
	thrift.RegisterStruct((*ThriftTestTestExceptionResult)(nil))
	thrift.RegisterStruct((*ThriftTestTestMultiExceptionArgs)(nil))
	thrift.RegisterStruct((*ThriftTestTestMultiExceptionResult)(nil))
	thrift.RegisterStruct((*ThriftTestTestOnewayArgs)(nil))
	thrift.RegisterService(secondServiceServiceDefinition)
	thrift.RegisterStruct((*SecondServiceBlahBlahArgs)(nil))
	thrift.RegisterStruct((*SecondServiceBlahBlahResult)(nil))
	thrift.RegisterStruct((*SecondServiceSecondtestStringArgs)(nil))
	thrift.RegisterStruct((*SecondServiceSecondtestStringResult)(nil))
}
