/**
 * Autogenerated by Thrift Compiler (v2.6.8-upfluence)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef duration_TYPES_H
#define duration_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <functional>
#include <memory>


namespace types { namespace known { namespace duration {

class Duration;


class Duration : public virtual ::apache::thrift::TBase {
 public:

  Duration(const Duration&);
  Duration& operator=(const Duration&);
  Duration() : seconds(0), nanos(0) {
  }

  virtual ~Duration() noexcept;
  int64_t seconds;
  int32_t nanos;

  void __set_seconds(const int64_t val);

  void __set_nanos(const int32_t val);

  bool operator == (const Duration & rhs) const
  {
    if (!(seconds == rhs.seconds))
      return false;
    if (!(nanos == rhs.nanos))
      return false;
    return true;
  }
  bool operator != (const Duration &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Duration & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(Duration &a, Duration &b);

std::ostream& operator<<(std::ostream& out, const Duration& obj);

}}} // namespace

#endif
