/**
 * Autogenerated by Thrift Compiler (2.5.4-upfluence)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef duration_CONSTANTS_H
#define duration_CONSTANTS_H

#include "duration_types.h"

namespace types { namespace known { namespace duration {

class durationConstants {
 public:
  durationConstants();

};

extern const durationConstants g_duration_constants;

}}} // namespace

#endif
