#
# Autogenerated by Thrift Compiler (v2.7.0-upfluence)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'thrift/types/constant_definition/constant_definition_types'

module Thrift
  module Types
    module Constant_definition
    end
  end
end
