#
# Autogenerated by Thrift Compiler (v2.7.0-upfluence)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'thrift/thrift/types/core/core_types'
require 'thrift/types/annotation_definition/annotation_definition_types'


module Thrift
  module Types
    module Constant_definition
      class ListConstantValueDefinition; end

      class MapConstantValueDefinitionEntry; end

      class MapConstantValueDefinition; end

      class ConstantValueDefinition < ::Thrift::Union; end

      class ConstantDefinition; end

      class ListConstantValueDefinition
        include ::Thrift::Struct, ::Thrift::Struct_Union

        NAME = 'ListConstantValueDefinition'.freeze
        NAMESPACE = 'types.constant_definition'.freeze

        LEGACY_ANNOTATIONS = {
        }.freeze

        STRUCTURED_ANNOTATIONS = [
        ].freeze

        THRIFT_FIELD_INDEX_VALUES = 1

        THRIFT_FIELD_VALUES_LEGACY_ANNOTATIONS = {
        }.freeze

        THRIFT_FIELD_VALUES_STRUCTURED_ANNOTATIONS = [
        ].freeze

        FIELDS = {
          THRIFT_FIELD_INDEX_VALUES => {type: ::Thrift::Types::LIST, name: 'values', element: {type: ::Thrift::Types::STRUCT, class: ::Thrift::Types::Constant_definition::ConstantValueDefinition}, legacy_annotations: THRIFT_FIELD_VALUES_LEGACY_ANNOTATIONS, structured_annotations: THRIFT_FIELD_VALUES_STRUCTURED_ANNOTATIONS}
        }

        def struct_fields; FIELDS; end

        def validate
          raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field values is unset!') unless @values
        end

        ::Thrift::Struct.generate_accessors self
        ::Thrift.register_struct_type self
      end

      class MapConstantValueDefinitionEntry
        include ::Thrift::Struct, ::Thrift::Struct_Union

        NAME = 'MapConstantValueDefinitionEntry'.freeze
        NAMESPACE = 'types.constant_definition'.freeze

        LEGACY_ANNOTATIONS = {
        }.freeze

        STRUCTURED_ANNOTATIONS = [
        ].freeze

        THRIFT_FIELD_INDEX_KEY = 1
        THRIFT_FIELD_INDEX_VALUE = 2

        THRIFT_FIELD_KEY_LEGACY_ANNOTATIONS = {
        }.freeze

        THRIFT_FIELD_KEY_STRUCTURED_ANNOTATIONS = [
        ].freeze

        THRIFT_FIELD_VALUE_LEGACY_ANNOTATIONS = {
        }.freeze

        THRIFT_FIELD_VALUE_STRUCTURED_ANNOTATIONS = [
        ].freeze

        FIELDS = {
          THRIFT_FIELD_INDEX_KEY => {type: ::Thrift::Types::STRUCT, name: 'key', class: ::Thrift::Types::Constant_definition::ConstantValueDefinition, legacy_annotations: THRIFT_FIELD_KEY_LEGACY_ANNOTATIONS, structured_annotations: THRIFT_FIELD_KEY_STRUCTURED_ANNOTATIONS},
          THRIFT_FIELD_INDEX_VALUE => {type: ::Thrift::Types::STRUCT, name: 'value', class: ::Thrift::Types::Constant_definition::ConstantValueDefinition, legacy_annotations: THRIFT_FIELD_VALUE_LEGACY_ANNOTATIONS, structured_annotations: THRIFT_FIELD_VALUE_STRUCTURED_ANNOTATIONS}
        }

        def struct_fields; FIELDS; end

        def validate
          raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field key is unset!') unless @key
          raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field value is unset!') unless @value
        end

        ::Thrift::Struct.generate_accessors self
        ::Thrift.register_struct_type self
      end

      class MapConstantValueDefinition
        include ::Thrift::Struct, ::Thrift::Struct_Union

        NAME = 'MapConstantValueDefinition'.freeze
        NAMESPACE = 'types.constant_definition'.freeze

        LEGACY_ANNOTATIONS = {
        }.freeze

        STRUCTURED_ANNOTATIONS = [
        ].freeze

        THRIFT_FIELD_INDEX_ENTRIES = 1

        THRIFT_FIELD_ENTRIES_LEGACY_ANNOTATIONS = {
        }.freeze

        THRIFT_FIELD_ENTRIES_STRUCTURED_ANNOTATIONS = [
        ].freeze

        FIELDS = {
          THRIFT_FIELD_INDEX_ENTRIES => {type: ::Thrift::Types::LIST, name: 'entries', element: {type: ::Thrift::Types::STRUCT, class: ::Thrift::Types::Constant_definition::MapConstantValueDefinitionEntry}, legacy_annotations: THRIFT_FIELD_ENTRIES_LEGACY_ANNOTATIONS, structured_annotations: THRIFT_FIELD_ENTRIES_STRUCTURED_ANNOTATIONS}
        }

        def struct_fields; FIELDS; end

        def validate
          raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field entries is unset!') unless @entries
        end

        ::Thrift::Struct.generate_accessors self
        ::Thrift.register_struct_type self
      end

      class ConstantValueDefinition < ::Thrift::Union
        include ::Thrift::Struct_Union

        NAME = 'ConstantValueDefinition'.freeze
        NAMESPACE = 'types.constant_definition'.freeze

        LEGACY_ANNOTATIONS = {
        }.freeze

        STRUCTURED_ANNOTATIONS = [
        ].freeze

        class << self
          def reference(val)
            ConstantValueDefinition.new(:reference, val)
          end

          def integer_value(val)
            ConstantValueDefinition.new(:integer_value, val)
          end

          def double_value(val)
            ConstantValueDefinition.new(:double_value, val)
          end

          def bool_value(val)
            ConstantValueDefinition.new(:bool_value, val)
          end

          def string_value(val)
            ConstantValueDefinition.new(:string_value, val)
          end

          def list_value(val)
            ConstantValueDefinition.new(:list_value, val)
          end

          def map_value(val)
            ConstantValueDefinition.new(:map_value, val)
          end
        end

        THRIFT_FIELD_INDEX_REFERENCE = 1
        THRIFT_FIELD_INDEX_INTEGER_VALUE = 2
        THRIFT_FIELD_INDEX_DOUBLE_VALUE = 3
        THRIFT_FIELD_INDEX_BOOL_VALUE = 4
        THRIFT_FIELD_INDEX_STRING_VALUE = 5
        THRIFT_FIELD_INDEX_LIST_VALUE = 6
        THRIFT_FIELD_INDEX_MAP_VALUE = 7

        THRIFT_FIELD_REFERENCE_LEGACY_ANNOTATIONS = {
        }.freeze

        THRIFT_FIELD_REFERENCE_STRUCTURED_ANNOTATIONS = [
        ].freeze

        THRIFT_FIELD_INTEGER_VALUE_LEGACY_ANNOTATIONS = {
        }.freeze

        THRIFT_FIELD_INTEGER_VALUE_STRUCTURED_ANNOTATIONS = [
        ].freeze

        THRIFT_FIELD_DOUBLE_VALUE_LEGACY_ANNOTATIONS = {
        }.freeze

        THRIFT_FIELD_DOUBLE_VALUE_STRUCTURED_ANNOTATIONS = [
        ].freeze

        THRIFT_FIELD_BOOL_VALUE_LEGACY_ANNOTATIONS = {
        }.freeze

        THRIFT_FIELD_BOOL_VALUE_STRUCTURED_ANNOTATIONS = [
        ].freeze

        THRIFT_FIELD_STRING_VALUE_LEGACY_ANNOTATIONS = {
        }.freeze

        THRIFT_FIELD_STRING_VALUE_STRUCTURED_ANNOTATIONS = [
        ].freeze

        THRIFT_FIELD_LIST_VALUE_LEGACY_ANNOTATIONS = {
        }.freeze

        THRIFT_FIELD_LIST_VALUE_STRUCTURED_ANNOTATIONS = [
        ].freeze

        THRIFT_FIELD_MAP_VALUE_LEGACY_ANNOTATIONS = {
        }.freeze

        THRIFT_FIELD_MAP_VALUE_STRUCTURED_ANNOTATIONS = [
        ].freeze

        FIELDS = {
          THRIFT_FIELD_INDEX_REFERENCE => {type: ::Thrift::Types::STRUCT, name: 'reference', class: ::Thrift::Thrift::Types::Core::Reference, optional: true, legacy_annotations: THRIFT_FIELD_REFERENCE_LEGACY_ANNOTATIONS, structured_annotations: THRIFT_FIELD_REFERENCE_STRUCTURED_ANNOTATIONS},
          THRIFT_FIELD_INDEX_INTEGER_VALUE => {type: ::Thrift::Types::I64, name: 'integer_value', optional: true, legacy_annotations: THRIFT_FIELD_INTEGER_VALUE_LEGACY_ANNOTATIONS, structured_annotations: THRIFT_FIELD_INTEGER_VALUE_STRUCTURED_ANNOTATIONS},
          THRIFT_FIELD_INDEX_DOUBLE_VALUE => {type: ::Thrift::Types::DOUBLE, name: 'double_value', optional: true, legacy_annotations: THRIFT_FIELD_DOUBLE_VALUE_LEGACY_ANNOTATIONS, structured_annotations: THRIFT_FIELD_DOUBLE_VALUE_STRUCTURED_ANNOTATIONS},
          THRIFT_FIELD_INDEX_BOOL_VALUE => {type: ::Thrift::Types::BOOL, name: 'bool_value', optional: true, legacy_annotations: THRIFT_FIELD_BOOL_VALUE_LEGACY_ANNOTATIONS, structured_annotations: THRIFT_FIELD_BOOL_VALUE_STRUCTURED_ANNOTATIONS},
          THRIFT_FIELD_INDEX_STRING_VALUE => {type: ::Thrift::Types::STRING, name: 'string_value', optional: true, legacy_annotations: THRIFT_FIELD_STRING_VALUE_LEGACY_ANNOTATIONS, structured_annotations: THRIFT_FIELD_STRING_VALUE_STRUCTURED_ANNOTATIONS},
          THRIFT_FIELD_INDEX_LIST_VALUE => {type: ::Thrift::Types::STRUCT, name: 'list_value', class: ::Thrift::Types::Constant_definition::ListConstantValueDefinition, optional: true, legacy_annotations: THRIFT_FIELD_LIST_VALUE_LEGACY_ANNOTATIONS, structured_annotations: THRIFT_FIELD_LIST_VALUE_STRUCTURED_ANNOTATIONS},
          THRIFT_FIELD_INDEX_MAP_VALUE => {type: ::Thrift::Types::STRUCT, name: 'map_value', class: ::Thrift::Types::Constant_definition::MapConstantValueDefinition, optional: true, legacy_annotations: THRIFT_FIELD_MAP_VALUE_LEGACY_ANNOTATIONS, structured_annotations: THRIFT_FIELD_MAP_VALUE_STRUCTURED_ANNOTATIONS}
        }

        def struct_fields; FIELDS; end

        def validate
          raise(StandardError, 'Union fields are not set.') if get_set_field.nil? || get_value.nil?
        end

        ::Thrift::Union.generate_accessors self
        ::Thrift.register_struct_type self
      end

      class ConstantDefinition
        include ::Thrift::Struct, ::Thrift::Struct_Union

        NAME = 'ConstantDefinition'.freeze
        NAMESPACE = 'types.constant_definition'.freeze

        LEGACY_ANNOTATIONS = {
        }.freeze

        STRUCTURED_ANNOTATIONS = [
        ].freeze

        THRIFT_FIELD_INDEX_ANNOTATION = 1
        THRIFT_FIELD_INDEX_VALUE = 2

        THRIFT_FIELD_ANNOTATION_LEGACY_ANNOTATIONS = {
        }.freeze

        THRIFT_FIELD_ANNOTATION_STRUCTURED_ANNOTATIONS = [
        ].freeze

        THRIFT_FIELD_VALUE_LEGACY_ANNOTATIONS = {
        }.freeze

        THRIFT_FIELD_VALUE_STRUCTURED_ANNOTATIONS = [
        ].freeze

        FIELDS = {
          THRIFT_FIELD_INDEX_ANNOTATION => {type: ::Thrift::Types::STRUCT, name: 'annotation', class: ::Thrift::Types::Annotation_definition::AnnotationDefinition, legacy_annotations: THRIFT_FIELD_ANNOTATION_LEGACY_ANNOTATIONS, structured_annotations: THRIFT_FIELD_ANNOTATION_STRUCTURED_ANNOTATIONS},
          THRIFT_FIELD_INDEX_VALUE => {type: ::Thrift::Types::STRUCT, name: 'value', class: ::Thrift::Types::Constant_definition::ConstantValueDefinition, optional: true, legacy_annotations: THRIFT_FIELD_VALUE_LEGACY_ANNOTATIONS, structured_annotations: THRIFT_FIELD_VALUE_STRUCTURED_ANNOTATIONS}
        }

        def struct_fields; FIELDS; end

        def validate
          raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field annotation is unset!') unless @annotation
        end

        ::Thrift::Struct.generate_accessors self
        ::Thrift.register_struct_type self
      end

    end
  end
end
