#
# Autogenerated by Thrift Compiler (2.5.4-upfluence)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'thrift/types/annotation/deprecation/deprecation_types'

module Thrift
  module Types
    module Annotation
      module Deprecation
      end
    end
  end
end
