#
# Autogenerated by Thrift Compiler (v2.6.8)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'thrift/types/known/any/any_types'

module Thrift
  module Types
    module Known
      module Any
      end
    end
  end
end
