// Autogenerated by Thrift Compiler (v2.6.8-upfluence)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package program_definition

import (
	"bytes"
	"context"
	"fmt"
	"github.com/upfluence/thrift/lib/go/thrift"
	"github.com/upfluence/thrift/lib/go/thrift/types/enum_definition"
	"github.com/upfluence/thrift/lib/go/thrift/types/service_definition"
	"github.com/upfluence/thrift/lib/go/thrift/types/struct_definition"
	"github.com/upfluence/thrift/lib/go/thrift/types/type_definition"
	"github.com/upfluence/thrift/lib/go/thrift/types/value"
	"reflect"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = context.Background
var _ = reflect.DeepEqual
var _ = bytes.Equal

var _ = enum_definition.GoUnusedProtection__
var _ = type_definition.GoUnusedProtection__
var _ = struct_definition.GoUnusedProtection__
var _ = service_definition.GoUnusedProtection__
var _ = value.GoUnusedProtection__

// Attributes:
//   - Name
//   - Path
//   - Doc
//   - Namespaces
//   - Includes
//   - Structs
//   - Services
//   - Constants
//   - Typedefs
//   - Enums
type ProgramDefinition struct {
	Name       string                                           `thrift:"name,1,required" db:"name" json:"name"`
	Path       string                                           `thrift:"path,2,required" db:"path" json:"path"`
	Doc        *string                                          `thrift:"doc,3" db:"doc" json:"doc,omitempty"`
	Namespaces map[string]string                                `thrift:"namespaces,4,required" db:"namespaces" json:"namespaces"`
	Includes   []*ProgramDefinition                             `thrift:"includes,5,required" db:"includes" json:"includes"`
	Structs    map[string]*struct_definition.StructDefinition   `thrift:"structs,6,required" db:"structs" json:"structs"`
	Services   map[string]*service_definition.ServiceDefinition `thrift:"services,7,required" db:"services" json:"services"`
	Constants  map[string]*value.ValueDefinition                `thrift:"constants,8,required" db:"constants" json:"constants"`
	Typedefs   map[string]*type_definition.TypeDefinition       `thrift:"typedefs,9,required" db:"typedefs" json:"typedefs"`
	Enums      map[string]*enum_definition.EnumDefinition       `thrift:"enums,10,required" db:"enums" json:"enums"`
}

func NewProgramDefinition() *ProgramDefinition {
	return &ProgramDefinition{}
}

var programDefinitionStructDefinition = thrift.StructDefinition{
	Namespace: Namespace,
	AnnotatedDefinition: thrift.AnnotatedDefinition{
		Name:                  "ProgramDefinition",
		LegacyAnnotations:     map[string]string{},
		StructuredAnnotations: []thrift.RegistrableStruct{},
	},
	Fields: []thrift.FieldDefinition{
		{
			AnnotatedDefinition: thrift.AnnotatedDefinition{
				Name:                  "name",
				LegacyAnnotations:     map[string]string{},
				StructuredAnnotations: []thrift.RegistrableStruct{},
			},
		},

		{
			AnnotatedDefinition: thrift.AnnotatedDefinition{
				Name:                  "path",
				LegacyAnnotations:     map[string]string{},
				StructuredAnnotations: []thrift.RegistrableStruct{},
			},
		},

		{
			AnnotatedDefinition: thrift.AnnotatedDefinition{
				Name:                  "doc",
				LegacyAnnotations:     map[string]string{},
				StructuredAnnotations: []thrift.RegistrableStruct{},
			},
		},

		{
			AnnotatedDefinition: thrift.AnnotatedDefinition{
				Name:                  "namespaces",
				LegacyAnnotations:     map[string]string{},
				StructuredAnnotations: []thrift.RegistrableStruct{},
			},
		},

		{
			AnnotatedDefinition: thrift.AnnotatedDefinition{
				Name:                  "includes",
				LegacyAnnotations:     map[string]string{},
				StructuredAnnotations: []thrift.RegistrableStruct{},
			},
		},

		{
			AnnotatedDefinition: thrift.AnnotatedDefinition{
				Name:                  "structs",
				LegacyAnnotations:     map[string]string{},
				StructuredAnnotations: []thrift.RegistrableStruct{},
			},
		},

		{
			AnnotatedDefinition: thrift.AnnotatedDefinition{
				Name:                  "services",
				LegacyAnnotations:     map[string]string{},
				StructuredAnnotations: []thrift.RegistrableStruct{},
			},
		},

		{
			AnnotatedDefinition: thrift.AnnotatedDefinition{
				Name:                  "constants",
				LegacyAnnotations:     map[string]string{},
				StructuredAnnotations: []thrift.RegistrableStruct{},
			},
		},

		{
			AnnotatedDefinition: thrift.AnnotatedDefinition{
				Name:                  "typedefs",
				LegacyAnnotations:     map[string]string{},
				StructuredAnnotations: []thrift.RegistrableStruct{},
			},
		},

		{
			AnnotatedDefinition: thrift.AnnotatedDefinition{
				Name:                  "enums",
				LegacyAnnotations:     map[string]string{},
				StructuredAnnotations: []thrift.RegistrableStruct{},
			},
		},
	},
}

func (p *ProgramDefinition) StructDefinition() thrift.StructDefinition {
	return programDefinitionStructDefinition
}

func (p *ProgramDefinition) GetName() string {
	return p.Name
}

func (p *ProgramDefinition) SetName(v string) {
	p.Name = v
}

func (p *ProgramDefinition) GetPath() string {
	return p.Path
}

func (p *ProgramDefinition) SetPath(v string) {
	p.Path = v
}

var ProgramDefinition_Doc_DEFAULT string

func (p *ProgramDefinition) GetDoc() string {
	if !p.IsSetDoc() {
		return ProgramDefinition_Doc_DEFAULT
	}
	return *p.Doc
}

func (p *ProgramDefinition) SetDoc(v string) {
	p.Doc = &v
}

func (p *ProgramDefinition) GetNamespaces() map[string]string {
	return p.Namespaces
}

func (p *ProgramDefinition) SetNamespaces(v map[string]string) {
	p.Namespaces = v
}

func (p *ProgramDefinition) GetIncludes() []*ProgramDefinition {
	return p.Includes
}

func (p *ProgramDefinition) SetIncludes(v []*ProgramDefinition) {
	p.Includes = v
}

func (p *ProgramDefinition) GetStructs() map[string]*struct_definition.StructDefinition {
	return p.Structs
}

func (p *ProgramDefinition) SetStructs(v map[string]*struct_definition.StructDefinition) {
	p.Structs = v
}

func (p *ProgramDefinition) GetServices() map[string]*service_definition.ServiceDefinition {
	return p.Services
}

func (p *ProgramDefinition) SetServices(v map[string]*service_definition.ServiceDefinition) {
	p.Services = v
}

func (p *ProgramDefinition) GetConstants() map[string]*value.ValueDefinition {
	return p.Constants
}

func (p *ProgramDefinition) SetConstants(v map[string]*value.ValueDefinition) {
	p.Constants = v
}

func (p *ProgramDefinition) GetTypedefs() map[string]*type_definition.TypeDefinition {
	return p.Typedefs
}

func (p *ProgramDefinition) SetTypedefs(v map[string]*type_definition.TypeDefinition) {
	p.Typedefs = v
}

func (p *ProgramDefinition) GetEnums() map[string]*enum_definition.EnumDefinition {
	return p.Enums
}

func (p *ProgramDefinition) SetEnums(v map[string]*enum_definition.EnumDefinition) {
	p.Enums = v
}
func (p *ProgramDefinition) IsSetDoc() bool {
	return p.Doc != nil
}

func (p *ProgramDefinition) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	var issetName bool = false
	var issetPath bool = false
	var issetNamespaces bool = false
	var issetIncludes bool = false
	var issetStructs bool = false
	var issetServices bool = false
	var issetConstants bool = false
	var issetTypedefs bool = false
	var issetEnums bool = false

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField1(iprot); err != nil {
					return err
				}
				issetName = true
			} else {
				if err := iprot.Skip(fieldTypeId); err != nil {
					return err
				}
			}
		case 2:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField2(iprot); err != nil {
					return err
				}
				issetPath = true
			} else {
				if err := iprot.Skip(fieldTypeId); err != nil {
					return err
				}
			}
		case 3:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField3(iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(fieldTypeId); err != nil {
					return err
				}
			}
		case 4:
			if fieldTypeId == thrift.MAP {
				if err := p.ReadField4(iprot); err != nil {
					return err
				}
				issetNamespaces = true
			} else {
				if err := iprot.Skip(fieldTypeId); err != nil {
					return err
				}
			}
		case 5:
			if fieldTypeId == thrift.LIST {
				if err := p.ReadField5(iprot); err != nil {
					return err
				}
				issetIncludes = true
			} else {
				if err := iprot.Skip(fieldTypeId); err != nil {
					return err
				}
			}
		case 6:
			if fieldTypeId == thrift.MAP {
				if err := p.ReadField6(iprot); err != nil {
					return err
				}
				issetStructs = true
			} else {
				if err := iprot.Skip(fieldTypeId); err != nil {
					return err
				}
			}
		case 7:
			if fieldTypeId == thrift.MAP {
				if err := p.ReadField7(iprot); err != nil {
					return err
				}
				issetServices = true
			} else {
				if err := iprot.Skip(fieldTypeId); err != nil {
					return err
				}
			}
		case 8:
			if fieldTypeId == thrift.MAP {
				if err := p.ReadField8(iprot); err != nil {
					return err
				}
				issetConstants = true
			} else {
				if err := iprot.Skip(fieldTypeId); err != nil {
					return err
				}
			}
		case 9:
			if fieldTypeId == thrift.MAP {
				if err := p.ReadField9(iprot); err != nil {
					return err
				}
				issetTypedefs = true
			} else {
				if err := iprot.Skip(fieldTypeId); err != nil {
					return err
				}
			}
		case 10:
			if fieldTypeId == thrift.MAP {
				if err := p.ReadField10(iprot); err != nil {
					return err
				}
				issetEnums = true
			} else {
				if err := iprot.Skip(fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	if !issetName {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Name is not set"))
	}
	if !issetPath {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Path is not set"))
	}
	if !issetNamespaces {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Namespaces is not set"))
	}
	if !issetIncludes {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Includes is not set"))
	}
	if !issetStructs {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Structs is not set"))
	}
	if !issetServices {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Services is not set"))
	}
	if !issetConstants {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Constants is not set"))
	}
	if !issetTypedefs {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Typedefs is not set"))
	}
	if !issetEnums {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Enums is not set"))
	}
	return nil
}

func (p *ProgramDefinition) ReadField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.Name = v
	}
	return nil
}

func (p *ProgramDefinition) ReadField2(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.Path = v
	}
	return nil
}

func (p *ProgramDefinition) ReadField3(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 3: ", err)
	} else {
		p.Doc = &v
	}
	return nil
}

func (p *ProgramDefinition) ReadField4(iprot thrift.TProtocol) error {
	_, _, size, err := iprot.ReadMapBegin()
	if err != nil {
		return thrift.PrependError("error reading map begin: ", err)
	}
	tMap := make(map[string]string, size)
	p.Namespaces = tMap
	for i := 0; i < size; i++ {
		var _key0 string
		if v, err := iprot.ReadString(); err != nil {
			return thrift.PrependError("error reading field 0: ", err)
		} else {
			_key0 = v
		}
		var _val1 string
		if v, err := iprot.ReadString(); err != nil {
			return thrift.PrependError("error reading field 0: ", err)
		} else {
			_val1 = v
		}
		p.Namespaces[_key0] = _val1
	}
	if err := iprot.ReadMapEnd(); err != nil {
		return thrift.PrependError("error reading map end: ", err)
	}
	return nil
}

func (p *ProgramDefinition) ReadField5(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return thrift.PrependError("error reading list begin: ", err)
	}
	tSlice := make([]*ProgramDefinition, 0, size)
	p.Includes = tSlice
	for i := 0; i < size; i++ {
		_elem2 := NewProgramDefinition()
		if err := _elem2.Read(iprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", _elem2), err)
		}
		p.Includes = append(p.Includes, _elem2)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return thrift.PrependError("error reading list end: ", err)
	}
	return nil
}

func (p *ProgramDefinition) ReadField6(iprot thrift.TProtocol) error {
	_, _, size, err := iprot.ReadMapBegin()
	if err != nil {
		return thrift.PrependError("error reading map begin: ", err)
	}
	tMap := make(map[string]*struct_definition.StructDefinition, size)
	p.Structs = tMap
	for i := 0; i < size; i++ {
		var _key3 string
		if v, err := iprot.ReadString(); err != nil {
			return thrift.PrependError("error reading field 0: ", err)
		} else {
			_key3 = v
		}
		_val4 := struct_definition.NewStructDefinition()
		if err := _val4.Read(iprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", _val4), err)
		}
		p.Structs[_key3] = _val4
	}
	if err := iprot.ReadMapEnd(); err != nil {
		return thrift.PrependError("error reading map end: ", err)
	}
	return nil
}

func (p *ProgramDefinition) ReadField7(iprot thrift.TProtocol) error {
	_, _, size, err := iprot.ReadMapBegin()
	if err != nil {
		return thrift.PrependError("error reading map begin: ", err)
	}
	tMap := make(map[string]*service_definition.ServiceDefinition, size)
	p.Services = tMap
	for i := 0; i < size; i++ {
		var _key5 string
		if v, err := iprot.ReadString(); err != nil {
			return thrift.PrependError("error reading field 0: ", err)
		} else {
			_key5 = v
		}
		_val6 := service_definition.NewServiceDefinition()
		if err := _val6.Read(iprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", _val6), err)
		}
		p.Services[_key5] = _val6
	}
	if err := iprot.ReadMapEnd(); err != nil {
		return thrift.PrependError("error reading map end: ", err)
	}
	return nil
}

func (p *ProgramDefinition) ReadField8(iprot thrift.TProtocol) error {
	_, _, size, err := iprot.ReadMapBegin()
	if err != nil {
		return thrift.PrependError("error reading map begin: ", err)
	}
	tMap := make(map[string]*value.ValueDefinition, size)
	p.Constants = tMap
	for i := 0; i < size; i++ {
		var _key7 string
		if v, err := iprot.ReadString(); err != nil {
			return thrift.PrependError("error reading field 0: ", err)
		} else {
			_key7 = v
		}
		_val8 := value.NewValueDefinition()
		if err := _val8.Read(iprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", _val8), err)
		}
		p.Constants[_key7] = _val8
	}
	if err := iprot.ReadMapEnd(); err != nil {
		return thrift.PrependError("error reading map end: ", err)
	}
	return nil
}

func (p *ProgramDefinition) ReadField9(iprot thrift.TProtocol) error {
	_, _, size, err := iprot.ReadMapBegin()
	if err != nil {
		return thrift.PrependError("error reading map begin: ", err)
	}
	tMap := make(map[string]*type_definition.TypeDefinition, size)
	p.Typedefs = tMap
	for i := 0; i < size; i++ {
		var _key9 string
		if v, err := iprot.ReadString(); err != nil {
			return thrift.PrependError("error reading field 0: ", err)
		} else {
			_key9 = v
		}
		_val10 := type_definition.NewTypeDefinition()
		if err := _val10.Read(iprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", _val10), err)
		}
		p.Typedefs[_key9] = _val10
	}
	if err := iprot.ReadMapEnd(); err != nil {
		return thrift.PrependError("error reading map end: ", err)
	}
	return nil
}

func (p *ProgramDefinition) ReadField10(iprot thrift.TProtocol) error {
	_, _, size, err := iprot.ReadMapBegin()
	if err != nil {
		return thrift.PrependError("error reading map begin: ", err)
	}
	tMap := make(map[string]*enum_definition.EnumDefinition, size)
	p.Enums = tMap
	for i := 0; i < size; i++ {
		var _key11 string
		if v, err := iprot.ReadString(); err != nil {
			return thrift.PrependError("error reading field 0: ", err)
		} else {
			_key11 = v
		}
		_val12 := enum_definition.NewEnumDefinition()
		if err := _val12.Read(iprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", _val12), err)
		}
		p.Enums[_key11] = _val12
	}
	if err := iprot.ReadMapEnd(); err != nil {
		return thrift.PrependError("error reading map end: ", err)
	}
	return nil
}

func (p *ProgramDefinition) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("ProgramDefinition"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(oprot); err != nil {
			return err
		}
		if err := p.writeField2(oprot); err != nil {
			return err
		}
		if err := p.writeField3(oprot); err != nil {
			return err
		}
		if err := p.writeField4(oprot); err != nil {
			return err
		}
		if err := p.writeField5(oprot); err != nil {
			return err
		}
		if err := p.writeField6(oprot); err != nil {
			return err
		}
		if err := p.writeField7(oprot); err != nil {
			return err
		}
		if err := p.writeField8(oprot); err != nil {
			return err
		}
		if err := p.writeField9(oprot); err != nil {
			return err
		}
		if err := p.writeField10(oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *ProgramDefinition) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("name", thrift.STRING, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:name: ", p), err)
	}
	if err := oprot.WriteString(string(p.Name)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.name (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:name: ", p), err)
	}
	return err
}

func (p *ProgramDefinition) writeField2(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("path", thrift.STRING, 2); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:path: ", p), err)
	}
	if err := oprot.WriteString(string(p.Path)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.path (2) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 2:path: ", p), err)
	}
	return err
}

func (p *ProgramDefinition) writeField3(oprot thrift.TProtocol) (err error) {
	if p.IsSetDoc() {
		if err := oprot.WriteFieldBegin("doc", thrift.STRING, 3); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:doc: ", p), err)
		}
		if err := oprot.WriteString(string(*p.Doc)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.doc (3) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 3:doc: ", p), err)
		}
	}
	return err
}

func (p *ProgramDefinition) writeField4(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("namespaces", thrift.MAP, 4); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:namespaces: ", p), err)
	}
	if err := oprot.WriteMapBegin(thrift.STRING, thrift.STRING, len(p.Namespaces)); err != nil {
		return thrift.PrependError("error writing map begin: ", err)
	}
	for k, v := range p.Namespaces {
		if err := oprot.WriteString(string(k)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
		}
		if err := oprot.WriteString(string(v)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
		}
	}
	if err := oprot.WriteMapEnd(); err != nil {
		return thrift.PrependError("error writing map end: ", err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 4:namespaces: ", p), err)
	}
	return err
}

func (p *ProgramDefinition) writeField5(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("includes", thrift.LIST, 5); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 5:includes: ", p), err)
	}
	if err := oprot.WriteListBegin(thrift.STRUCT, len(p.Includes)); err != nil {
		return thrift.PrependError("error writing list begin: ", err)
	}
	for _, v := range p.Includes {
		if err := v.Write(oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", v), err)
		}
	}
	if err := oprot.WriteListEnd(); err != nil {
		return thrift.PrependError("error writing list end: ", err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 5:includes: ", p), err)
	}
	return err
}

func (p *ProgramDefinition) writeField6(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("structs", thrift.MAP, 6); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 6:structs: ", p), err)
	}
	if err := oprot.WriteMapBegin(thrift.STRING, thrift.STRUCT, len(p.Structs)); err != nil {
		return thrift.PrependError("error writing map begin: ", err)
	}
	for k, v := range p.Structs {
		if err := oprot.WriteString(string(k)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
		}
		if err := v.Write(oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", v), err)
		}
	}
	if err := oprot.WriteMapEnd(); err != nil {
		return thrift.PrependError("error writing map end: ", err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 6:structs: ", p), err)
	}
	return err
}

func (p *ProgramDefinition) writeField7(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("services", thrift.MAP, 7); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 7:services: ", p), err)
	}
	if err := oprot.WriteMapBegin(thrift.STRING, thrift.STRUCT, len(p.Services)); err != nil {
		return thrift.PrependError("error writing map begin: ", err)
	}
	for k, v := range p.Services {
		if err := oprot.WriteString(string(k)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
		}
		if err := v.Write(oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", v), err)
		}
	}
	if err := oprot.WriteMapEnd(); err != nil {
		return thrift.PrependError("error writing map end: ", err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 7:services: ", p), err)
	}
	return err
}

func (p *ProgramDefinition) writeField8(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("constants", thrift.MAP, 8); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 8:constants: ", p), err)
	}
	if err := oprot.WriteMapBegin(thrift.STRING, thrift.STRUCT, len(p.Constants)); err != nil {
		return thrift.PrependError("error writing map begin: ", err)
	}
	for k, v := range p.Constants {
		if err := oprot.WriteString(string(k)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
		}
		if err := v.Write(oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", v), err)
		}
	}
	if err := oprot.WriteMapEnd(); err != nil {
		return thrift.PrependError("error writing map end: ", err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 8:constants: ", p), err)
	}
	return err
}

func (p *ProgramDefinition) writeField9(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("typedefs", thrift.MAP, 9); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 9:typedefs: ", p), err)
	}
	if err := oprot.WriteMapBegin(thrift.STRING, thrift.STRUCT, len(p.Typedefs)); err != nil {
		return thrift.PrependError("error writing map begin: ", err)
	}
	for k, v := range p.Typedefs {
		if err := oprot.WriteString(string(k)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
		}
		if err := v.Write(oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", v), err)
		}
	}
	if err := oprot.WriteMapEnd(); err != nil {
		return thrift.PrependError("error writing map end: ", err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 9:typedefs: ", p), err)
	}
	return err
}

func (p *ProgramDefinition) writeField10(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("enums", thrift.MAP, 10); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 10:enums: ", p), err)
	}
	if err := oprot.WriteMapBegin(thrift.STRING, thrift.STRUCT, len(p.Enums)); err != nil {
		return thrift.PrependError("error writing map begin: ", err)
	}
	for k, v := range p.Enums {
		if err := oprot.WriteString(string(k)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
		}
		if err := v.Write(oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", v), err)
		}
	}
	if err := oprot.WriteMapEnd(); err != nil {
		return thrift.PrependError("error writing map end: ", err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 10:enums: ", p), err)
	}
	return err
}

func (p *ProgramDefinition) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf(
		"ProgramDefinition({name: %v, path: %v, doc: %v, namespaces: %v, includes: %v, structs: %v, services: %v, constants: %v, typedefs: %v, enums: %v})",
		p.GetName(),
		p.GetPath(),
		p.GetDoc(),
		p.GetNamespaces(),
		p.GetIncludes(),
		p.GetStructs(),
		p.GetServices(),
		p.GetConstants(),
		p.GetTypedefs(),
		p.GetEnums(),
	)
}
