// Autogenerated by Thrift Compiler (2.7.0-upfluence)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package constant_definition

import (
	"bytes"
	"context"
	"fmt"
	"github.com/upfluence/thrift/lib/go/thrift"
	"github.com/upfluence/thrift/lib/go/thrift/types/annotation_definition"
	"github.com/upfluence/thrift/lib/go/thrift/types/core"
	"reflect"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = context.Background
var _ = reflect.DeepEqual
var _ = bytes.Equal

var _ = core.GoUnusedProtection__
var _ = annotation_definition.GoUnusedProtection__

// Attributes:
//   - Values
type ListConstantValueDefinition struct {
	Values []*ConstantValueDefinition `thrift:"values,1,required" db:"values" json:"values"`
}

func NewListConstantValueDefinition() *ListConstantValueDefinition {
	return &ListConstantValueDefinition{}
}

var listConstantValueDefinitionStructDefinition = thrift.StructDefinition{
	Namespace: Namespace,
	AnnotatedDefinition: thrift.AnnotatedDefinition{
		Name:                  "ListConstantValueDefinition",
		LegacyAnnotations:     map[string]string{},
		StructuredAnnotations: []thrift.RegistrableStruct{},
	},
	Fields: []thrift.FieldDefinition{
		{
			AnnotatedDefinition: thrift.AnnotatedDefinition{
				Name:                  "values",
				LegacyAnnotations:     map[string]string{},
				StructuredAnnotations: []thrift.RegistrableStruct{},
			},
		},
	},
}

func (p *ListConstantValueDefinition) StructDefinition() thrift.StructDefinition {
	return listConstantValueDefinitionStructDefinition
}

func (p *ListConstantValueDefinition) GetValues() []*ConstantValueDefinition {
	return p.Values
}

func (p *ListConstantValueDefinition) SetValues(v []*ConstantValueDefinition) {
	p.Values = v
}
func (p *ListConstantValueDefinition) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	var issetValues bool = false

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.LIST {
				if err := p.ReadField1(iprot); err != nil {
					return err
				}
				issetValues = true
			} else {
				if err := iprot.Skip(fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	if !issetValues {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Values is not set"))
	}
	return nil
}

func (p *ListConstantValueDefinition) ReadField1(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return thrift.PrependError("error reading list begin: ", err)
	}
	tSlice := make([]*ConstantValueDefinition, 0, size)
	p.Values = tSlice
	for i := 0; i < size; i++ {
		_elem0 := NewConstantValueDefinition()
		if err := _elem0.Read(iprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", _elem0), err)
		}
		p.Values = append(p.Values, _elem0)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return thrift.PrependError("error reading list end: ", err)
	}
	return nil
}

func (p *ListConstantValueDefinition) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("ListConstantValueDefinition"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *ListConstantValueDefinition) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("values", thrift.LIST, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:values: ", p), err)
	}
	if err := oprot.WriteListBegin(thrift.STRUCT, len(p.Values)); err != nil {
		return thrift.PrependError("error writing list begin: ", err)
	}
	for _, v := range p.Values {
		if err := v.Write(oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", v), err)
		}
	}
	if err := oprot.WriteListEnd(); err != nil {
		return thrift.PrependError("error writing list end: ", err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:values: ", p), err)
	}
	return err
}

func (p *ListConstantValueDefinition) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf(
		"ListConstantValueDefinition({values: %v})",
		p.GetValues(),
	)
}

// Attributes:
//   - Key
//   - Value
type MapConstantValueDefinitionEntry struct {
	Key   *ConstantValueDefinition `thrift:"key,1,required" db:"key" json:"key"`
	Value *ConstantValueDefinition `thrift:"value,2,required" db:"value" json:"value"`
}

func NewMapConstantValueDefinitionEntry() *MapConstantValueDefinitionEntry {
	return &MapConstantValueDefinitionEntry{}
}

var mapConstantValueDefinitionEntryStructDefinition = thrift.StructDefinition{
	Namespace: Namespace,
	AnnotatedDefinition: thrift.AnnotatedDefinition{
		Name:                  "MapConstantValueDefinitionEntry",
		LegacyAnnotations:     map[string]string{},
		StructuredAnnotations: []thrift.RegistrableStruct{},
	},
	Fields: []thrift.FieldDefinition{
		{
			AnnotatedDefinition: thrift.AnnotatedDefinition{
				Name:                  "key",
				LegacyAnnotations:     map[string]string{},
				StructuredAnnotations: []thrift.RegistrableStruct{},
			},
		},

		{
			AnnotatedDefinition: thrift.AnnotatedDefinition{
				Name:                  "value",
				LegacyAnnotations:     map[string]string{},
				StructuredAnnotations: []thrift.RegistrableStruct{},
			},
		},
	},
}

func (p *MapConstantValueDefinitionEntry) StructDefinition() thrift.StructDefinition {
	return mapConstantValueDefinitionEntryStructDefinition
}

var MapConstantValueDefinitionEntry_Key_DEFAULT *ConstantValueDefinition

func (p *MapConstantValueDefinitionEntry) GetKey() *ConstantValueDefinition {
	if !p.IsSetKey() {
		return MapConstantValueDefinitionEntry_Key_DEFAULT
	}
	return p.Key
}

func (p *MapConstantValueDefinitionEntry) SetKey(v *ConstantValueDefinition) {
	p.Key = v
}

var MapConstantValueDefinitionEntry_Value_DEFAULT *ConstantValueDefinition

func (p *MapConstantValueDefinitionEntry) GetValue() *ConstantValueDefinition {
	if !p.IsSetValue() {
		return MapConstantValueDefinitionEntry_Value_DEFAULT
	}
	return p.Value
}

func (p *MapConstantValueDefinitionEntry) SetValue(v *ConstantValueDefinition) {
	p.Value = v
}
func (p *MapConstantValueDefinitionEntry) IsSetKey() bool {
	return p.Key != nil
}

func (p *MapConstantValueDefinitionEntry) IsSetValue() bool {
	return p.Value != nil
}

func (p *MapConstantValueDefinitionEntry) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	var issetKey bool = false
	var issetValue bool = false

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField1(iprot); err != nil {
					return err
				}
				issetKey = true
			} else {
				if err := iprot.Skip(fieldTypeId); err != nil {
					return err
				}
			}
		case 2:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField2(iprot); err != nil {
					return err
				}
				issetValue = true
			} else {
				if err := iprot.Skip(fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	if !issetKey {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Key is not set"))
	}
	if !issetValue {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Value is not set"))
	}
	return nil
}

func (p *MapConstantValueDefinitionEntry) ReadField1(iprot thrift.TProtocol) error {
	p.Key = NewConstantValueDefinition()
	if err := p.Key.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Key), err)
	}
	return nil
}

func (p *MapConstantValueDefinitionEntry) ReadField2(iprot thrift.TProtocol) error {
	p.Value = NewConstantValueDefinition()
	if err := p.Value.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Value), err)
	}
	return nil
}

func (p *MapConstantValueDefinitionEntry) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("MapConstantValueDefinitionEntry"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(oprot); err != nil {
			return err
		}
		if err := p.writeField2(oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *MapConstantValueDefinitionEntry) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("key", thrift.STRUCT, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:key: ", p), err)
	}
	if err := p.Key.Write(oprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Key), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:key: ", p), err)
	}
	return err
}

func (p *MapConstantValueDefinitionEntry) writeField2(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("value", thrift.STRUCT, 2); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:value: ", p), err)
	}
	if err := p.Value.Write(oprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Value), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 2:value: ", p), err)
	}
	return err
}

func (p *MapConstantValueDefinitionEntry) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf(
		"MapConstantValueDefinitionEntry({key: %v, value: %v})",
		p.GetKey(),
		p.GetValue(),
	)
}

// Attributes:
//   - Entries
type MapConstantValueDefinition struct {
	Entries []*MapConstantValueDefinitionEntry `thrift:"entries,1,required" db:"entries" json:"entries"`
}

func NewMapConstantValueDefinition() *MapConstantValueDefinition {
	return &MapConstantValueDefinition{}
}

var mapConstantValueDefinitionStructDefinition = thrift.StructDefinition{
	Namespace: Namespace,
	AnnotatedDefinition: thrift.AnnotatedDefinition{
		Name:                  "MapConstantValueDefinition",
		LegacyAnnotations:     map[string]string{},
		StructuredAnnotations: []thrift.RegistrableStruct{},
	},
	Fields: []thrift.FieldDefinition{
		{
			AnnotatedDefinition: thrift.AnnotatedDefinition{
				Name:                  "entries",
				LegacyAnnotations:     map[string]string{},
				StructuredAnnotations: []thrift.RegistrableStruct{},
			},
		},
	},
}

func (p *MapConstantValueDefinition) StructDefinition() thrift.StructDefinition {
	return mapConstantValueDefinitionStructDefinition
}

func (p *MapConstantValueDefinition) GetEntries() []*MapConstantValueDefinitionEntry {
	return p.Entries
}

func (p *MapConstantValueDefinition) SetEntries(v []*MapConstantValueDefinitionEntry) {
	p.Entries = v
}
func (p *MapConstantValueDefinition) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	var issetEntries bool = false

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.LIST {
				if err := p.ReadField1(iprot); err != nil {
					return err
				}
				issetEntries = true
			} else {
				if err := iprot.Skip(fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	if !issetEntries {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Entries is not set"))
	}
	return nil
}

func (p *MapConstantValueDefinition) ReadField1(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return thrift.PrependError("error reading list begin: ", err)
	}
	tSlice := make([]*MapConstantValueDefinitionEntry, 0, size)
	p.Entries = tSlice
	for i := 0; i < size; i++ {
		_elem1 := NewMapConstantValueDefinitionEntry()
		if err := _elem1.Read(iprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", _elem1), err)
		}
		p.Entries = append(p.Entries, _elem1)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return thrift.PrependError("error reading list end: ", err)
	}
	return nil
}

func (p *MapConstantValueDefinition) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("MapConstantValueDefinition"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *MapConstantValueDefinition) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("entries", thrift.LIST, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:entries: ", p), err)
	}
	if err := oprot.WriteListBegin(thrift.STRUCT, len(p.Entries)); err != nil {
		return thrift.PrependError("error writing list begin: ", err)
	}
	for _, v := range p.Entries {
		if err := v.Write(oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", v), err)
		}
	}
	if err := oprot.WriteListEnd(); err != nil {
		return thrift.PrependError("error writing list end: ", err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:entries: ", p), err)
	}
	return err
}

func (p *MapConstantValueDefinition) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf(
		"MapConstantValueDefinition({entries: %v})",
		p.GetEntries(),
	)
}

// Attributes:
//   - Reference
//   - IntegerValue
//   - DoubleValue
//   - BoolValue
//   - StringValue
//   - ListValue
//   - MapValue
type ConstantValueDefinition struct {
	Reference    *core.Reference              `thrift:"reference,1" db:"reference" json:"reference,omitempty"`
	IntegerValue *int64                       `thrift:"integer_value,2" db:"integer_value" json:"integer_value,omitempty"`
	DoubleValue  *float64                     `thrift:"double_value,3" db:"double_value" json:"double_value,omitempty"`
	BoolValue    *bool                        `thrift:"bool_value,4" db:"bool_value" json:"bool_value,omitempty"`
	StringValue  *string                      `thrift:"string_value,5" db:"string_value" json:"string_value,omitempty"`
	ListValue    *ListConstantValueDefinition `thrift:"list_value,6" db:"list_value" json:"list_value,omitempty"`
	MapValue     *MapConstantValueDefinition  `thrift:"map_value,7" db:"map_value" json:"map_value,omitempty"`
}

func NewConstantValueDefinition() *ConstantValueDefinition {
	return &ConstantValueDefinition{}
}

var constantValueDefinitionStructDefinition = thrift.StructDefinition{
	Namespace: Namespace,
	IsUnion:   true,
	AnnotatedDefinition: thrift.AnnotatedDefinition{
		Name:                  "ConstantValueDefinition",
		LegacyAnnotations:     map[string]string{},
		StructuredAnnotations: []thrift.RegistrableStruct{},
	},
	Fields: []thrift.FieldDefinition{
		{
			AnnotatedDefinition: thrift.AnnotatedDefinition{
				Name:                  "reference",
				LegacyAnnotations:     map[string]string{},
				StructuredAnnotations: []thrift.RegistrableStruct{},
			},
		},

		{
			AnnotatedDefinition: thrift.AnnotatedDefinition{
				Name:                  "integer_value",
				LegacyAnnotations:     map[string]string{},
				StructuredAnnotations: []thrift.RegistrableStruct{},
			},
		},

		{
			AnnotatedDefinition: thrift.AnnotatedDefinition{
				Name:                  "double_value",
				LegacyAnnotations:     map[string]string{},
				StructuredAnnotations: []thrift.RegistrableStruct{},
			},
		},

		{
			AnnotatedDefinition: thrift.AnnotatedDefinition{
				Name:                  "bool_value",
				LegacyAnnotations:     map[string]string{},
				StructuredAnnotations: []thrift.RegistrableStruct{},
			},
		},

		{
			AnnotatedDefinition: thrift.AnnotatedDefinition{
				Name:                  "string_value",
				LegacyAnnotations:     map[string]string{},
				StructuredAnnotations: []thrift.RegistrableStruct{},
			},
		},

		{
			AnnotatedDefinition: thrift.AnnotatedDefinition{
				Name:                  "list_value",
				LegacyAnnotations:     map[string]string{},
				StructuredAnnotations: []thrift.RegistrableStruct{},
			},
		},

		{
			AnnotatedDefinition: thrift.AnnotatedDefinition{
				Name:                  "map_value",
				LegacyAnnotations:     map[string]string{},
				StructuredAnnotations: []thrift.RegistrableStruct{},
			},
		},
	},
}

func (p *ConstantValueDefinition) StructDefinition() thrift.StructDefinition {
	return constantValueDefinitionStructDefinition
}

var ConstantValueDefinition_Reference_DEFAULT *core.Reference

func (p *ConstantValueDefinition) GetReference() *core.Reference {
	if !p.IsSetReference() {
		return ConstantValueDefinition_Reference_DEFAULT
	}
	return p.Reference
}

func (p *ConstantValueDefinition) SetReference(v *core.Reference) {
	p.Reference = v
}

var ConstantValueDefinition_IntegerValue_DEFAULT int64

func (p *ConstantValueDefinition) GetIntegerValue() int64 {
	if !p.IsSetIntegerValue() {
		return ConstantValueDefinition_IntegerValue_DEFAULT
	}
	return *p.IntegerValue
}

func (p *ConstantValueDefinition) SetIntegerValue(v int64) {
	p.IntegerValue = &v
}

var ConstantValueDefinition_DoubleValue_DEFAULT float64

func (p *ConstantValueDefinition) GetDoubleValue() float64 {
	if !p.IsSetDoubleValue() {
		return ConstantValueDefinition_DoubleValue_DEFAULT
	}
	return *p.DoubleValue
}

func (p *ConstantValueDefinition) SetDoubleValue(v float64) {
	p.DoubleValue = &v
}

var ConstantValueDefinition_BoolValue_DEFAULT bool

func (p *ConstantValueDefinition) GetBoolValue() bool {
	if !p.IsSetBoolValue() {
		return ConstantValueDefinition_BoolValue_DEFAULT
	}
	return *p.BoolValue
}

func (p *ConstantValueDefinition) SetBoolValue(v bool) {
	p.BoolValue = &v
}

var ConstantValueDefinition_StringValue_DEFAULT string

func (p *ConstantValueDefinition) GetStringValue() string {
	if !p.IsSetStringValue() {
		return ConstantValueDefinition_StringValue_DEFAULT
	}
	return *p.StringValue
}

func (p *ConstantValueDefinition) SetStringValue(v string) {
	p.StringValue = &v
}

var ConstantValueDefinition_ListValue_DEFAULT *ListConstantValueDefinition

func (p *ConstantValueDefinition) GetListValue() *ListConstantValueDefinition {
	if !p.IsSetListValue() {
		return ConstantValueDefinition_ListValue_DEFAULT
	}
	return p.ListValue
}

func (p *ConstantValueDefinition) SetListValue(v *ListConstantValueDefinition) {
	p.ListValue = v
}

var ConstantValueDefinition_MapValue_DEFAULT *MapConstantValueDefinition

func (p *ConstantValueDefinition) GetMapValue() *MapConstantValueDefinition {
	if !p.IsSetMapValue() {
		return ConstantValueDefinition_MapValue_DEFAULT
	}
	return p.MapValue
}

func (p *ConstantValueDefinition) SetMapValue(v *MapConstantValueDefinition) {
	p.MapValue = v
}
func (p *ConstantValueDefinition) CountSetFieldsConstantValueDefinition() int {
	count := 0
	if p.IsSetReference() {
		count++
	}
	if p.IsSetIntegerValue() {
		count++
	}
	if p.IsSetDoubleValue() {
		count++
	}
	if p.IsSetBoolValue() {
		count++
	}
	if p.IsSetStringValue() {
		count++
	}
	if p.IsSetListValue() {
		count++
	}
	if p.IsSetMapValue() {
		count++
	}
	return count

}

func (p *ConstantValueDefinition) GetSetFieldsConstantValueDefinition() string {
	if p.IsSetReference() {
		return "reference"
	}
	if p.IsSetIntegerValue() {
		return "integer_value"
	}
	if p.IsSetDoubleValue() {
		return "double_value"
	}
	if p.IsSetBoolValue() {
		return "bool_value"
	}
	if p.IsSetStringValue() {
		return "string_value"
	}
	if p.IsSetListValue() {
		return "list_value"
	}
	if p.IsSetMapValue() {
		return "map_value"
	}
	return "<not set>"

}

func (p *ConstantValueDefinition) Interface() interface{} {
	if p.IsSetReference() {
		return p.Reference
	}
	if p.IsSetIntegerValue() {
		return p.IntegerValue
	}
	if p.IsSetDoubleValue() {
		return p.DoubleValue
	}
	if p.IsSetBoolValue() {
		return p.BoolValue
	}
	if p.IsSetStringValue() {
		return p.StringValue
	}
	if p.IsSetListValue() {
		return p.ListValue
	}
	if p.IsSetMapValue() {
		return p.MapValue
	}
	return nil

}

func (p *ConstantValueDefinition) IsSetReference() bool {
	return p.Reference != nil
}

func (p *ConstantValueDefinition) IsSetIntegerValue() bool {
	return p.IntegerValue != nil
}

func (p *ConstantValueDefinition) IsSetDoubleValue() bool {
	return p.DoubleValue != nil
}

func (p *ConstantValueDefinition) IsSetBoolValue() bool {
	return p.BoolValue != nil
}

func (p *ConstantValueDefinition) IsSetStringValue() bool {
	return p.StringValue != nil
}

func (p *ConstantValueDefinition) IsSetListValue() bool {
	return p.ListValue != nil
}

func (p *ConstantValueDefinition) IsSetMapValue() bool {
	return p.MapValue != nil
}

func (p *ConstantValueDefinition) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField1(iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(fieldTypeId); err != nil {
					return err
				}
			}
		case 2:
			if fieldTypeId == thrift.I64 {
				if err := p.ReadField2(iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(fieldTypeId); err != nil {
					return err
				}
			}
		case 3:
			if fieldTypeId == thrift.DOUBLE {
				if err := p.ReadField3(iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(fieldTypeId); err != nil {
					return err
				}
			}
		case 4:
			if fieldTypeId == thrift.BOOL {
				if err := p.ReadField4(iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(fieldTypeId); err != nil {
					return err
				}
			}
		case 5:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField5(iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(fieldTypeId); err != nil {
					return err
				}
			}
		case 6:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField6(iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(fieldTypeId); err != nil {
					return err
				}
			}
		case 7:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField7(iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *ConstantValueDefinition) ReadField1(iprot thrift.TProtocol) error {
	p.Reference = core.NewReference()
	if err := p.Reference.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Reference), err)
	}
	return nil
}

func (p *ConstantValueDefinition) ReadField2(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI64(); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.IntegerValue = &v
	}
	return nil
}

func (p *ConstantValueDefinition) ReadField3(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadDouble(); err != nil {
		return thrift.PrependError("error reading field 3: ", err)
	} else {
		p.DoubleValue = &v
	}
	return nil
}

func (p *ConstantValueDefinition) ReadField4(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadBool(); err != nil {
		return thrift.PrependError("error reading field 4: ", err)
	} else {
		p.BoolValue = &v
	}
	return nil
}

func (p *ConstantValueDefinition) ReadField5(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 5: ", err)
	} else {
		p.StringValue = &v
	}
	return nil
}

func (p *ConstantValueDefinition) ReadField6(iprot thrift.TProtocol) error {
	p.ListValue = NewListConstantValueDefinition()
	if err := p.ListValue.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.ListValue), err)
	}
	return nil
}

func (p *ConstantValueDefinition) ReadField7(iprot thrift.TProtocol) error {
	p.MapValue = NewMapConstantValueDefinition()
	if err := p.MapValue.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.MapValue), err)
	}
	return nil
}

func (p *ConstantValueDefinition) Write(oprot thrift.TProtocol) error {
	if c := p.CountSetFieldsConstantValueDefinition(); c != 1 {
		return fmt.Errorf("%T write union: exactly one field must be set (%d set).", p, c)
	}
	if err := oprot.WriteStructBegin("ConstantValueDefinition"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(oprot); err != nil {
			return err
		}
		if err := p.writeField2(oprot); err != nil {
			return err
		}
		if err := p.writeField3(oprot); err != nil {
			return err
		}
		if err := p.writeField4(oprot); err != nil {
			return err
		}
		if err := p.writeField5(oprot); err != nil {
			return err
		}
		if err := p.writeField6(oprot); err != nil {
			return err
		}
		if err := p.writeField7(oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *ConstantValueDefinition) writeField1(oprot thrift.TProtocol) (err error) {
	if p.IsSetReference() {
		if err := oprot.WriteFieldBegin("reference", thrift.STRUCT, 1); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:reference: ", p), err)
		}
		if err := p.Reference.Write(oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Reference), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 1:reference: ", p), err)
		}
	}
	return err
}

func (p *ConstantValueDefinition) writeField2(oprot thrift.TProtocol) (err error) {
	if p.IsSetIntegerValue() {
		if err := oprot.WriteFieldBegin("integer_value", thrift.I64, 2); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:integer_value: ", p), err)
		}
		if err := oprot.WriteI64(int64(*p.IntegerValue)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.integer_value (2) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 2:integer_value: ", p), err)
		}
	}
	return err
}

func (p *ConstantValueDefinition) writeField3(oprot thrift.TProtocol) (err error) {
	if p.IsSetDoubleValue() {
		if err := oprot.WriteFieldBegin("double_value", thrift.DOUBLE, 3); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:double_value: ", p), err)
		}
		if err := oprot.WriteDouble(float64(*p.DoubleValue)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.double_value (3) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 3:double_value: ", p), err)
		}
	}
	return err
}

func (p *ConstantValueDefinition) writeField4(oprot thrift.TProtocol) (err error) {
	if p.IsSetBoolValue() {
		if err := oprot.WriteFieldBegin("bool_value", thrift.BOOL, 4); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:bool_value: ", p), err)
		}
		if err := oprot.WriteBool(bool(*p.BoolValue)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.bool_value (4) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 4:bool_value: ", p), err)
		}
	}
	return err
}

func (p *ConstantValueDefinition) writeField5(oprot thrift.TProtocol) (err error) {
	if p.IsSetStringValue() {
		if err := oprot.WriteFieldBegin("string_value", thrift.STRING, 5); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 5:string_value: ", p), err)
		}
		if err := oprot.WriteString(string(*p.StringValue)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.string_value (5) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 5:string_value: ", p), err)
		}
	}
	return err
}

func (p *ConstantValueDefinition) writeField6(oprot thrift.TProtocol) (err error) {
	if p.IsSetListValue() {
		if err := oprot.WriteFieldBegin("list_value", thrift.STRUCT, 6); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 6:list_value: ", p), err)
		}
		if err := p.ListValue.Write(oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.ListValue), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 6:list_value: ", p), err)
		}
	}
	return err
}

func (p *ConstantValueDefinition) writeField7(oprot thrift.TProtocol) (err error) {
	if p.IsSetMapValue() {
		if err := oprot.WriteFieldBegin("map_value", thrift.STRUCT, 7); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 7:map_value: ", p), err)
		}
		if err := p.MapValue.Write(oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.MapValue), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 7:map_value: ", p), err)
		}
	}
	return err
}

func (p *ConstantValueDefinition) String() string {
	if p == nil {
		return "<nil>"
	}
	if p.CountSetFieldsConstantValueDefinition() == 0 {
		return "ConstantValueDefinition({<empty>})"
	}
	return fmt.Sprintf(
		"ConstantValueDefinition({%v: %v})",
		p.GetSetFieldsConstantValueDefinition(),
		p.Interface(),
	)
}

// Attributes:
//   - Annotation
//   - Value
type ConstantDefinition struct {
	Annotation *annotation_definition.AnnotationDefinition `thrift:"annotation,1,required" db:"annotation" json:"annotation"`
	Value      *ConstantValueDefinition                    `thrift:"value,2" db:"value" json:"value,omitempty"`
}

func NewConstantDefinition() *ConstantDefinition {
	return &ConstantDefinition{}
}

var constantDefinitionStructDefinition = thrift.StructDefinition{
	Namespace: Namespace,
	AnnotatedDefinition: thrift.AnnotatedDefinition{
		Name:                  "ConstantDefinition",
		LegacyAnnotations:     map[string]string{},
		StructuredAnnotations: []thrift.RegistrableStruct{},
	},
	Fields: []thrift.FieldDefinition{
		{
			AnnotatedDefinition: thrift.AnnotatedDefinition{
				Name:                  "annotation",
				LegacyAnnotations:     map[string]string{},
				StructuredAnnotations: []thrift.RegistrableStruct{},
			},
		},

		{
			AnnotatedDefinition: thrift.AnnotatedDefinition{
				Name:                  "value",
				LegacyAnnotations:     map[string]string{},
				StructuredAnnotations: []thrift.RegistrableStruct{},
			},
		},
	},
}

func (p *ConstantDefinition) StructDefinition() thrift.StructDefinition {
	return constantDefinitionStructDefinition
}

var ConstantDefinition_Annotation_DEFAULT *annotation_definition.AnnotationDefinition

func (p *ConstantDefinition) GetAnnotation() *annotation_definition.AnnotationDefinition {
	if !p.IsSetAnnotation() {
		return ConstantDefinition_Annotation_DEFAULT
	}
	return p.Annotation
}

func (p *ConstantDefinition) SetAnnotation(v *annotation_definition.AnnotationDefinition) {
	p.Annotation = v
}

var ConstantDefinition_Value_DEFAULT *ConstantValueDefinition

func (p *ConstantDefinition) GetValue() *ConstantValueDefinition {
	if !p.IsSetValue() {
		return ConstantDefinition_Value_DEFAULT
	}
	return p.Value
}

func (p *ConstantDefinition) SetValue(v *ConstantValueDefinition) {
	p.Value = v
}
func (p *ConstantDefinition) IsSetAnnotation() bool {
	return p.Annotation != nil
}

func (p *ConstantDefinition) IsSetValue() bool {
	return p.Value != nil
}

func (p *ConstantDefinition) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	var issetAnnotation bool = false

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField1(iprot); err != nil {
					return err
				}
				issetAnnotation = true
			} else {
				if err := iprot.Skip(fieldTypeId); err != nil {
					return err
				}
			}
		case 2:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField2(iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	if !issetAnnotation {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Annotation is not set"))
	}
	return nil
}

func (p *ConstantDefinition) ReadField1(iprot thrift.TProtocol) error {
	p.Annotation = annotation_definition.NewAnnotationDefinition()
	if err := p.Annotation.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Annotation), err)
	}
	return nil
}

func (p *ConstantDefinition) ReadField2(iprot thrift.TProtocol) error {
	p.Value = NewConstantValueDefinition()
	if err := p.Value.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Value), err)
	}
	return nil
}

func (p *ConstantDefinition) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("ConstantDefinition"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(oprot); err != nil {
			return err
		}
		if err := p.writeField2(oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *ConstantDefinition) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("annotation", thrift.STRUCT, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:annotation: ", p), err)
	}
	if err := p.Annotation.Write(oprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Annotation), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:annotation: ", p), err)
	}
	return err
}

func (p *ConstantDefinition) writeField2(oprot thrift.TProtocol) (err error) {
	if p.IsSetValue() {
		if err := oprot.WriteFieldBegin("value", thrift.STRUCT, 2); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:value: ", p), err)
		}
		if err := p.Value.Write(oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Value), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 2:value: ", p), err)
		}
	}
	return err
}

func (p *ConstantDefinition) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf(
		"ConstantDefinition({annotation: %v, value: %v})",
		p.GetAnnotation(),
		p.GetValue(),
	)
}
