#
# Autogenerated by Thrift Compiler (2.7.0-upfluence)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'types/annotation/deprecation/deprecation_types'

module Types
  module Annotation
    module Deprecation
      ::Thrift.register_program_definition('CwABAAAAC2RlcHJlY2F0aW9uCwACAAAAVi9Vc2Vycy9hbGV4aXMvY29kZS9zcmMvZ2l0aHViLmNvbS91cGZsdWVuY2UvdGhyaWZ0L3R5cGVzL2Fubm90YXRpb24vZGVwcmVjYXRpb24udGhyaWZ0DQAECwsAAAABAAAAASoAAAAcdHlwZXMuYW5ub3RhdGlvbi5kZXByZWNhdGlvbg8ABQwAAAAADQAGCwwAAAABAAAACkRlcHJlY2F0ZWQMAAELAAEAAAAKRGVwcmVjYXRlZA8AAgwAAAAADQADCwsAAAAAAAgAAgAAAAEPAAMMAAAAAAANAAcLDAAAAAANAAgLDAAAAAANAAkLDAAAAAANAAoLDAAAAAAA')
    end
  end
end
