/**
 * Autogenerated by Thrift Compiler (v2.6.8-upfluence)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef annotation_definition_CONSTANTS_H
#define annotation_definition_CONSTANTS_H

#include "annotation_definition_types.h"

namespace types { namespace annotation_definition {

class annotation_definitionConstants {
 public:
  annotation_definitionConstants();

};

extern const annotation_definitionConstants g_annotation_definition_constants;

}} // namespace

#endif
