/**
 * Autogenerated by Thrift Compiler (v2.6.8-upfluence)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "annotation_definition_constants.h"

namespace types { namespace annotation_definition {

const annotation_definitionConstants g_annotation_definition_constants;

annotation_definitionConstants::annotation_definitionConstants() {
}

}} // namespace

