/**
 * Autogenerated by Thrift Compiler (2.7.0-upfluence)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "constant_definition_constants.h"

namespace types { namespace constant_definition {

const constant_definitionConstants g_constant_definition_constants;

constant_definitionConstants::constant_definitionConstants() {
}

}} // namespace

