/**
 * Autogenerated by Thrift Compiler (2.7.0-upfluence)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "core_constants.h"

namespace types { namespace core {

const coreConstants g_core_constants;

coreConstants::coreConstants() {
}

}} // namespace

