/**
 * Autogenerated by Thrift Compiler (v2.7.0-upfluence)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "enum_definition_constants.h"

namespace types { namespace enum_definition {

const enum_definitionConstants g_enum_definition_constants;

enum_definitionConstants::enum_definitionConstants() {
}

}} // namespace

