/**
 * Autogenerated by Thrift Compiler (2.7.0-upfluence)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef enum_definition_CONSTANTS_H
#define enum_definition_CONSTANTS_H

#include "enum_definition_types.h"

namespace types { namespace enum_definition {

class enum_definitionConstants {
 public:
  enum_definitionConstants();

};

extern const enum_definitionConstants g_enum_definition_constants;

}} // namespace

#endif
