/**
 * Autogenerated by Thrift Compiler (v2.7.0-upfluence)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "plugin_constants.h"

namespace types { namespace plugin {

const pluginConstants g_plugin_constants;

pluginConstants::pluginConstants() {
}

}} // namespace

