/**
 * Autogenerated by Thrift Compiler (v2.7.0-upfluence)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Plugin_H
#define Plugin_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include <memory>
#include "plugin_types.h"

namespace types { namespace plugin {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class PluginIf {
 public:
  virtual ~PluginIf() {}
  virtual void generate_code(GenerateCodeResponse& _return, const GenerateCodeRequest& req) = 0;
};

class PluginIfFactory {
 public:
  typedef PluginIf Handler;

  virtual ~PluginIfFactory() {}

  virtual PluginIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(PluginIf* /* handler */) = 0;
};

class PluginIfSingletonFactory : virtual public PluginIfFactory {
 public:
  PluginIfSingletonFactory(const ::std::shared_ptr<PluginIf>& iface) : iface_(iface) {}
  virtual ~PluginIfSingletonFactory() {}

  virtual PluginIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(PluginIf* /* handler */) {}

 protected:
  ::std::shared_ptr<PluginIf> iface_;
};

class PluginNull : virtual public PluginIf {
 public:
  virtual ~PluginNull() {}
  void generate_code(GenerateCodeResponse& /* _return */, const GenerateCodeRequest& /* req */) {
    return;
  }
};

typedef struct _Plugin_generate_code_args__isset {
  _Plugin_generate_code_args__isset() : req(false) {}
  bool req :1;
} _Plugin_generate_code_args__isset;

class Plugin_generate_code_args {
 public:

  Plugin_generate_code_args(const Plugin_generate_code_args&);
  Plugin_generate_code_args& operator=(const Plugin_generate_code_args&);
  Plugin_generate_code_args() {
  }

  virtual ~Plugin_generate_code_args() noexcept;
  GenerateCodeRequest req;

  _Plugin_generate_code_args__isset __isset;

  void __set_req(const GenerateCodeRequest& val);

  bool operator == (const Plugin_generate_code_args & rhs) const
  {
    if (!(req == rhs.req))
      return false;
    return true;
  }
  bool operator != (const Plugin_generate_code_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Plugin_generate_code_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class Plugin_generate_code_pargs {
 public:


  virtual ~Plugin_generate_code_pargs() noexcept;
  const GenerateCodeRequest* req;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Plugin_generate_code_result__isset {
  _Plugin_generate_code_result__isset() : success(false) {}
  bool success :1;
} _Plugin_generate_code_result__isset;

class Plugin_generate_code_result {
 public:

  Plugin_generate_code_result(const Plugin_generate_code_result&);
  Plugin_generate_code_result& operator=(const Plugin_generate_code_result&);
  Plugin_generate_code_result() {
  }

  virtual ~Plugin_generate_code_result() noexcept;
  GenerateCodeResponse success;

  _Plugin_generate_code_result__isset __isset;

  void __set_success(const GenerateCodeResponse& val);

  bool operator == (const Plugin_generate_code_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const Plugin_generate_code_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Plugin_generate_code_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _Plugin_generate_code_presult__isset {
  _Plugin_generate_code_presult__isset() : success(false) {}
  bool success :1;
} _Plugin_generate_code_presult__isset;

class Plugin_generate_code_presult {
 public:


  virtual ~Plugin_generate_code_presult() noexcept;
  GenerateCodeResponse* success;

  _Plugin_generate_code_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class PluginClient : virtual public PluginIf {
 public:
  PluginClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  PluginClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void generate_code(GenerateCodeResponse& _return, const GenerateCodeRequest& req);
  void send_generate_code(const GenerateCodeRequest& req);
  void recv_generate_code(GenerateCodeResponse& _return);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class PluginProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::std::shared_ptr<PluginIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (PluginProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_generate_code(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  PluginProcessor(::std::shared_ptr<PluginIf> iface) :
    iface_(iface) {
    processMap_["generate_code"] = &PluginProcessor::process_generate_code;
  }

  virtual ~PluginProcessor() {}
};

class PluginProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  PluginProcessorFactory(const ::std::shared_ptr< PluginIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::std::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::std::shared_ptr< PluginIfFactory > handlerFactory_;
};

class PluginMultiface : virtual public PluginIf {
 public:
  PluginMultiface(std::vector<std::shared_ptr<PluginIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~PluginMultiface() {}
 protected:
  std::vector<std::shared_ptr<PluginIf> > ifaces_;
  PluginMultiface() {}
  void add(::std::shared_ptr<PluginIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void generate_code(GenerateCodeResponse& _return, const GenerateCodeRequest& req) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->generate_code(_return, req);
    }
    ifaces_[i]->generate_code(_return, req);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class PluginConcurrentClient : virtual public PluginIf {
 public:
  PluginConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(prot);
  }
  PluginConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot, std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void generate_code(GenerateCodeResponse& _return, const GenerateCodeRequest& req);
  int32_t send_generate_code(const GenerateCodeRequest& req);
  void recv_generate_code(GenerateCodeResponse& _return, const int32_t seqid);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  std::shared_ptr<::apache::thrift::async::TConcurrentClientSyncInfo> sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

}} // namespace

#endif
