/**
 * Autogenerated by Thrift Compiler (v2.7.0-upfluence)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "plugin_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace types { namespace plugin {


GenerateCodeRequest::~GenerateCodeRequest() noexcept {
}


void GenerateCodeRequest::__set_program(const  ::types::program_definition::ProgramDefinition& val) {
  this->program = val;
}

void GenerateCodeRequest::__set_language(const std::string& val) {
  this->language = val;
}

void GenerateCodeRequest::__set_options(const std::map<std::string, std::string> & val) {
  this->options = val;
}
std::ostream& operator<<(std::ostream& out, const GenerateCodeRequest& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t GenerateCodeRequest::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_program = false;
  bool isset_language = false;
  bool isset_options = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->program.read(iprot);
          isset_program = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->language);
          isset_language = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_MAP) {
          {
            this->options.clear();
            uint32_t _size0;
            ::apache::thrift::protocol::TType _ktype1;
            ::apache::thrift::protocol::TType _vtype2;
            xfer += iprot->readMapBegin(_ktype1, _vtype2, _size0);
            uint32_t _i4;
            for (_i4 = 0; _i4 < _size0; ++_i4)
            {
              std::string _key5;
              xfer += iprot->readString(_key5);
              std::string& _val6 = this->options[_key5];
              xfer += iprot->readString(_val6);
            }
            xfer += iprot->readMapEnd();
          }
          isset_options = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_program)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_language)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_options)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t GenerateCodeRequest::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("GenerateCodeRequest");

  xfer += oprot->writeFieldBegin("program", ::apache::thrift::protocol::T_STRUCT, 1);
  xfer += this->program.write(oprot);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("language", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->language);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("options", ::apache::thrift::protocol::T_MAP, 3);
  {
    xfer += oprot->writeMapBegin(::apache::thrift::protocol::T_STRING, ::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->options.size()));
    std::map<std::string, std::string> ::const_iterator _iter7;
    for (_iter7 = this->options.begin(); _iter7 != this->options.end(); ++_iter7)
    {
      xfer += oprot->writeString(_iter7->first);
      xfer += oprot->writeString(_iter7->second);
    }
    xfer += oprot->writeMapEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(GenerateCodeRequest &a, GenerateCodeRequest &b) {
  using ::std::swap;
  swap(a.program, b.program);
  swap(a.language, b.language);
  swap(a.options, b.options);
}

GenerateCodeRequest::GenerateCodeRequest(const GenerateCodeRequest& other8) {
  program = other8.program;
  language = other8.language;
  options = other8.options;
}
GenerateCodeRequest& GenerateCodeRequest::operator=(const GenerateCodeRequest& other9) {
  program = other9.program;
  language = other9.language;
  options = other9.options;
  return *this;
}
void GenerateCodeRequest::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "GenerateCodeRequest(";
  out << "program=" << to_string(program);
  out << ", " << "language=" << to_string(language);
  out << ", " << "options=" << to_string(options);
  out << ")";
}


GenerateCodeResponse::~GenerateCodeResponse() noexcept {
}


void GenerateCodeResponse::__set_files(const std::map<std::string, std::string> & val) {
  this->files = val;
}
std::ostream& operator<<(std::ostream& out, const GenerateCodeResponse& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t GenerateCodeResponse::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_files = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_MAP) {
          {
            this->files.clear();
            uint32_t _size10;
            ::apache::thrift::protocol::TType _ktype11;
            ::apache::thrift::protocol::TType _vtype12;
            xfer += iprot->readMapBegin(_ktype11, _vtype12, _size10);
            uint32_t _i14;
            for (_i14 = 0; _i14 < _size10; ++_i14)
            {
              std::string _key15;
              xfer += iprot->readString(_key15);
              std::string& _val16 = this->files[_key15];
              xfer += iprot->readBinary(_val16);
            }
            xfer += iprot->readMapEnd();
          }
          isset_files = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_files)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t GenerateCodeResponse::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("GenerateCodeResponse");

  xfer += oprot->writeFieldBegin("files", ::apache::thrift::protocol::T_MAP, 1);
  {
    xfer += oprot->writeMapBegin(::apache::thrift::protocol::T_STRING, ::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->files.size()));
    std::map<std::string, std::string> ::const_iterator _iter17;
    for (_iter17 = this->files.begin(); _iter17 != this->files.end(); ++_iter17)
    {
      xfer += oprot->writeString(_iter17->first);
      xfer += oprot->writeBinary(_iter17->second);
    }
    xfer += oprot->writeMapEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(GenerateCodeResponse &a, GenerateCodeResponse &b) {
  using ::std::swap;
  swap(a.files, b.files);
}

GenerateCodeResponse::GenerateCodeResponse(const GenerateCodeResponse& other18) {
  files = other18.files;
}
GenerateCodeResponse& GenerateCodeResponse::operator=(const GenerateCodeResponse& other19) {
  files = other19.files;
  return *this;
}
void GenerateCodeResponse::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "GenerateCodeResponse(";
  out << "files=" << to_string(files);
  out << ")";
}

}} // namespace
