/**
 * Autogenerated by Thrift Compiler (2.7.0-upfluence)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "program_definition_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace types { namespace program_definition {


ProgramDefinition::~ProgramDefinition() noexcept {
}


void ProgramDefinition::__set_name(const std::string& val) {
  this->name = val;
}

void ProgramDefinition::__set_path(const std::string& val) {
  this->path = val;
}

void ProgramDefinition::__set_doc(const std::string& val) {
  this->doc = val;
__isset.doc = true;
}

void ProgramDefinition::__set_namespaces(const std::map<std::string, std::string> & val) {
  this->namespaces = val;
}

void ProgramDefinition::__set_includes(const std::vector<ProgramDefinition> & val) {
  this->includes = val;
}

void ProgramDefinition::__set_structs(const std::map<std::string,  ::types::struct_definition::StructDefinition> & val) {
  this->structs = val;
}

void ProgramDefinition::__set_services(const std::map<std::string,  ::types::service_definition::ServiceDefinition> & val) {
  this->services = val;
}

void ProgramDefinition::__set_constants(const std::map<std::string,  ::types::constant_definition::ConstantDefinition> & val) {
  this->constants = val;
}

void ProgramDefinition::__set_typedefs(const std::map<std::string,  ::types::type_definition::TypeDefinition> & val) {
  this->typedefs = val;
}

void ProgramDefinition::__set_enums(const std::map<std::string,  ::types::enum_definition::EnumDefinition> & val) {
  this->enums = val;
}

void ProgramDefinition::__set_stdlib(const bool val) {
  this->stdlib = val;
}

void ProgramDefinition::__set_namespace_annotations(const std::map<std::string, std::map<std::string, std::string> > & val) {
  this->namespace_annotations = val;
__isset.namespace_annotations = true;
}

void ProgramDefinition::__set_cpp_includes(const std::vector<std::string> & val) {
  this->cpp_includes = val;
__isset.cpp_includes = true;
}
std::ostream& operator<<(std::ostream& out, const ProgramDefinition& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t ProgramDefinition::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_name = false;
  bool isset_path = false;
  bool isset_namespaces = false;
  bool isset_includes = false;
  bool isset_structs = false;
  bool isset_services = false;
  bool isset_constants = false;
  bool isset_typedefs = false;
  bool isset_enums = false;
  bool isset_stdlib = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->name);
          isset_name = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->path);
          isset_path = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->doc);
          this->__isset.doc = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_MAP) {
          {
            this->namespaces.clear();
            uint32_t _size0;
            ::apache::thrift::protocol::TType _ktype1;
            ::apache::thrift::protocol::TType _vtype2;
            xfer += iprot->readMapBegin(_ktype1, _vtype2, _size0);
            uint32_t _i4;
            for (_i4 = 0; _i4 < _size0; ++_i4)
            {
              std::string _key5;
              xfer += iprot->readString(_key5);
              std::string& _val6 = this->namespaces[_key5];
              xfer += iprot->readString(_val6);
            }
            xfer += iprot->readMapEnd();
          }
          isset_namespaces = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->includes.clear();
            uint32_t _size7;
            ::apache::thrift::protocol::TType _etype10;
            xfer += iprot->readListBegin(_etype10, _size7);
            this->includes.resize(_size7);
            uint32_t _i11;
            for (_i11 = 0; _i11 < _size7; ++_i11)
            {
              xfer += this->includes[_i11].read(iprot);
            }
            xfer += iprot->readListEnd();
          }
          isset_includes = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 6:
        if (ftype == ::apache::thrift::protocol::T_MAP) {
          {
            this->structs.clear();
            uint32_t _size12;
            ::apache::thrift::protocol::TType _ktype13;
            ::apache::thrift::protocol::TType _vtype14;
            xfer += iprot->readMapBegin(_ktype13, _vtype14, _size12);
            uint32_t _i16;
            for (_i16 = 0; _i16 < _size12; ++_i16)
            {
              std::string _key17;
              xfer += iprot->readString(_key17);
               ::types::struct_definition::StructDefinition& _val18 = this->structs[_key17];
              xfer += _val18.read(iprot);
            }
            xfer += iprot->readMapEnd();
          }
          isset_structs = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 7:
        if (ftype == ::apache::thrift::protocol::T_MAP) {
          {
            this->services.clear();
            uint32_t _size19;
            ::apache::thrift::protocol::TType _ktype20;
            ::apache::thrift::protocol::TType _vtype21;
            xfer += iprot->readMapBegin(_ktype20, _vtype21, _size19);
            uint32_t _i23;
            for (_i23 = 0; _i23 < _size19; ++_i23)
            {
              std::string _key24;
              xfer += iprot->readString(_key24);
               ::types::service_definition::ServiceDefinition& _val25 = this->services[_key24];
              xfer += _val25.read(iprot);
            }
            xfer += iprot->readMapEnd();
          }
          isset_services = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 8:
        if (ftype == ::apache::thrift::protocol::T_MAP) {
          {
            this->constants.clear();
            uint32_t _size26;
            ::apache::thrift::protocol::TType _ktype27;
            ::apache::thrift::protocol::TType _vtype28;
            xfer += iprot->readMapBegin(_ktype27, _vtype28, _size26);
            uint32_t _i30;
            for (_i30 = 0; _i30 < _size26; ++_i30)
            {
              std::string _key31;
              xfer += iprot->readString(_key31);
               ::types::constant_definition::ConstantDefinition& _val32 = this->constants[_key31];
              xfer += _val32.read(iprot);
            }
            xfer += iprot->readMapEnd();
          }
          isset_constants = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 9:
        if (ftype == ::apache::thrift::protocol::T_MAP) {
          {
            this->typedefs.clear();
            uint32_t _size33;
            ::apache::thrift::protocol::TType _ktype34;
            ::apache::thrift::protocol::TType _vtype35;
            xfer += iprot->readMapBegin(_ktype34, _vtype35, _size33);
            uint32_t _i37;
            for (_i37 = 0; _i37 < _size33; ++_i37)
            {
              std::string _key38;
              xfer += iprot->readString(_key38);
               ::types::type_definition::TypeDefinition& _val39 = this->typedefs[_key38];
              xfer += _val39.read(iprot);
            }
            xfer += iprot->readMapEnd();
          }
          isset_typedefs = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 10:
        if (ftype == ::apache::thrift::protocol::T_MAP) {
          {
            this->enums.clear();
            uint32_t _size40;
            ::apache::thrift::protocol::TType _ktype41;
            ::apache::thrift::protocol::TType _vtype42;
            xfer += iprot->readMapBegin(_ktype41, _vtype42, _size40);
            uint32_t _i44;
            for (_i44 = 0; _i44 < _size40; ++_i44)
            {
              std::string _key45;
              xfer += iprot->readString(_key45);
               ::types::enum_definition::EnumDefinition& _val46 = this->enums[_key45];
              xfer += _val46.read(iprot);
            }
            xfer += iprot->readMapEnd();
          }
          isset_enums = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 11:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->stdlib);
          isset_stdlib = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 12:
        if (ftype == ::apache::thrift::protocol::T_MAP) {
          {
            this->namespace_annotations.clear();
            uint32_t _size47;
            ::apache::thrift::protocol::TType _ktype48;
            ::apache::thrift::protocol::TType _vtype49;
            xfer += iprot->readMapBegin(_ktype48, _vtype49, _size47);
            uint32_t _i51;
            for (_i51 = 0; _i51 < _size47; ++_i51)
            {
              std::string _key52;
              xfer += iprot->readString(_key52);
              std::map<std::string, std::string> & _val53 = this->namespace_annotations[_key52];
              {
                _val53.clear();
                uint32_t _size54;
                ::apache::thrift::protocol::TType _ktype55;
                ::apache::thrift::protocol::TType _vtype56;
                xfer += iprot->readMapBegin(_ktype55, _vtype56, _size54);
                uint32_t _i58;
                for (_i58 = 0; _i58 < _size54; ++_i58)
                {
                  std::string _key59;
                  xfer += iprot->readString(_key59);
                  std::string& _val60 = _val53[_key59];
                  xfer += iprot->readString(_val60);
                }
                xfer += iprot->readMapEnd();
              }
            }
            xfer += iprot->readMapEnd();
          }
          this->__isset.namespace_annotations = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 13:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->cpp_includes.clear();
            uint32_t _size61;
            ::apache::thrift::protocol::TType _etype64;
            xfer += iprot->readListBegin(_etype64, _size61);
            this->cpp_includes.resize(_size61);
            uint32_t _i65;
            for (_i65 = 0; _i65 < _size61; ++_i65)
            {
              xfer += iprot->readString(this->cpp_includes[_i65]);
            }
            xfer += iprot->readListEnd();
          }
          this->__isset.cpp_includes = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_name)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_path)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_namespaces)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_includes)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_structs)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_services)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_constants)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_typedefs)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_enums)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_stdlib)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t ProgramDefinition::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("ProgramDefinition");

  xfer += oprot->writeFieldBegin("name", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->name);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("path", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->path);
  xfer += oprot->writeFieldEnd();

  if (this->__isset.doc) {
    xfer += oprot->writeFieldBegin("doc", ::apache::thrift::protocol::T_STRING, 3);
    xfer += oprot->writeString(this->doc);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldBegin("namespaces", ::apache::thrift::protocol::T_MAP, 4);
  {
    xfer += oprot->writeMapBegin(::apache::thrift::protocol::T_STRING, ::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->namespaces.size()));
    std::map<std::string, std::string> ::const_iterator _iter66;
    for (_iter66 = this->namespaces.begin(); _iter66 != this->namespaces.end(); ++_iter66)
    {
      xfer += oprot->writeString(_iter66->first);
      xfer += oprot->writeString(_iter66->second);
    }
    xfer += oprot->writeMapEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("includes", ::apache::thrift::protocol::T_LIST, 5);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->includes.size()));
    std::vector<ProgramDefinition> ::const_iterator _iter67;
    for (_iter67 = this->includes.begin(); _iter67 != this->includes.end(); ++_iter67)
    {
      xfer += (*_iter67).write(oprot);
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("structs", ::apache::thrift::protocol::T_MAP, 6);
  {
    xfer += oprot->writeMapBegin(::apache::thrift::protocol::T_STRING, ::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->structs.size()));
    std::map<std::string,  ::types::struct_definition::StructDefinition> ::const_iterator _iter68;
    for (_iter68 = this->structs.begin(); _iter68 != this->structs.end(); ++_iter68)
    {
      xfer += oprot->writeString(_iter68->first);
      xfer += _iter68->second.write(oprot);
    }
    xfer += oprot->writeMapEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("services", ::apache::thrift::protocol::T_MAP, 7);
  {
    xfer += oprot->writeMapBegin(::apache::thrift::protocol::T_STRING, ::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->services.size()));
    std::map<std::string,  ::types::service_definition::ServiceDefinition> ::const_iterator _iter69;
    for (_iter69 = this->services.begin(); _iter69 != this->services.end(); ++_iter69)
    {
      xfer += oprot->writeString(_iter69->first);
      xfer += _iter69->second.write(oprot);
    }
    xfer += oprot->writeMapEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("constants", ::apache::thrift::protocol::T_MAP, 8);
  {
    xfer += oprot->writeMapBegin(::apache::thrift::protocol::T_STRING, ::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->constants.size()));
    std::map<std::string,  ::types::constant_definition::ConstantDefinition> ::const_iterator _iter70;
    for (_iter70 = this->constants.begin(); _iter70 != this->constants.end(); ++_iter70)
    {
      xfer += oprot->writeString(_iter70->first);
      xfer += _iter70->second.write(oprot);
    }
    xfer += oprot->writeMapEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("typedefs", ::apache::thrift::protocol::T_MAP, 9);
  {
    xfer += oprot->writeMapBegin(::apache::thrift::protocol::T_STRING, ::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->typedefs.size()));
    std::map<std::string,  ::types::type_definition::TypeDefinition> ::const_iterator _iter71;
    for (_iter71 = this->typedefs.begin(); _iter71 != this->typedefs.end(); ++_iter71)
    {
      xfer += oprot->writeString(_iter71->first);
      xfer += _iter71->second.write(oprot);
    }
    xfer += oprot->writeMapEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("enums", ::apache::thrift::protocol::T_MAP, 10);
  {
    xfer += oprot->writeMapBegin(::apache::thrift::protocol::T_STRING, ::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->enums.size()));
    std::map<std::string,  ::types::enum_definition::EnumDefinition> ::const_iterator _iter72;
    for (_iter72 = this->enums.begin(); _iter72 != this->enums.end(); ++_iter72)
    {
      xfer += oprot->writeString(_iter72->first);
      xfer += _iter72->second.write(oprot);
    }
    xfer += oprot->writeMapEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("stdlib", ::apache::thrift::protocol::T_BOOL, 11);
  xfer += oprot->writeBool(this->stdlib);
  xfer += oprot->writeFieldEnd();

  if (this->__isset.namespace_annotations) {
    xfer += oprot->writeFieldBegin("namespace_annotations", ::apache::thrift::protocol::T_MAP, 12);
    {
      xfer += oprot->writeMapBegin(::apache::thrift::protocol::T_STRING, ::apache::thrift::protocol::T_MAP, static_cast<uint32_t>(this->namespace_annotations.size()));
      std::map<std::string, std::map<std::string, std::string> > ::const_iterator _iter73;
      for (_iter73 = this->namespace_annotations.begin(); _iter73 != this->namespace_annotations.end(); ++_iter73)
      {
        xfer += oprot->writeString(_iter73->first);
        {
          xfer += oprot->writeMapBegin(::apache::thrift::protocol::T_STRING, ::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(_iter73->second.size()));
          std::map<std::string, std::string> ::const_iterator _iter74;
          for (_iter74 = _iter73->second.begin(); _iter74 != _iter73->second.end(); ++_iter74)
          {
            xfer += oprot->writeString(_iter74->first);
            xfer += oprot->writeString(_iter74->second);
          }
          xfer += oprot->writeMapEnd();
        }
      }
      xfer += oprot->writeMapEnd();
    }
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.cpp_includes) {
    xfer += oprot->writeFieldBegin("cpp_includes", ::apache::thrift::protocol::T_LIST, 13);
    {
      xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->cpp_includes.size()));
      std::vector<std::string> ::const_iterator _iter75;
      for (_iter75 = this->cpp_includes.begin(); _iter75 != this->cpp_includes.end(); ++_iter75)
      {
        xfer += oprot->writeString((*_iter75));
      }
      xfer += oprot->writeListEnd();
    }
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(ProgramDefinition &a, ProgramDefinition &b) {
  using ::std::swap;
  swap(a.name, b.name);
  swap(a.path, b.path);
  swap(a.doc, b.doc);
  swap(a.namespaces, b.namespaces);
  swap(a.includes, b.includes);
  swap(a.structs, b.structs);
  swap(a.services, b.services);
  swap(a.constants, b.constants);
  swap(a.typedefs, b.typedefs);
  swap(a.enums, b.enums);
  swap(a.stdlib, b.stdlib);
  swap(a.namespace_annotations, b.namespace_annotations);
  swap(a.cpp_includes, b.cpp_includes);
  swap(a.__isset, b.__isset);
}

ProgramDefinition::ProgramDefinition(const ProgramDefinition& other76) {
  name = other76.name;
  path = other76.path;
  doc = other76.doc;
  namespaces = other76.namespaces;
  includes = other76.includes;
  structs = other76.structs;
  services = other76.services;
  constants = other76.constants;
  typedefs = other76.typedefs;
  enums = other76.enums;
  stdlib = other76.stdlib;
  namespace_annotations = other76.namespace_annotations;
  cpp_includes = other76.cpp_includes;
  __isset = other76.__isset;
}
ProgramDefinition& ProgramDefinition::operator=(const ProgramDefinition& other77) {
  name = other77.name;
  path = other77.path;
  doc = other77.doc;
  namespaces = other77.namespaces;
  includes = other77.includes;
  structs = other77.structs;
  services = other77.services;
  constants = other77.constants;
  typedefs = other77.typedefs;
  enums = other77.enums;
  stdlib = other77.stdlib;
  namespace_annotations = other77.namespace_annotations;
  cpp_includes = other77.cpp_includes;
  __isset = other77.__isset;
  return *this;
}
void ProgramDefinition::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ProgramDefinition(";
  out << "name=" << to_string(name);
  out << ", " << "path=" << to_string(path);
  out << ", " << "doc="; (__isset.doc ? (out << to_string(doc)) : (out << "<null>"));
  out << ", " << "namespaces=" << to_string(namespaces);
  out << ", " << "includes=" << to_string(includes);
  out << ", " << "structs=" << to_string(structs);
  out << ", " << "services=" << to_string(services);
  out << ", " << "constants=" << to_string(constants);
  out << ", " << "typedefs=" << to_string(typedefs);
  out << ", " << "enums=" << to_string(enums);
  out << ", " << "stdlib=" << to_string(stdlib);
  out << ", " << "namespace_annotations="; (__isset.namespace_annotations ? (out << to_string(namespace_annotations)) : (out << "<null>"));
  out << ", " << "cpp_includes="; (__isset.cpp_includes ? (out << to_string(cpp_includes)) : (out << "<null>"));
  out << ")";
}

}} // namespace
