/**
 * Autogenerated by Thrift Compiler (v2.6.8-upfluence)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef program_definition_TYPES_H
#define program_definition_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <functional>
#include <memory>
#include "enum_definition_types.h"
#include "type_definition_types.h"
#include "struct_definition_types.h"
#include "service_definition_types.h"
#include "value_definition_types.h"


namespace types { namespace program_definition {

class ProgramDefinition;

typedef struct _ProgramDefinition__isset {
  _ProgramDefinition__isset() : doc(false) {}
  bool doc :1;
} _ProgramDefinition__isset;

class ProgramDefinition : public virtual ::apache::thrift::TBase {
 public:

  ProgramDefinition(const ProgramDefinition&);
  ProgramDefinition& operator=(const ProgramDefinition&);
  ProgramDefinition() : name(), path(), doc() {
  }

  virtual ~ProgramDefinition() noexcept;
  std::string name;
  std::string path;
  std::string doc;
  std::map<std::string, std::string>  namespaces;
  std::vector<ProgramDefinition>  includes;
  std::map<std::string,  ::types::struct_definition::StructDefinition>  structs;
  std::map<std::string,  ::types::service_definition::ServiceDefinition>  services;
  std::map<std::string,  ::types::value::ValueDefinition>  constants;
  std::map<std::string,  ::types::type_definition::TypeDefinition>  typedefs;
  std::map<std::string,  ::types::enum_definition::EnumDefinition>  enums;

  _ProgramDefinition__isset __isset;

  void __set_name(const std::string& val);

  void __set_path(const std::string& val);

  void __set_doc(const std::string& val);

  void __set_namespaces(const std::map<std::string, std::string> & val);

  void __set_includes(const std::vector<ProgramDefinition> & val);

  void __set_structs(const std::map<std::string,  ::types::struct_definition::StructDefinition> & val);

  void __set_services(const std::map<std::string,  ::types::service_definition::ServiceDefinition> & val);

  void __set_constants(const std::map<std::string,  ::types::value::ValueDefinition> & val);

  void __set_typedefs(const std::map<std::string,  ::types::type_definition::TypeDefinition> & val);

  void __set_enums(const std::map<std::string,  ::types::enum_definition::EnumDefinition> & val);

  bool operator == (const ProgramDefinition & rhs) const
  {
    if (!(name == rhs.name))
      return false;
    if (!(path == rhs.path))
      return false;
    if (__isset.doc != rhs.__isset.doc)
      return false;
    else if (__isset.doc && !(doc == rhs.doc))
      return false;
    if (!(namespaces == rhs.namespaces))
      return false;
    if (!(includes == rhs.includes))
      return false;
    if (!(structs == rhs.structs))
      return false;
    if (!(services == rhs.services))
      return false;
    if (!(constants == rhs.constants))
      return false;
    if (!(typedefs == rhs.typedefs))
      return false;
    if (!(enums == rhs.enums))
      return false;
    return true;
  }
  bool operator != (const ProgramDefinition &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ProgramDefinition & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(ProgramDefinition &a, ProgramDefinition &b);

std::ostream& operator<<(std::ostream& out, const ProgramDefinition& obj);

}} // namespace

#endif
