/**
 * Autogenerated by Thrift Compiler (v2.7.0-upfluence)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef program_definition_CONSTANTS_H
#define program_definition_CONSTANTS_H

#include "program_definition_types.h"

namespace types { namespace program_definition {

class program_definitionConstants {
 public:
  program_definitionConstants();

};

extern const program_definitionConstants g_program_definition_constants;

}} // namespace

#endif
