/**
 * Autogenerated by Thrift Compiler (v2.7.0-upfluence)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "program_definition_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace types { namespace program_definition {


ProgramDefinition::~ProgramDefinition() noexcept {
}


void ProgramDefinition::__set_name(const std::string& val) {
  this->name = val;
}

void ProgramDefinition::__set_path(const std::string& val) {
  this->path = val;
}

void ProgramDefinition::__set_doc(const std::string& val) {
  this->doc = val;
__isset.doc = true;
}

void ProgramDefinition::__set_namespaces(const std::map<std::string, std::string> & val) {
  this->namespaces = val;
}

void ProgramDefinition::__set_includes(const std::vector<ProgramDefinition> & val) {
  this->includes = val;
}

void ProgramDefinition::__set_structs(const std::map<std::string,  ::types::struct_definition::StructDefinition> & val) {
  this->structs = val;
}

void ProgramDefinition::__set_services(const std::map<std::string,  ::types::service_definition::ServiceDefinition> & val) {
  this->services = val;
}

void ProgramDefinition::__set_constants(const std::map<std::string,  ::types::value_definition::ValueDefinition> & val) {
  this->constants = val;
}

void ProgramDefinition::__set_typedefs(const std::map<std::string,  ::types::type_definition::TypeDefinition> & val) {
  this->typedefs = val;
}

void ProgramDefinition::__set_enums(const std::map<std::string,  ::types::enum_definition::EnumDefinition> & val) {
  this->enums = val;
}
std::ostream& operator<<(std::ostream& out, const ProgramDefinition& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t ProgramDefinition::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_name = false;
  bool isset_path = false;
  bool isset_namespaces = false;
  bool isset_includes = false;
  bool isset_structs = false;
  bool isset_services = false;
  bool isset_constants = false;
  bool isset_typedefs = false;
  bool isset_enums = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->name);
          isset_name = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->path);
          isset_path = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->doc);
          this->__isset.doc = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_MAP) {
          {
            this->namespaces.clear();
            uint32_t _size0;
            ::apache::thrift::protocol::TType _ktype1;
            ::apache::thrift::protocol::TType _vtype2;
            xfer += iprot->readMapBegin(_ktype1, _vtype2, _size0);
            uint32_t _i4;
            for (_i4 = 0; _i4 < _size0; ++_i4)
            {
              std::string _key5;
              xfer += iprot->readString(_key5);
              std::string& _val6 = this->namespaces[_key5];
              xfer += iprot->readString(_val6);
            }
            xfer += iprot->readMapEnd();
          }
          isset_namespaces = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->includes.clear();
            uint32_t _size7;
            ::apache::thrift::protocol::TType _etype10;
            xfer += iprot->readListBegin(_etype10, _size7);
            this->includes.resize(_size7);
            uint32_t _i11;
            for (_i11 = 0; _i11 < _size7; ++_i11)
            {
              xfer += this->includes[_i11].read(iprot);
            }
            xfer += iprot->readListEnd();
          }
          isset_includes = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 6:
        if (ftype == ::apache::thrift::protocol::T_MAP) {
          {
            this->structs.clear();
            uint32_t _size12;
            ::apache::thrift::protocol::TType _ktype13;
            ::apache::thrift::protocol::TType _vtype14;
            xfer += iprot->readMapBegin(_ktype13, _vtype14, _size12);
            uint32_t _i16;
            for (_i16 = 0; _i16 < _size12; ++_i16)
            {
              std::string _key17;
              xfer += iprot->readString(_key17);
               ::types::struct_definition::StructDefinition& _val18 = this->structs[_key17];
              xfer += _val18.read(iprot);
            }
            xfer += iprot->readMapEnd();
          }
          isset_structs = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 7:
        if (ftype == ::apache::thrift::protocol::T_MAP) {
          {
            this->services.clear();
            uint32_t _size19;
            ::apache::thrift::protocol::TType _ktype20;
            ::apache::thrift::protocol::TType _vtype21;
            xfer += iprot->readMapBegin(_ktype20, _vtype21, _size19);
            uint32_t _i23;
            for (_i23 = 0; _i23 < _size19; ++_i23)
            {
              std::string _key24;
              xfer += iprot->readString(_key24);
               ::types::service_definition::ServiceDefinition& _val25 = this->services[_key24];
              xfer += _val25.read(iprot);
            }
            xfer += iprot->readMapEnd();
          }
          isset_services = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 8:
        if (ftype == ::apache::thrift::protocol::T_MAP) {
          {
            this->constants.clear();
            uint32_t _size26;
            ::apache::thrift::protocol::TType _ktype27;
            ::apache::thrift::protocol::TType _vtype28;
            xfer += iprot->readMapBegin(_ktype27, _vtype28, _size26);
            uint32_t _i30;
            for (_i30 = 0; _i30 < _size26; ++_i30)
            {
              std::string _key31;
              xfer += iprot->readString(_key31);
               ::types::value_definition::ValueDefinition& _val32 = this->constants[_key31];
              xfer += _val32.read(iprot);
            }
            xfer += iprot->readMapEnd();
          }
          isset_constants = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 9:
        if (ftype == ::apache::thrift::protocol::T_MAP) {
          {
            this->typedefs.clear();
            uint32_t _size33;
            ::apache::thrift::protocol::TType _ktype34;
            ::apache::thrift::protocol::TType _vtype35;
            xfer += iprot->readMapBegin(_ktype34, _vtype35, _size33);
            uint32_t _i37;
            for (_i37 = 0; _i37 < _size33; ++_i37)
            {
              std::string _key38;
              xfer += iprot->readString(_key38);
               ::types::type_definition::TypeDefinition& _val39 = this->typedefs[_key38];
              xfer += _val39.read(iprot);
            }
            xfer += iprot->readMapEnd();
          }
          isset_typedefs = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 10:
        if (ftype == ::apache::thrift::protocol::T_MAP) {
          {
            this->enums.clear();
            uint32_t _size40;
            ::apache::thrift::protocol::TType _ktype41;
            ::apache::thrift::protocol::TType _vtype42;
            xfer += iprot->readMapBegin(_ktype41, _vtype42, _size40);
            uint32_t _i44;
            for (_i44 = 0; _i44 < _size40; ++_i44)
            {
              std::string _key45;
              xfer += iprot->readString(_key45);
               ::types::enum_definition::EnumDefinition& _val46 = this->enums[_key45];
              xfer += _val46.read(iprot);
            }
            xfer += iprot->readMapEnd();
          }
          isset_enums = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_name)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_path)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_namespaces)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_includes)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_structs)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_services)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_constants)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_typedefs)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_enums)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t ProgramDefinition::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("ProgramDefinition");

  xfer += oprot->writeFieldBegin("name", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->name);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("path", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->path);
  xfer += oprot->writeFieldEnd();

  if (this->__isset.doc) {
    xfer += oprot->writeFieldBegin("doc", ::apache::thrift::protocol::T_STRING, 3);
    xfer += oprot->writeString(this->doc);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldBegin("namespaces", ::apache::thrift::protocol::T_MAP, 4);
  {
    xfer += oprot->writeMapBegin(::apache::thrift::protocol::T_STRING, ::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->namespaces.size()));
    std::map<std::string, std::string> ::const_iterator _iter47;
    for (_iter47 = this->namespaces.begin(); _iter47 != this->namespaces.end(); ++_iter47)
    {
      xfer += oprot->writeString(_iter47->first);
      xfer += oprot->writeString(_iter47->second);
    }
    xfer += oprot->writeMapEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("includes", ::apache::thrift::protocol::T_LIST, 5);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->includes.size()));
    std::vector<ProgramDefinition> ::const_iterator _iter48;
    for (_iter48 = this->includes.begin(); _iter48 != this->includes.end(); ++_iter48)
    {
      xfer += (*_iter48).write(oprot);
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("structs", ::apache::thrift::protocol::T_MAP, 6);
  {
    xfer += oprot->writeMapBegin(::apache::thrift::protocol::T_STRING, ::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->structs.size()));
    std::map<std::string,  ::types::struct_definition::StructDefinition> ::const_iterator _iter49;
    for (_iter49 = this->structs.begin(); _iter49 != this->structs.end(); ++_iter49)
    {
      xfer += oprot->writeString(_iter49->first);
      xfer += _iter49->second.write(oprot);
    }
    xfer += oprot->writeMapEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("services", ::apache::thrift::protocol::T_MAP, 7);
  {
    xfer += oprot->writeMapBegin(::apache::thrift::protocol::T_STRING, ::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->services.size()));
    std::map<std::string,  ::types::service_definition::ServiceDefinition> ::const_iterator _iter50;
    for (_iter50 = this->services.begin(); _iter50 != this->services.end(); ++_iter50)
    {
      xfer += oprot->writeString(_iter50->first);
      xfer += _iter50->second.write(oprot);
    }
    xfer += oprot->writeMapEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("constants", ::apache::thrift::protocol::T_MAP, 8);
  {
    xfer += oprot->writeMapBegin(::apache::thrift::protocol::T_STRING, ::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->constants.size()));
    std::map<std::string,  ::types::value_definition::ValueDefinition> ::const_iterator _iter51;
    for (_iter51 = this->constants.begin(); _iter51 != this->constants.end(); ++_iter51)
    {
      xfer += oprot->writeString(_iter51->first);
      xfer += _iter51->second.write(oprot);
    }
    xfer += oprot->writeMapEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("typedefs", ::apache::thrift::protocol::T_MAP, 9);
  {
    xfer += oprot->writeMapBegin(::apache::thrift::protocol::T_STRING, ::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->typedefs.size()));
    std::map<std::string,  ::types::type_definition::TypeDefinition> ::const_iterator _iter52;
    for (_iter52 = this->typedefs.begin(); _iter52 != this->typedefs.end(); ++_iter52)
    {
      xfer += oprot->writeString(_iter52->first);
      xfer += _iter52->second.write(oprot);
    }
    xfer += oprot->writeMapEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("enums", ::apache::thrift::protocol::T_MAP, 10);
  {
    xfer += oprot->writeMapBegin(::apache::thrift::protocol::T_STRING, ::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->enums.size()));
    std::map<std::string,  ::types::enum_definition::EnumDefinition> ::const_iterator _iter53;
    for (_iter53 = this->enums.begin(); _iter53 != this->enums.end(); ++_iter53)
    {
      xfer += oprot->writeString(_iter53->first);
      xfer += _iter53->second.write(oprot);
    }
    xfer += oprot->writeMapEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(ProgramDefinition &a, ProgramDefinition &b) {
  using ::std::swap;
  swap(a.name, b.name);
  swap(a.path, b.path);
  swap(a.doc, b.doc);
  swap(a.namespaces, b.namespaces);
  swap(a.includes, b.includes);
  swap(a.structs, b.structs);
  swap(a.services, b.services);
  swap(a.constants, b.constants);
  swap(a.typedefs, b.typedefs);
  swap(a.enums, b.enums);
  swap(a.__isset, b.__isset);
}

ProgramDefinition::ProgramDefinition(const ProgramDefinition& other54) {
  name = other54.name;
  path = other54.path;
  doc = other54.doc;
  namespaces = other54.namespaces;
  includes = other54.includes;
  structs = other54.structs;
  services = other54.services;
  constants = other54.constants;
  typedefs = other54.typedefs;
  enums = other54.enums;
  __isset = other54.__isset;
}
ProgramDefinition& ProgramDefinition::operator=(const ProgramDefinition& other55) {
  name = other55.name;
  path = other55.path;
  doc = other55.doc;
  namespaces = other55.namespaces;
  includes = other55.includes;
  structs = other55.structs;
  services = other55.services;
  constants = other55.constants;
  typedefs = other55.typedefs;
  enums = other55.enums;
  __isset = other55.__isset;
  return *this;
}
void ProgramDefinition::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ProgramDefinition(";
  out << "name=" << to_string(name);
  out << ", " << "path=" << to_string(path);
  out << ", " << "doc="; (__isset.doc ? (out << to_string(doc)) : (out << "<null>"));
  out << ", " << "namespaces=" << to_string(namespaces);
  out << ", " << "includes=" << to_string(includes);
  out << ", " << "structs=" << to_string(structs);
  out << ", " << "services=" << to_string(services);
  out << ", " << "constants=" << to_string(constants);
  out << ", " << "typedefs=" << to_string(typedefs);
  out << ", " << "enums=" << to_string(enums);
  out << ")";
}

}} // namespace
