/**
 * Autogenerated by Thrift Compiler (2.7.0-upfluence)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef service_definition_CONSTANTS_H
#define service_definition_CONSTANTS_H

#include "service_definition_types.h"

namespace types { namespace service_definition {

class service_definitionConstants {
 public:
  service_definitionConstants();

};

extern const service_definitionConstants g_service_definition_constants;

}} // namespace

#endif
