/**
 * Autogenerated by Thrift Compiler (2.7.0-upfluence)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "service_definition_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace types { namespace service_definition {


FunctionDefinition::~FunctionDefinition() noexcept {
}


void FunctionDefinition::__set_annotation(const  ::types::annotation_definition::AnnotationDefinition& val) {
  this->annotation = val;
}

void FunctionDefinition::__set_arguments(const std::vector< ::types::struct_definition::FieldDefinition> & val) {
  this->arguments = val;
}

void FunctionDefinition::__set_return_type(const  ::types::type_definition::TypeDefinition& val) {
  this->return_type = val;
}

void FunctionDefinition::__set_exceptions(const std::vector< ::types::core::Reference> & val) {
  this->exceptions = val;
}

void FunctionDefinition::__set_oneway_(const bool val) {
  this->oneway_ = val;
}

void FunctionDefinition::__set_sink_type(const  ::types::type_definition::TypeDefinition& val) {
  this->sink_type = val;
__isset.sink_type = true;
}

void FunctionDefinition::__set_stream_type(const  ::types::type_definition::TypeDefinition& val) {
  this->stream_type = val;
__isset.stream_type = true;
}
std::ostream& operator<<(std::ostream& out, const FunctionDefinition& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t FunctionDefinition::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_annotation = false;
  bool isset_arguments = false;
  bool isset_return_type = false;
  bool isset_exceptions = false;
  bool isset_oneway_ = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->annotation.read(iprot);
          isset_annotation = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->arguments.clear();
            uint32_t _size0;
            ::apache::thrift::protocol::TType _etype3;
            xfer += iprot->readListBegin(_etype3, _size0);
            this->arguments.resize(_size0);
            uint32_t _i4;
            for (_i4 = 0; _i4 < _size0; ++_i4)
            {
              xfer += this->arguments[_i4].read(iprot);
            }
            xfer += iprot->readListEnd();
          }
          isset_arguments = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->return_type.read(iprot);
          isset_return_type = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->exceptions.clear();
            uint32_t _size5;
            ::apache::thrift::protocol::TType _etype8;
            xfer += iprot->readListBegin(_etype8, _size5);
            this->exceptions.resize(_size5);
            uint32_t _i9;
            for (_i9 = 0; _i9 < _size5; ++_i9)
            {
              xfer += this->exceptions[_i9].read(iprot);
            }
            xfer += iprot->readListEnd();
          }
          isset_exceptions = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 5:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->oneway_);
          isset_oneway_ = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 6:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->sink_type.read(iprot);
          this->__isset.sink_type = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 7:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->stream_type.read(iprot);
          this->__isset.stream_type = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_annotation)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_arguments)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_return_type)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_exceptions)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_oneway_)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t FunctionDefinition::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("FunctionDefinition");

  xfer += oprot->writeFieldBegin("annotation", ::apache::thrift::protocol::T_STRUCT, 1);
  xfer += this->annotation.write(oprot);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("arguments", ::apache::thrift::protocol::T_LIST, 2);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->arguments.size()));
    std::vector< ::types::struct_definition::FieldDefinition> ::const_iterator _iter10;
    for (_iter10 = this->arguments.begin(); _iter10 != this->arguments.end(); ++_iter10)
    {
      xfer += (*_iter10).write(oprot);
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("return_type", ::apache::thrift::protocol::T_STRUCT, 3);
  xfer += this->return_type.write(oprot);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("exceptions", ::apache::thrift::protocol::T_LIST, 4);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->exceptions.size()));
    std::vector< ::types::core::Reference> ::const_iterator _iter11;
    for (_iter11 = this->exceptions.begin(); _iter11 != this->exceptions.end(); ++_iter11)
    {
      xfer += (*_iter11).write(oprot);
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("oneway_", ::apache::thrift::protocol::T_BOOL, 5);
  xfer += oprot->writeBool(this->oneway_);
  xfer += oprot->writeFieldEnd();

  if (this->__isset.sink_type) {
    xfer += oprot->writeFieldBegin("sink_type", ::apache::thrift::protocol::T_STRUCT, 6);
    xfer += this->sink_type.write(oprot);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.stream_type) {
    xfer += oprot->writeFieldBegin("stream_type", ::apache::thrift::protocol::T_STRUCT, 7);
    xfer += this->stream_type.write(oprot);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(FunctionDefinition &a, FunctionDefinition &b) {
  using ::std::swap;
  swap(a.annotation, b.annotation);
  swap(a.arguments, b.arguments);
  swap(a.return_type, b.return_type);
  swap(a.exceptions, b.exceptions);
  swap(a.oneway_, b.oneway_);
  swap(a.sink_type, b.sink_type);
  swap(a.stream_type, b.stream_type);
  swap(a.__isset, b.__isset);
}

FunctionDefinition::FunctionDefinition(const FunctionDefinition& other12) {
  annotation = other12.annotation;
  arguments = other12.arguments;
  return_type = other12.return_type;
  exceptions = other12.exceptions;
  oneway_ = other12.oneway_;
  sink_type = other12.sink_type;
  stream_type = other12.stream_type;
  __isset = other12.__isset;
}
FunctionDefinition& FunctionDefinition::operator=(const FunctionDefinition& other13) {
  annotation = other13.annotation;
  arguments = other13.arguments;
  return_type = other13.return_type;
  exceptions = other13.exceptions;
  oneway_ = other13.oneway_;
  sink_type = other13.sink_type;
  stream_type = other13.stream_type;
  __isset = other13.__isset;
  return *this;
}
void FunctionDefinition::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "FunctionDefinition(";
  out << "annotation=" << to_string(annotation);
  out << ", " << "arguments=" << to_string(arguments);
  out << ", " << "return_type=" << to_string(return_type);
  out << ", " << "exceptions=" << to_string(exceptions);
  out << ", " << "oneway_=" << to_string(oneway_);
  out << ", " << "sink_type="; (__isset.sink_type ? (out << to_string(sink_type)) : (out << "<null>"));
  out << ", " << "stream_type="; (__isset.stream_type ? (out << to_string(stream_type)) : (out << "<null>"));
  out << ")";
}


ServiceDefinition::~ServiceDefinition() noexcept {
}


void ServiceDefinition::__set_annotation(const  ::types::annotation_definition::AnnotationDefinition& val) {
  this->annotation = val;
}

void ServiceDefinition::__set_extends_(const  ::types::core::Reference& val) {
  this->extends_ = val;
__isset.extends_ = true;
}

void ServiceDefinition::__set_functions(const std::vector<FunctionDefinition> & val) {
  this->functions = val;
}
std::ostream& operator<<(std::ostream& out, const ServiceDefinition& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t ServiceDefinition::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_annotation = false;
  bool isset_functions = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->annotation.read(iprot);
          isset_annotation = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->extends_.read(iprot);
          this->__isset.extends_ = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->functions.clear();
            uint32_t _size14;
            ::apache::thrift::protocol::TType _etype17;
            xfer += iprot->readListBegin(_etype17, _size14);
            this->functions.resize(_size14);
            uint32_t _i18;
            for (_i18 = 0; _i18 < _size14; ++_i18)
            {
              xfer += this->functions[_i18].read(iprot);
            }
            xfer += iprot->readListEnd();
          }
          isset_functions = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_annotation)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_functions)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t ServiceDefinition::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("ServiceDefinition");

  xfer += oprot->writeFieldBegin("annotation", ::apache::thrift::protocol::T_STRUCT, 1);
  xfer += this->annotation.write(oprot);
  xfer += oprot->writeFieldEnd();

  if (this->__isset.extends_) {
    xfer += oprot->writeFieldBegin("extends_", ::apache::thrift::protocol::T_STRUCT, 2);
    xfer += this->extends_.write(oprot);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldBegin("functions", ::apache::thrift::protocol::T_LIST, 3);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->functions.size()));
    std::vector<FunctionDefinition> ::const_iterator _iter19;
    for (_iter19 = this->functions.begin(); _iter19 != this->functions.end(); ++_iter19)
    {
      xfer += (*_iter19).write(oprot);
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(ServiceDefinition &a, ServiceDefinition &b) {
  using ::std::swap;
  swap(a.annotation, b.annotation);
  swap(a.extends_, b.extends_);
  swap(a.functions, b.functions);
  swap(a.__isset, b.__isset);
}

ServiceDefinition::ServiceDefinition(const ServiceDefinition& other20) {
  annotation = other20.annotation;
  extends_ = other20.extends_;
  functions = other20.functions;
  __isset = other20.__isset;
}
ServiceDefinition& ServiceDefinition::operator=(const ServiceDefinition& other21) {
  annotation = other21.annotation;
  extends_ = other21.extends_;
  functions = other21.functions;
  __isset = other21.__isset;
  return *this;
}
void ServiceDefinition::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ServiceDefinition(";
  out << "annotation=" << to_string(annotation);
  out << ", " << "extends_="; (__isset.extends_ ? (out << to_string(extends_)) : (out << "<null>"));
  out << ", " << "functions=" << to_string(functions);
  out << ")";
}

}} // namespace
