/**
 * Autogenerated by Thrift Compiler (v2.6.8-upfluence)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "service_definition_constants.h"

namespace types { namespace service_definition {

const service_definitionConstants g_service_definition_constants;

service_definitionConstants::service_definitionConstants() {
}

}} // namespace

