/**
 * Autogenerated by Thrift Compiler (2.7.0-upfluence)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "struct_definition_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace types { namespace struct_definition {

int _kRequirednessValues[] = {
  Requiredness::Unknown,
  Requiredness::Optional,
  Requiredness::Required
};
const char* _kRequirednessNames[] = {
  "Unknown",
  "Optional",
  "Required"
};
const std::map<int, const char*> _Requiredness_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(3, _kRequirednessValues, _kRequirednessNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));

std::ostream& operator<<(std::ostream& out, const Requiredness::type& val) {
  std::map<int, const char*>::const_iterator it = _Requiredness_VALUES_TO_NAMES.find(val);
  if (it != _Requiredness_VALUES_TO_NAMES.end()) {
    out << it->second;
  } else {
    out << static_cast<int>(val);
  }
  return out;
}

std::string to_string(const Requiredness::type& val) {
  std::map<int, const char*>::const_iterator it = _Requiredness_VALUES_TO_NAMES.find(val);
  if (it != _Requiredness_VALUES_TO_NAMES.end()) {
    return std::string(it->second);
  } else {
    return std::to_string(static_cast<int>(val));
  }
}

int _kStructKindValues[] = {
  StructKind::Unknown,
  StructKind::Struct,
  StructKind::Exception,
  StructKind::Union
};
const char* _kStructKindNames[] = {
  "Unknown",
  "Struct",
  "Exception",
  "Union"
};
const std::map<int, const char*> _StructKind_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(4, _kStructKindValues, _kStructKindNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));

std::ostream& operator<<(std::ostream& out, const StructKind::type& val) {
  std::map<int, const char*>::const_iterator it = _StructKind_VALUES_TO_NAMES.find(val);
  if (it != _StructKind_VALUES_TO_NAMES.end()) {
    out << it->second;
  } else {
    out << static_cast<int>(val);
  }
  return out;
}

std::string to_string(const StructKind::type& val) {
  std::map<int, const char*>::const_iterator it = _StructKind_VALUES_TO_NAMES.find(val);
  if (it != _StructKind_VALUES_TO_NAMES.end()) {
    return std::string(it->second);
  } else {
    return std::to_string(static_cast<int>(val));
  }
}


FieldDefinition::~FieldDefinition() noexcept {
}


void FieldDefinition::__set_annotation(const  ::types::annotation_definition::AnnotationDefinition& val) {
  this->annotation = val;
}

void FieldDefinition::__set_id(const int32_t val) {
  this->id = val;
}

void FieldDefinition::__set_type(::std::shared_ptr< ::types::type_definition::TypeDefinition> val) {
  this->type = val;
}

void FieldDefinition::__set_requiredness(const Requiredness::type val) {
  this->requiredness = val;
}
std::ostream& operator<<(std::ostream& out, const FieldDefinition& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t FieldDefinition::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_annotation = false;
  bool isset_id = false;
  bool isset_type = false;
  bool isset_requiredness = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->annotation.read(iprot);
          isset_annotation = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->id);
          isset_id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          if (!this->type) { 
            this->type = ::std::shared_ptr< ::types::type_definition::TypeDefinition>(new  ::types::type_definition::TypeDefinition);
          }
          xfer += this->type->read(iprot);
          bool wasSet = false;
          if (this->type->__isset.scalar_type) { wasSet = true; }
          if (this->type->__isset.list_type) { wasSet = true; }
          if (this->type->__isset.map_type) { wasSet = true; }
          if (this->type->__isset.set_type) { wasSet = true; }
          if (this->type->__isset.reference_type) { wasSet = true; }
          if (!wasSet) { this->type.reset(); }
          isset_type = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          int32_t ecast0;
          xfer += iprot->readI32(ecast0);
          this->requiredness = (Requiredness::type)ecast0;
          isset_requiredness = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_annotation)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_id)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_type)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_requiredness)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t FieldDefinition::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("FieldDefinition");

  xfer += oprot->writeFieldBegin("annotation", ::apache::thrift::protocol::T_STRUCT, 1);
  xfer += this->annotation.write(oprot);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("id", ::apache::thrift::protocol::T_I32, 2);
  xfer += oprot->writeI32(this->id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("type", ::apache::thrift::protocol::T_STRUCT, 3);
  if (this->type) {
    xfer += this->type->write(oprot); 
  } else {oprot->writeStructBegin("TypeDefinition"); 
    oprot->writeStructEnd();
    oprot->writeFieldStop();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("requiredness", ::apache::thrift::protocol::T_I32, 4);
  xfer += oprot->writeI32((int32_t)this->requiredness);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(FieldDefinition &a, FieldDefinition &b) {
  using ::std::swap;
  swap(a.annotation, b.annotation);
  swap(a.id, b.id);
  swap(a.type, b.type);
  swap(a.requiredness, b.requiredness);
}

FieldDefinition::FieldDefinition(const FieldDefinition& other1) {
  annotation = other1.annotation;
  id = other1.id;
  type = other1.type;
  requiredness = other1.requiredness;
}
FieldDefinition& FieldDefinition::operator=(const FieldDefinition& other2) {
  annotation = other2.annotation;
  id = other2.id;
  type = other2.type;
  requiredness = other2.requiredness;
  return *this;
}
void FieldDefinition::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "FieldDefinition(";
  out << "annotation=" << to_string(annotation);
  out << ", " << "id=" << to_string(id);
  out << ", " << "type=" << to_string(type);
  out << ", " << "requiredness=" << to_string(requiredness);
  out << ")";
}


StructDefinition::~StructDefinition() noexcept {
}


void StructDefinition::__set_annotation(const  ::types::annotation_definition::AnnotationDefinition& val) {
  this->annotation = val;
}

void StructDefinition::__set_kind(const StructKind::type val) {
  this->kind = val;
}

void StructDefinition::__set_fields(const std::vector<FieldDefinition> & val) {
  this->fields = val;
}
std::ostream& operator<<(std::ostream& out, const StructDefinition& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t StructDefinition::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_annotation = false;
  bool isset_kind = false;
  bool isset_fields = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->annotation.read(iprot);
          isset_annotation = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          int32_t ecast3;
          xfer += iprot->readI32(ecast3);
          this->kind = (StructKind::type)ecast3;
          isset_kind = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_LIST) {
          {
            this->fields.clear();
            uint32_t _size4;
            ::apache::thrift::protocol::TType _etype7;
            xfer += iprot->readListBegin(_etype7, _size4);
            this->fields.resize(_size4);
            uint32_t _i8;
            for (_i8 = 0; _i8 < _size4; ++_i8)
            {
              xfer += this->fields[_i8].read(iprot);
            }
            xfer += iprot->readListEnd();
          }
          isset_fields = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_annotation)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_kind)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_fields)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t StructDefinition::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("StructDefinition");

  xfer += oprot->writeFieldBegin("annotation", ::apache::thrift::protocol::T_STRUCT, 1);
  xfer += this->annotation.write(oprot);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("kind", ::apache::thrift::protocol::T_I32, 2);
  xfer += oprot->writeI32((int32_t)this->kind);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("fields", ::apache::thrift::protocol::T_LIST, 3);
  {
    xfer += oprot->writeListBegin(::apache::thrift::protocol::T_STRUCT, static_cast<uint32_t>(this->fields.size()));
    std::vector<FieldDefinition> ::const_iterator _iter9;
    for (_iter9 = this->fields.begin(); _iter9 != this->fields.end(); ++_iter9)
    {
      xfer += (*_iter9).write(oprot);
    }
    xfer += oprot->writeListEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(StructDefinition &a, StructDefinition &b) {
  using ::std::swap;
  swap(a.annotation, b.annotation);
  swap(a.kind, b.kind);
  swap(a.fields, b.fields);
}

StructDefinition::StructDefinition(const StructDefinition& other10) {
  annotation = other10.annotation;
  kind = other10.kind;
  fields = other10.fields;
}
StructDefinition& StructDefinition::operator=(const StructDefinition& other11) {
  annotation = other11.annotation;
  kind = other11.kind;
  fields = other11.fields;
  return *this;
}
void StructDefinition::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "StructDefinition(";
  out << "annotation=" << to_string(annotation);
  out << ", " << "kind=" << to_string(kind);
  out << ", " << "fields=" << to_string(fields);
  out << ")";
}

}} // namespace
