/**
 * Autogenerated by Thrift Compiler (v2.6.8-upfluence)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "struct_definition_constants.h"

namespace types { namespace struct_definition {

const struct_definitionConstants g_struct_definition_constants;

struct_definitionConstants::struct_definitionConstants() {
}

}} // namespace

