/**
 * Autogenerated by Thrift Compiler (v2.7.0-upfluence)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "type_definition_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace types { namespace type_definition {

int _kScalarTypeValues[] = {
  ScalarType::Unknown,
  ScalarType::String,
  ScalarType::Binary,
  ScalarType::Bool,
  ScalarType::I16,
  ScalarType::I32,
  ScalarType::I64,
  ScalarType::Double
};
const char* _kScalarTypeNames[] = {
  "Unknown",
  "String",
  "Binary",
  "Bool",
  "I16",
  "I32",
  "I64",
  "Double"
};
const std::map<int, const char*> _ScalarType_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(8, _kScalarTypeValues, _kScalarTypeNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));

std::ostream& operator<<(std::ostream& out, const ScalarType::type& val) {
  std::map<int, const char*>::const_iterator it = _ScalarType_VALUES_TO_NAMES.find(val);
  if (it != _ScalarType_VALUES_TO_NAMES.end()) {
    out << it->second;
  } else {
    out << static_cast<int>(val);
  }
  return out;
}

std::string to_string(const ScalarType::type& val) {
  std::map<int, const char*>::const_iterator it = _ScalarType_VALUES_TO_NAMES.find(val);
  if (it != _ScalarType_VALUES_TO_NAMES.end()) {
    return std::string(it->second);
  } else {
    return std::to_string(static_cast<int>(val));
  }
}


ListType::~ListType() noexcept {
}


void ListType::__set_element_type(::std::shared_ptr<Type> val) {
  this->element_type = val;
}
std::ostream& operator<<(std::ostream& out, const ListType& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t ListType::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_element_type = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          if (!this->element_type) { 
            this->element_type = ::std::shared_ptr<Type>(new Type);
          }
          xfer += this->element_type->read(iprot);
          bool wasSet = false;
          if (this->element_type->__isset.scalar_type) { wasSet = true; }
          if (this->element_type->__isset.list_type) { wasSet = true; }
          if (this->element_type->__isset.map_type) { wasSet = true; }
          if (this->element_type->__isset.set_type) { wasSet = true; }
          if (this->element_type->__isset.reference_type) { wasSet = true; }
          if (!wasSet) { this->element_type.reset(); }
          isset_element_type = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_element_type)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t ListType::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("ListType");

  xfer += oprot->writeFieldBegin("element_type", ::apache::thrift::protocol::T_STRUCT, 1);
  if (this->element_type) {
    xfer += this->element_type->write(oprot); 
  } else {oprot->writeStructBegin("Type"); 
    oprot->writeStructEnd();
    oprot->writeFieldStop();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(ListType &a, ListType &b) {
  using ::std::swap;
  swap(a.element_type, b.element_type);
}

ListType::ListType(const ListType& other0) {
  element_type = other0.element_type;
}
ListType& ListType::operator=(const ListType& other1) {
  element_type = other1.element_type;
  return *this;
}
void ListType::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "ListType(";
  out << "element_type=" << to_string(element_type);
  out << ")";
}


MapType::~MapType() noexcept {
}


void MapType::__set_key_type(::std::shared_ptr<Type> val) {
  this->key_type = val;
}

void MapType::__set_value_type(::std::shared_ptr<Type> val) {
  this->value_type = val;
}
std::ostream& operator<<(std::ostream& out, const MapType& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t MapType::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_key_type = false;
  bool isset_value_type = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          if (!this->key_type) { 
            this->key_type = ::std::shared_ptr<Type>(new Type);
          }
          xfer += this->key_type->read(iprot);
          bool wasSet = false;
          if (this->key_type->__isset.scalar_type) { wasSet = true; }
          if (this->key_type->__isset.list_type) { wasSet = true; }
          if (this->key_type->__isset.map_type) { wasSet = true; }
          if (this->key_type->__isset.set_type) { wasSet = true; }
          if (this->key_type->__isset.reference_type) { wasSet = true; }
          if (!wasSet) { this->key_type.reset(); }
          isset_key_type = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          if (!this->value_type) { 
            this->value_type = ::std::shared_ptr<Type>(new Type);
          }
          xfer += this->value_type->read(iprot);
          bool wasSet = false;
          if (this->value_type->__isset.scalar_type) { wasSet = true; }
          if (this->value_type->__isset.list_type) { wasSet = true; }
          if (this->value_type->__isset.map_type) { wasSet = true; }
          if (this->value_type->__isset.set_type) { wasSet = true; }
          if (this->value_type->__isset.reference_type) { wasSet = true; }
          if (!wasSet) { this->value_type.reset(); }
          isset_value_type = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_key_type)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_value_type)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t MapType::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("MapType");

  xfer += oprot->writeFieldBegin("key_type", ::apache::thrift::protocol::T_STRUCT, 1);
  if (this->key_type) {
    xfer += this->key_type->write(oprot); 
  } else {oprot->writeStructBegin("Type"); 
    oprot->writeStructEnd();
    oprot->writeFieldStop();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("value_type", ::apache::thrift::protocol::T_STRUCT, 2);
  if (this->value_type) {
    xfer += this->value_type->write(oprot); 
  } else {oprot->writeStructBegin("Type"); 
    oprot->writeStructEnd();
    oprot->writeFieldStop();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(MapType &a, MapType &b) {
  using ::std::swap;
  swap(a.key_type, b.key_type);
  swap(a.value_type, b.value_type);
}

MapType::MapType(const MapType& other2) {
  key_type = other2.key_type;
  value_type = other2.value_type;
}
MapType& MapType::operator=(const MapType& other3) {
  key_type = other3.key_type;
  value_type = other3.value_type;
  return *this;
}
void MapType::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "MapType(";
  out << "key_type=" << to_string(key_type);
  out << ", " << "value_type=" << to_string(value_type);
  out << ")";
}


SetType::~SetType() noexcept {
}


void SetType::__set_element_type(::std::shared_ptr<Type> val) {
  this->element_type = val;
}
std::ostream& operator<<(std::ostream& out, const SetType& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t SetType::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_element_type = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          if (!this->element_type) { 
            this->element_type = ::std::shared_ptr<Type>(new Type);
          }
          xfer += this->element_type->read(iprot);
          bool wasSet = false;
          if (this->element_type->__isset.scalar_type) { wasSet = true; }
          if (this->element_type->__isset.list_type) { wasSet = true; }
          if (this->element_type->__isset.map_type) { wasSet = true; }
          if (this->element_type->__isset.set_type) { wasSet = true; }
          if (this->element_type->__isset.reference_type) { wasSet = true; }
          if (!wasSet) { this->element_type.reset(); }
          isset_element_type = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_element_type)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t SetType::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("SetType");

  xfer += oprot->writeFieldBegin("element_type", ::apache::thrift::protocol::T_STRUCT, 1);
  if (this->element_type) {
    xfer += this->element_type->write(oprot); 
  } else {oprot->writeStructBegin("Type"); 
    oprot->writeStructEnd();
    oprot->writeFieldStop();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(SetType &a, SetType &b) {
  using ::std::swap;
  swap(a.element_type, b.element_type);
}

SetType::SetType(const SetType& other4) {
  element_type = other4.element_type;
}
SetType& SetType::operator=(const SetType& other5) {
  element_type = other5.element_type;
  return *this;
}
void SetType::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "SetType(";
  out << "element_type=" << to_string(element_type);
  out << ")";
}


Type::~Type() noexcept {
}


void Type::__set_scalar_type(const ScalarType::type val) {
  this->scalar_type = val;
__isset.scalar_type = true;
}

void Type::__set_list_type(const ListType& val) {
  this->list_type = val;
__isset.list_type = true;
}

void Type::__set_map_type(const MapType& val) {
  this->map_type = val;
__isset.map_type = true;
}

void Type::__set_set_type(const SetType& val) {
  this->set_type = val;
__isset.set_type = true;
}

void Type::__set_reference_type(const  ::types::core::Reference& val) {
  this->reference_type = val;
__isset.reference_type = true;
}
std::ostream& operator<<(std::ostream& out, const Type& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t Type::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          int32_t ecast6;
          xfer += iprot->readI32(ecast6);
          this->scalar_type = (ScalarType::type)ecast6;
          this->__isset.scalar_type = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->list_type.read(iprot);
          this->__isset.list_type = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->map_type.read(iprot);
          this->__isset.map_type = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 4:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->set_type.read(iprot);
          this->__isset.set_type = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 8:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->reference_type.read(iprot);
          this->__isset.reference_type = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t Type::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("Type");

  if (this->__isset.scalar_type) {
    xfer += oprot->writeFieldBegin("scalar_type", ::apache::thrift::protocol::T_I32, 1);
    xfer += oprot->writeI32((int32_t)this->scalar_type);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.list_type) {
    xfer += oprot->writeFieldBegin("list_type", ::apache::thrift::protocol::T_STRUCT, 2);
    xfer += this->list_type.write(oprot);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.map_type) {
    xfer += oprot->writeFieldBegin("map_type", ::apache::thrift::protocol::T_STRUCT, 3);
    xfer += this->map_type.write(oprot);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.set_type) {
    xfer += oprot->writeFieldBegin("set_type", ::apache::thrift::protocol::T_STRUCT, 4);
    xfer += this->set_type.write(oprot);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.reference_type) {
    xfer += oprot->writeFieldBegin("reference_type", ::apache::thrift::protocol::T_STRUCT, 8);
    xfer += this->reference_type.write(oprot);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(Type &a, Type &b) {
  using ::std::swap;
  swap(a.scalar_type, b.scalar_type);
  swap(a.list_type, b.list_type);
  swap(a.map_type, b.map_type);
  swap(a.set_type, b.set_type);
  swap(a.reference_type, b.reference_type);
  swap(a.__isset, b.__isset);
}

Type::Type(const Type& other7) {
  scalar_type = other7.scalar_type;
  list_type = other7.list_type;
  map_type = other7.map_type;
  set_type = other7.set_type;
  reference_type = other7.reference_type;
  __isset = other7.__isset;
}
Type& Type::operator=(const Type& other8) {
  scalar_type = other8.scalar_type;
  list_type = other8.list_type;
  map_type = other8.map_type;
  set_type = other8.set_type;
  reference_type = other8.reference_type;
  __isset = other8.__isset;
  return *this;
}
void Type::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "Type(";
  out << "scalar_type="; (__isset.scalar_type ? (out << to_string(scalar_type)) : (out << "<null>"));
  out << ", " << "list_type="; (__isset.list_type ? (out << to_string(list_type)) : (out << "<null>"));
  out << ", " << "map_type="; (__isset.map_type ? (out << to_string(map_type)) : (out << "<null>"));
  out << ", " << "set_type="; (__isset.set_type ? (out << to_string(set_type)) : (out << "<null>"));
  out << ", " << "reference_type="; (__isset.reference_type ? (out << to_string(reference_type)) : (out << "<null>"));
  out << ")";
}

}} // namespace
