/**
 * Autogenerated by Thrift Compiler (2.7.0-upfluence)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef type_definition_TYPES_H
#define type_definition_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <functional>
#include <memory>
#include "core_types.h"
#include "annotation_definition_types.h"


namespace types { namespace type_definition {

struct ScalarType {
  enum type {
    Unknown = 0,
    String = 1,
    Binary = 2,
    Bool = 3,
    I16 = 4,
    I32 = 5,
    I64 = 6,
    Double = 7
  };
};

extern const std::map<int, const char*> _ScalarType_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const ScalarType::type& val);

std::string to_string(const ScalarType::type& val);

class ListTypeDefinition;

class MapTypeDefinition;

class SetTypeDefinition;

class TypeDefinition;


class ListTypeDefinition : public virtual ::apache::thrift::TBase {
 public:

  ListTypeDefinition(const ListTypeDefinition&);
  ListTypeDefinition& operator=(const ListTypeDefinition&);
  ListTypeDefinition() : element_type() {
  }

  virtual ~ListTypeDefinition() noexcept;
  ::std::shared_ptr<TypeDefinition> element_type;

  void __set_element_type(::std::shared_ptr<TypeDefinition> val);

  bool operator == (const ListTypeDefinition & rhs) const
  {
    if (!(element_type == rhs.element_type))
      return false;
    return true;
  }
  bool operator != (const ListTypeDefinition &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ListTypeDefinition & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(ListTypeDefinition &a, ListTypeDefinition &b);

std::ostream& operator<<(std::ostream& out, const ListTypeDefinition& obj);


class MapTypeDefinition : public virtual ::apache::thrift::TBase {
 public:

  MapTypeDefinition(const MapTypeDefinition&);
  MapTypeDefinition& operator=(const MapTypeDefinition&);
  MapTypeDefinition() : key_type(), value_type() {
  }

  virtual ~MapTypeDefinition() noexcept;
  ::std::shared_ptr<TypeDefinition> key_type;
  ::std::shared_ptr<TypeDefinition> value_type;

  void __set_key_type(::std::shared_ptr<TypeDefinition> val);

  void __set_value_type(::std::shared_ptr<TypeDefinition> val);

  bool operator == (const MapTypeDefinition & rhs) const
  {
    if (!(key_type == rhs.key_type))
      return false;
    if (!(value_type == rhs.value_type))
      return false;
    return true;
  }
  bool operator != (const MapTypeDefinition &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MapTypeDefinition & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(MapTypeDefinition &a, MapTypeDefinition &b);

std::ostream& operator<<(std::ostream& out, const MapTypeDefinition& obj);


class SetTypeDefinition : public virtual ::apache::thrift::TBase {
 public:

  SetTypeDefinition(const SetTypeDefinition&);
  SetTypeDefinition& operator=(const SetTypeDefinition&);
  SetTypeDefinition() : element_type() {
  }

  virtual ~SetTypeDefinition() noexcept;
  ::std::shared_ptr<TypeDefinition> element_type;

  void __set_element_type(::std::shared_ptr<TypeDefinition> val);

  bool operator == (const SetTypeDefinition & rhs) const
  {
    if (!(element_type == rhs.element_type))
      return false;
    return true;
  }
  bool operator != (const SetTypeDefinition &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SetTypeDefinition & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(SetTypeDefinition &a, SetTypeDefinition &b);

std::ostream& operator<<(std::ostream& out, const SetTypeDefinition& obj);

typedef struct _TypeDefinition__isset {
  _TypeDefinition__isset() : scalar_type(false), list_type(false), map_type(false), set_type(false), reference_type(false) {}
  bool scalar_type :1;
  bool list_type :1;
  bool map_type :1;
  bool set_type :1;
  bool reference_type :1;
} _TypeDefinition__isset;

class TypeDefinition : public virtual ::apache::thrift::TBase {
 public:

  TypeDefinition(const TypeDefinition&);
  TypeDefinition& operator=(const TypeDefinition&);
  TypeDefinition() : scalar_type((ScalarType::type)0) {
  }

  virtual ~TypeDefinition() noexcept;
  ScalarType::type scalar_type;
  ListTypeDefinition list_type;
  MapTypeDefinition map_type;
  SetTypeDefinition set_type;
   ::types::core::Reference reference_type;

  _TypeDefinition__isset __isset;

  void __set_scalar_type(const ScalarType::type val);

  void __set_list_type(const ListTypeDefinition& val);

  void __set_map_type(const MapTypeDefinition& val);

  void __set_set_type(const SetTypeDefinition& val);

  void __set_reference_type(const  ::types::core::Reference& val);

  bool operator == (const TypeDefinition & rhs) const
  {
    if (__isset.scalar_type != rhs.__isset.scalar_type)
      return false;
    else if (__isset.scalar_type && !(scalar_type == rhs.scalar_type))
      return false;
    if (__isset.list_type != rhs.__isset.list_type)
      return false;
    else if (__isset.list_type && !(list_type == rhs.list_type))
      return false;
    if (__isset.map_type != rhs.__isset.map_type)
      return false;
    else if (__isset.map_type && !(map_type == rhs.map_type))
      return false;
    if (__isset.set_type != rhs.__isset.set_type)
      return false;
    else if (__isset.set_type && !(set_type == rhs.set_type))
      return false;
    if (__isset.reference_type != rhs.__isset.reference_type)
      return false;
    else if (__isset.reference_type && !(reference_type == rhs.reference_type))
      return false;
    return true;
  }
  bool operator != (const TypeDefinition &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TypeDefinition & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(TypeDefinition &a, TypeDefinition &b);

std::ostream& operator<<(std::ostream& out, const TypeDefinition& obj);

}} // namespace

#endif
