/**
 * Autogenerated by Thrift Compiler (2.7.0-upfluence)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "type_definition_constants.h"

namespace types { namespace type_definition {

const type_definitionConstants g_type_definition_constants;

type_definitionConstants::type_definitionConstants() {
}

}} // namespace

