/**
 * Autogenerated by Thrift Compiler (v2.6.8-upfluence)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "value_definition_constants.h"

namespace types { namespace value {

const value_definitionConstants g_value_definition_constants;

value_definitionConstants::value_definitionConstants() {
}

}} // namespace

