/**
 * Autogenerated by Thrift Compiler (v2.7.0-upfluence)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef value_definition_CONSTANTS_H
#define value_definition_CONSTANTS_H

#include "value_definition_types.h"

namespace types { namespace value_definition {

class value_definitionConstants {
 public:
  value_definitionConstants();

};

extern const value_definitionConstants g_value_definition_constants;

}} // namespace

#endif
