/**
 * Autogenerated by Thrift Compiler (2.5.4-upfluence)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "value_constants.h"

namespace types { namespace value {

const valueConstants g_value_constants;

valueConstants::valueConstants() {
}

}} // namespace

