#
# Autogenerated by Thrift Compiler (v2.6.8-upfluence)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'thrift/types/known/duration/duration_types'

module Thrift
  module Types
    module Known
      module Duration
      end
    end
  end
end
