#
# Autogenerated by Thrift Compiler (v2.7.0-upfluence)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'thrift/types/program_definition/program_definition_types'


module Thrift
  module Types
    module Plugin
      class GenerateCodeRequest; end

      class GenerateCodeResponse; end

      class GenerateCodeRequest
        include ::Thrift::Struct, ::Thrift::Struct_Union

        NAME = 'GenerateCodeRequest'.freeze
        NAMESPACE = 'types.plugin'.freeze

        LEGACY_ANNOTATIONS = {
        }.freeze

        STRUCTURED_ANNOTATIONS = [
        ].freeze

        THRIFT_FIELD_INDEX_PROGRAM = 1
        THRIFT_FIELD_INDEX_LANGUAGE = 2
        THRIFT_FIELD_INDEX_OPTIONS = 3

        THRIFT_FIELD_PROGRAM_LEGACY_ANNOTATIONS = {
        }.freeze

        THRIFT_FIELD_PROGRAM_STRUCTURED_ANNOTATIONS = [
        ].freeze

        THRIFT_FIELD_LANGUAGE_LEGACY_ANNOTATIONS = {
        }.freeze

        THRIFT_FIELD_LANGUAGE_STRUCTURED_ANNOTATIONS = [
        ].freeze

        THRIFT_FIELD_OPTIONS_LEGACY_ANNOTATIONS = {
        }.freeze

        THRIFT_FIELD_OPTIONS_STRUCTURED_ANNOTATIONS = [
        ].freeze

        FIELDS = {
          THRIFT_FIELD_INDEX_PROGRAM => {type: ::Thrift::Types::STRUCT, name: 'program', class: ::Thrift::Types::Program_definition::ProgramDefinition, legacy_annotations: THRIFT_FIELD_PROGRAM_LEGACY_ANNOTATIONS, structured_annotations: THRIFT_FIELD_PROGRAM_STRUCTURED_ANNOTATIONS},
          THRIFT_FIELD_INDEX_LANGUAGE => {type: ::Thrift::Types::STRING, name: 'language', legacy_annotations: THRIFT_FIELD_LANGUAGE_LEGACY_ANNOTATIONS, structured_annotations: THRIFT_FIELD_LANGUAGE_STRUCTURED_ANNOTATIONS},
          THRIFT_FIELD_INDEX_OPTIONS => {type: ::Thrift::Types::MAP, name: 'options', key: {type: ::Thrift::Types::STRING}, value: {type: ::Thrift::Types::STRING}, legacy_annotations: THRIFT_FIELD_OPTIONS_LEGACY_ANNOTATIONS, structured_annotations: THRIFT_FIELD_OPTIONS_STRUCTURED_ANNOTATIONS}
        }

        def struct_fields; FIELDS; end

        def validate
          raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field program is unset!') unless @program
          raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field language is unset!') unless @language
          raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field options is unset!') unless @options
        end

        ::Thrift::Struct.generate_accessors self
        ::Thrift.register_struct_type self
      end

      class GenerateCodeResponse
        include ::Thrift::Struct, ::Thrift::Struct_Union

        NAME = 'GenerateCodeResponse'.freeze
        NAMESPACE = 'types.plugin'.freeze

        LEGACY_ANNOTATIONS = {
        }.freeze

        STRUCTURED_ANNOTATIONS = [
        ].freeze

        THRIFT_FIELD_INDEX_FILES = 1

        THRIFT_FIELD_FILES_LEGACY_ANNOTATIONS = {
        }.freeze

        THRIFT_FIELD_FILES_STRUCTURED_ANNOTATIONS = [
        ].freeze

        FIELDS = {
          THRIFT_FIELD_INDEX_FILES => {type: ::Thrift::Types::MAP, name: 'files', key: {type: ::Thrift::Types::STRING}, value: {type: ::Thrift::Types::STRING, binary: true}, legacy_annotations: THRIFT_FIELD_FILES_LEGACY_ANNOTATIONS, structured_annotations: THRIFT_FIELD_FILES_STRUCTURED_ANNOTATIONS}
        }

        def struct_fields; FIELDS; end

        def validate
          raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field files is unset!') unless @files
        end

        ::Thrift::Struct.generate_accessors self
        ::Thrift.register_struct_type self
      end

    end
  end
end
