// Autogenerated by Thrift Compiler (v2.7.0-upfluence)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package value_definition

import (
	"bytes"
	"context"
	"fmt"
	"github.com/upfluence/thrift/lib/go/thrift"
	"reflect"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = context.Background
var _ = reflect.DeepEqual
var _ = bytes.Equal

var GoUnusedProtection__ int

const Namespace = "types.value_definition"

func init() {
	thrift.RegisterStruct((*NullValueDefinition)(nil))
	thrift.RegisterStruct((*ListValueDefinition)(nil))
	thrift.RegisterStruct((*MapEntryDefinition)(nil))
	thrift.RegisterStruct((*MapValueDefinition)(nil))
	thrift.RegisterStruct((*ValueDefinition)(nil))
	thrift.RegisterStruct((*StructValueDefinition)(nil))
}
