#
# Autogenerated by Thrift Compiler (v2.6.8-upfluence)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

module Thrift
  module Types
    module Core
      class Reference; end

      class Reference
        include ::Thrift::Struct, ::Thrift::Struct_Union

        NAME = 'Reference'.freeze
        NAMESPACE = 'types.core'.freeze

        LEGACY_ANNOTATIONS = {
        }.freeze

        STRUCTURED_ANNOTATIONS = [
        ].freeze

        THRIFT_FIELD_INDEX_NAMESPACE_ = 1
        THRIFT_FIELD_INDEX_NAME = 2

        THRIFT_FIELD_NAMESPACE__LEGACY_ANNOTATIONS = {
        }.freeze

        THRIFT_FIELD_NAMESPACE__STRUCTURED_ANNOTATIONS = [
        ].freeze

        THRIFT_FIELD_NAME_LEGACY_ANNOTATIONS = {
        }.freeze

        THRIFT_FIELD_NAME_STRUCTURED_ANNOTATIONS = [
        ].freeze

        FIELDS = {
          THRIFT_FIELD_INDEX_NAMESPACE_ => {type: ::Thrift::Types::STRING, name: 'namespace_', optional: true, legacy_annotations: THRIFT_FIELD_NAMESPACE__LEGACY_ANNOTATIONS, structured_annotations: THRIFT_FIELD_NAMESPACE__STRUCTURED_ANNOTATIONS},
          THRIFT_FIELD_INDEX_NAME => {type: ::Thrift::Types::STRING, name: 'name', legacy_annotations: THRIFT_FIELD_NAME_LEGACY_ANNOTATIONS, structured_annotations: THRIFT_FIELD_NAME_STRUCTURED_ANNOTATIONS}
        }

        def struct_fields; FIELDS; end

        def validate
          raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field name is unset!') unless @name
        end

        ::Thrift::Struct.generate_accessors self
        ::Thrift.register_struct_type self
      end

    end
  end
end
