// Autogenerated by Thrift Compiler (v2.7.0-upfluence)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package struct_definition

import (
	"bytes"
	"context"
	"fmt"
	"github.com/upfluence/thrift/lib/go/thrift"
	"github.com/upfluence/thrift/lib/go/thrift/types/annotation_definition"
	"github.com/upfluence/thrift/lib/go/thrift/types/type_definition"
	"reflect"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = context.Background
var _ = reflect.DeepEqual
var _ = bytes.Equal

var _ = annotation_definition.GoUnusedProtection__
var _ = type_definition.GoUnusedProtection__

var GoUnusedProtection__ int

const Namespace = "types.struct_definition"

func init() {
	thrift.RegisterStruct((*FieldDefinition)(nil))
	thrift.RegisterStruct((*StructDefinition)(nil))
}
