#
# Autogenerated by Thrift Compiler (2.7.0-upfluence)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'thrift/types/annotation_definition/annotation_definition_types'

module Thrift
  module Types
    module Annotation_definition
    end
  end
end
