#
# Autogenerated by Thrift Compiler (v2.6.8-upfluence)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

module Thrift
  module Types
    module Value
      class NullValueDefinition; end

      class ListValueDefinition; end

      class MapEntryDefinition; end

      class MapValueDefinition; end

      class ValueDefinition < ::Thrift::Union; end

      class StructValueDefinition; end

      class NullValueDefinition
        include ::Thrift::Struct, ::Thrift::Struct_Union

        NAME = 'NullValueDefinition'.freeze
        NAMESPACE = 'types.value'.freeze

        LEGACY_ANNOTATIONS = {
        }.freeze

        STRUCTURED_ANNOTATIONS = [
        ].freeze


        FIELDS = {

        }

        def struct_fields; FIELDS; end

        def validate
        end

        ::Thrift::Struct.generate_accessors self
        ::Thrift.register_struct_type self
      end

      class ListValueDefinition
        include ::Thrift::Struct, ::Thrift::Struct_Union

        NAME = 'ListValueDefinition'.freeze
        NAMESPACE = 'types.value'.freeze

        LEGACY_ANNOTATIONS = {
        }.freeze

        STRUCTURED_ANNOTATIONS = [
        ].freeze

        THRIFT_FIELD_INDEX_VALUES = 1

        THRIFT_FIELD_VALUES_LEGACY_ANNOTATIONS = {
        }.freeze

        THRIFT_FIELD_VALUES_STRUCTURED_ANNOTATIONS = [
        ].freeze

        FIELDS = {
          THRIFT_FIELD_INDEX_VALUES => {type: ::Thrift::Types::LIST, name: 'values', element: {type: ::Thrift::Types::STRUCT, class: ::Thrift::Types::Value::ValueDefinition}, legacy_annotations: THRIFT_FIELD_VALUES_LEGACY_ANNOTATIONS, structured_annotations: THRIFT_FIELD_VALUES_STRUCTURED_ANNOTATIONS}
        }

        def struct_fields; FIELDS; end

        def validate
          raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field values is unset!') unless @values
        end

        ::Thrift::Struct.generate_accessors self
        ::Thrift.register_struct_type self
      end

      class MapEntryDefinition
        include ::Thrift::Struct, ::Thrift::Struct_Union

        NAME = 'MapEntryDefinition'.freeze
        NAMESPACE = 'types.value'.freeze

        LEGACY_ANNOTATIONS = {
        }.freeze

        STRUCTURED_ANNOTATIONS = [
        ].freeze

        THRIFT_FIELD_INDEX_KEY = 1
        THRIFT_FIELD_INDEX_VALUE = 2

        THRIFT_FIELD_KEY_LEGACY_ANNOTATIONS = {
        }.freeze

        THRIFT_FIELD_KEY_STRUCTURED_ANNOTATIONS = [
        ].freeze

        THRIFT_FIELD_VALUE_LEGACY_ANNOTATIONS = {
        }.freeze

        THRIFT_FIELD_VALUE_STRUCTURED_ANNOTATIONS = [
        ].freeze

        FIELDS = {
          THRIFT_FIELD_INDEX_KEY => {type: ::Thrift::Types::STRUCT, name: 'key', class: ::Thrift::Types::Value::ValueDefinition, legacy_annotations: THRIFT_FIELD_KEY_LEGACY_ANNOTATIONS, structured_annotations: THRIFT_FIELD_KEY_STRUCTURED_ANNOTATIONS},
          THRIFT_FIELD_INDEX_VALUE => {type: ::Thrift::Types::STRUCT, name: 'value', class: ::Thrift::Types::Value::ValueDefinition, legacy_annotations: THRIFT_FIELD_VALUE_LEGACY_ANNOTATIONS, structured_annotations: THRIFT_FIELD_VALUE_STRUCTURED_ANNOTATIONS}
        }

        def struct_fields; FIELDS; end

        def validate
          raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field key is unset!') unless @key
          raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field value is unset!') unless @value
        end

        ::Thrift::Struct.generate_accessors self
        ::Thrift.register_struct_type self
      end

      class MapValueDefinition
        include ::Thrift::Struct, ::Thrift::Struct_Union

        NAME = 'MapValueDefinition'.freeze
        NAMESPACE = 'types.value'.freeze

        LEGACY_ANNOTATIONS = {
        }.freeze

        STRUCTURED_ANNOTATIONS = [
        ].freeze

        THRIFT_FIELD_INDEX_ENTRIES = 1

        THRIFT_FIELD_ENTRIES_LEGACY_ANNOTATIONS = {
        }.freeze

        THRIFT_FIELD_ENTRIES_STRUCTURED_ANNOTATIONS = [
        ].freeze

        FIELDS = {
          THRIFT_FIELD_INDEX_ENTRIES => {type: ::Thrift::Types::LIST, name: 'entries', element: {type: ::Thrift::Types::STRUCT, class: ::Thrift::Types::Value::MapEntryDefinition}, legacy_annotations: THRIFT_FIELD_ENTRIES_LEGACY_ANNOTATIONS, structured_annotations: THRIFT_FIELD_ENTRIES_STRUCTURED_ANNOTATIONS}
        }

        def struct_fields; FIELDS; end

        def validate
          raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field entries is unset!') unless @entries
        end

        ::Thrift::Struct.generate_accessors self
        ::Thrift.register_struct_type self
      end

      class ValueDefinition < ::Thrift::Union
        include ::Thrift::Struct_Union

        NAME = 'ValueDefinition'.freeze
        NAMESPACE = 'types.value'.freeze

        LEGACY_ANNOTATIONS = {
        }.freeze

        STRUCTURED_ANNOTATIONS = [
        ].freeze

        class << self
          def null_value(val)
            ValueDefinition.new(:null_value, val)
          end

          def string_value(val)
            ValueDefinition.new(:string_value, val)
          end

          def binary_value(val)
            ValueDefinition.new(:binary_value, val)
          end

          def integer_value(val)
            ValueDefinition.new(:integer_value, val)
          end

          def double_value(val)
            ValueDefinition.new(:double_value, val)
          end

          def bool_value(val)
            ValueDefinition.new(:bool_value, val)
          end

          def list_value(val)
            ValueDefinition.new(:list_value, val)
          end

          def map_value(val)
            ValueDefinition.new(:map_value, val)
          end

          def struct_value(val)
            ValueDefinition.new(:struct_value, val)
          end
        end

        THRIFT_FIELD_INDEX_NULL_VALUE = 1
        THRIFT_FIELD_INDEX_STRING_VALUE = 2
        THRIFT_FIELD_INDEX_BINARY_VALUE = 3
        THRIFT_FIELD_INDEX_INTEGER_VALUE = 4
        THRIFT_FIELD_INDEX_DOUBLE_VALUE = 5
        THRIFT_FIELD_INDEX_BOOL_VALUE = 6
        THRIFT_FIELD_INDEX_LIST_VALUE = 7
        THRIFT_FIELD_INDEX_MAP_VALUE = 8
        THRIFT_FIELD_INDEX_STRUCT_VALUE = 9

        THRIFT_FIELD_NULL_VALUE_LEGACY_ANNOTATIONS = {
        }.freeze

        THRIFT_FIELD_NULL_VALUE_STRUCTURED_ANNOTATIONS = [
        ].freeze

        THRIFT_FIELD_STRING_VALUE_LEGACY_ANNOTATIONS = {
        }.freeze

        THRIFT_FIELD_STRING_VALUE_STRUCTURED_ANNOTATIONS = [
        ].freeze

        THRIFT_FIELD_BINARY_VALUE_LEGACY_ANNOTATIONS = {
        }.freeze

        THRIFT_FIELD_BINARY_VALUE_STRUCTURED_ANNOTATIONS = [
        ].freeze

        THRIFT_FIELD_INTEGER_VALUE_LEGACY_ANNOTATIONS = {
        }.freeze

        THRIFT_FIELD_INTEGER_VALUE_STRUCTURED_ANNOTATIONS = [
        ].freeze

        THRIFT_FIELD_DOUBLE_VALUE_LEGACY_ANNOTATIONS = {
        }.freeze

        THRIFT_FIELD_DOUBLE_VALUE_STRUCTURED_ANNOTATIONS = [
        ].freeze

        THRIFT_FIELD_BOOL_VALUE_LEGACY_ANNOTATIONS = {
        }.freeze

        THRIFT_FIELD_BOOL_VALUE_STRUCTURED_ANNOTATIONS = [
        ].freeze

        THRIFT_FIELD_LIST_VALUE_LEGACY_ANNOTATIONS = {
        }.freeze

        THRIFT_FIELD_LIST_VALUE_STRUCTURED_ANNOTATIONS = [
        ].freeze

        THRIFT_FIELD_MAP_VALUE_LEGACY_ANNOTATIONS = {
        }.freeze

        THRIFT_FIELD_MAP_VALUE_STRUCTURED_ANNOTATIONS = [
        ].freeze

        THRIFT_FIELD_STRUCT_VALUE_LEGACY_ANNOTATIONS = {
        }.freeze

        THRIFT_FIELD_STRUCT_VALUE_STRUCTURED_ANNOTATIONS = [
        ].freeze

        FIELDS = {
          THRIFT_FIELD_INDEX_NULL_VALUE => {type: ::Thrift::Types::STRUCT, name: 'null_value', class: ::Thrift::Types::Value::NullValueDefinition, optional: true, legacy_annotations: THRIFT_FIELD_NULL_VALUE_LEGACY_ANNOTATIONS, structured_annotations: THRIFT_FIELD_NULL_VALUE_STRUCTURED_ANNOTATIONS},
          THRIFT_FIELD_INDEX_STRING_VALUE => {type: ::Thrift::Types::STRING, name: 'string_value', optional: true, legacy_annotations: THRIFT_FIELD_STRING_VALUE_LEGACY_ANNOTATIONS, structured_annotations: THRIFT_FIELD_STRING_VALUE_STRUCTURED_ANNOTATIONS},
          THRIFT_FIELD_INDEX_BINARY_VALUE => {type: ::Thrift::Types::STRING, name: 'binary_value', binary: true, optional: true, legacy_annotations: THRIFT_FIELD_BINARY_VALUE_LEGACY_ANNOTATIONS, structured_annotations: THRIFT_FIELD_BINARY_VALUE_STRUCTURED_ANNOTATIONS},
          THRIFT_FIELD_INDEX_INTEGER_VALUE => {type: ::Thrift::Types::I64, name: 'integer_value', optional: true, legacy_annotations: THRIFT_FIELD_INTEGER_VALUE_LEGACY_ANNOTATIONS, structured_annotations: THRIFT_FIELD_INTEGER_VALUE_STRUCTURED_ANNOTATIONS},
          THRIFT_FIELD_INDEX_DOUBLE_VALUE => {type: ::Thrift::Types::DOUBLE, name: 'double_value', optional: true, legacy_annotations: THRIFT_FIELD_DOUBLE_VALUE_LEGACY_ANNOTATIONS, structured_annotations: THRIFT_FIELD_DOUBLE_VALUE_STRUCTURED_ANNOTATIONS},
          THRIFT_FIELD_INDEX_BOOL_VALUE => {type: ::Thrift::Types::BOOL, name: 'bool_value', optional: true, legacy_annotations: THRIFT_FIELD_BOOL_VALUE_LEGACY_ANNOTATIONS, structured_annotations: THRIFT_FIELD_BOOL_VALUE_STRUCTURED_ANNOTATIONS},
          THRIFT_FIELD_INDEX_LIST_VALUE => {type: ::Thrift::Types::STRUCT, name: 'list_value', class: ::Thrift::Types::Value::ListValueDefinition, optional: true, legacy_annotations: THRIFT_FIELD_LIST_VALUE_LEGACY_ANNOTATIONS, structured_annotations: THRIFT_FIELD_LIST_VALUE_STRUCTURED_ANNOTATIONS},
          THRIFT_FIELD_INDEX_MAP_VALUE => {type: ::Thrift::Types::STRUCT, name: 'map_value', class: ::Thrift::Types::Value::MapValueDefinition, optional: true, legacy_annotations: THRIFT_FIELD_MAP_VALUE_LEGACY_ANNOTATIONS, structured_annotations: THRIFT_FIELD_MAP_VALUE_STRUCTURED_ANNOTATIONS},
          THRIFT_FIELD_INDEX_STRUCT_VALUE => {type: ::Thrift::Types::STRUCT, name: 'struct_value', class: ::Thrift::Types::Value::StructValueDefinition, optional: true, legacy_annotations: THRIFT_FIELD_STRUCT_VALUE_LEGACY_ANNOTATIONS, structured_annotations: THRIFT_FIELD_STRUCT_VALUE_STRUCTURED_ANNOTATIONS}
        }

        def struct_fields; FIELDS; end

        def validate
          raise(StandardError, 'Union fields are not set.') if get_set_field.nil? || get_value.nil?
        end

        ::Thrift::Union.generate_accessors self
        ::Thrift.register_struct_type self
      end

      class StructValueDefinition
        include ::Thrift::Struct, ::Thrift::Struct_Union

        NAME = 'StructValueDefinition'.freeze
        NAMESPACE = 'types.value'.freeze

        LEGACY_ANNOTATIONS = {
        }.freeze

        STRUCTURED_ANNOTATIONS = [
        ].freeze

        THRIFT_FIELD_INDEX_FIELDS = 1

        THRIFT_FIELD_FIELDS_LEGACY_ANNOTATIONS = {
        }.freeze

        THRIFT_FIELD_FIELDS_STRUCTURED_ANNOTATIONS = [
        ].freeze

        FIELDS = {
          THRIFT_FIELD_INDEX_FIELDS => {type: ::Thrift::Types::MAP, name: 'fields', key: {type: ::Thrift::Types::STRING}, value: {type: ::Thrift::Types::STRUCT, class: ::Thrift::Types::Value::ValueDefinition}, optional: true, legacy_annotations: THRIFT_FIELD_FIELDS_LEGACY_ANNOTATIONS, structured_annotations: THRIFT_FIELD_FIELDS_STRUCTURED_ANNOTATIONS}
        }

        def struct_fields; FIELDS; end

        def validate
        end

        ::Thrift::Struct.generate_accessors self
        ::Thrift.register_struct_type self
      end

    end
  end
end
