#
# Autogenerated by Thrift Compiler (2.3.0-upfluence)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'any_types'

module Thrift
  module Types
    module Known
      module Any
      end
    end
  end
end
