#
# Autogenerated by Thrift Compiler (2.5.4-upfluence)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

module Thrift
  module Types
    module Known
      module Timestamp
        class Timestamp; end

        class Timestamp
          include ::Thrift::Struct, ::Thrift::Struct_Union

          NAME = 'Timestamp'.freeze
          NAMESPACE = 'types.known.timestamp'.freeze

          THRIFT_FIELD_INDEX_SECONDS = 1
          THRIFT_FIELD_INDEX_NANOS = 2

          FIELDS = {
            THRIFT_FIELD_INDEX_SECONDS => {type: ::Thrift::Types::I64, name: 'seconds'},
            THRIFT_FIELD_INDEX_NANOS => {type: ::Thrift::Types::I32, name: 'nanos'}
          }

          def struct_fields; FIELDS; end

          def validate
            raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field seconds is unset!') unless @seconds
            raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field nanos is unset!') unless @nanos
          end

          ::Thrift::Struct.generate_accessors self
          ::Thrift.register_struct_type self
        end

      end
    end
  end
end
