#
# Autogenerated by Thrift Compiler (v2.6.8-upfluence)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'thrift/types/service_definition/service_definition_types'

module Thrift
  module Types
    module Service_definition
    end
  end
end
