// Autogenerated by Thrift Compiler (v2.7.0-upfluence)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package type_definition

import (
	"bytes"
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"github.com/upfluence/thrift/lib/go/thrift"
	"github.com/upfluence/thrift/lib/go/thrift/types/annotation_definition"
	"github.com/upfluence/thrift/lib/go/thrift/types/core"
	"reflect"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = context.Background
var _ = reflect.DeepEqual
var _ = bytes.Equal

var _ = core.GoUnusedProtection__
var _ = annotation_definition.GoUnusedProtection__

type ScalarType int64

const (
	ScalarType_Unknown ScalarType = 0
	ScalarType_String  ScalarType = 1
	ScalarType_Binary  ScalarType = 2
	ScalarType_Bool    ScalarType = 3
	ScalarType_I16     ScalarType = 4
	ScalarType_I32     ScalarType = 5
	ScalarType_I64     ScalarType = 6
	ScalarType_Double  ScalarType = 7
)

func (p ScalarType) String() string {
	switch p {
	case ScalarType_Unknown:
		return "Unknown"
	case ScalarType_String:
		return "String"
	case ScalarType_Binary:
		return "Binary"
	case ScalarType_Bool:
		return "Bool"
	case ScalarType_I16:
		return "I16"
	case ScalarType_I32:
		return "I32"
	case ScalarType_I64:
		return "I64"
	case ScalarType_Double:
		return "Double"
	}
	return "<UNSET>"
}

func ScalarTypeFromString(s string) (ScalarType, error) {
	switch s {
	case "Unknown":
		return ScalarType_Unknown, nil
	case "String":
		return ScalarType_String, nil
	case "Binary":
		return ScalarType_Binary, nil
	case "Bool":
		return ScalarType_Bool, nil
	case "I16":
		return ScalarType_I16, nil
	case "I32":
		return ScalarType_I32, nil
	case "I64":
		return ScalarType_I64, nil
	case "Double":
		return ScalarType_Double, nil
	}
	return ScalarType(0), fmt.Errorf("not a valid ScalarType string")
}

func ScalarTypePtr(v ScalarType) *ScalarType { return &v }

func (p ScalarType) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *ScalarType) UnmarshalText(text []byte) error {
	q, err := ScalarTypeFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *ScalarType) Scan(value interface{}) error {
	v, ok := value.(int64)
	if !ok {
		return errors.New("Scan value is not int64")
	}
	*p = ScalarType(v)
	return nil
}

func (p *ScalarType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

// Attributes:
//   - ElementType
type ListType struct {
	ElementType *Type `thrift:"element_type,1,required" db:"element_type" json:"element_type"`
}

func NewListType() *ListType {
	return &ListType{}
}

var listTypeStructDefinition = thrift.StructDefinition{
	Namespace: Namespace,
	AnnotatedDefinition: thrift.AnnotatedDefinition{
		Name:                  "ListType",
		LegacyAnnotations:     map[string]string{},
		StructuredAnnotations: []thrift.RegistrableStruct{},
	},
	Fields: []thrift.FieldDefinition{
		{
			AnnotatedDefinition: thrift.AnnotatedDefinition{
				Name:                  "element_type",
				LegacyAnnotations:     map[string]string{},
				StructuredAnnotations: []thrift.RegistrableStruct{},
			},
		},
	},
}

func (p *ListType) StructDefinition() thrift.StructDefinition {
	return listTypeStructDefinition
}

var ListType_ElementType_DEFAULT *Type

func (p *ListType) GetElementType() *Type {
	if !p.IsSetElementType() {
		return ListType_ElementType_DEFAULT
	}
	return p.ElementType
}

func (p *ListType) SetElementType(v *Type) {
	p.ElementType = v
}
func (p *ListType) IsSetElementType() bool {
	return p.ElementType != nil
}

func (p *ListType) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	var issetElementType bool = false

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField1(iprot); err != nil {
					return err
				}
				issetElementType = true
			} else {
				if err := iprot.Skip(fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	if !issetElementType {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field ElementType is not set"))
	}
	return nil
}

func (p *ListType) ReadField1(iprot thrift.TProtocol) error {
	p.ElementType = NewType()
	if err := p.ElementType.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.ElementType), err)
	}
	return nil
}

func (p *ListType) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("ListType"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *ListType) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("element_type", thrift.STRUCT, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:element_type: ", p), err)
	}
	if err := p.ElementType.Write(oprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.ElementType), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:element_type: ", p), err)
	}
	return err
}

func (p *ListType) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf(
		"ListType({element_type: %v})",
		p.GetElementType(),
	)
}

// Attributes:
//   - KeyType
//   - ValueType
type MapType struct {
	KeyType   *Type `thrift:"key_type,1,required" db:"key_type" json:"key_type"`
	ValueType *Type `thrift:"value_type,2,required" db:"value_type" json:"value_type"`
}

func NewMapType() *MapType {
	return &MapType{}
}

var mapTypeStructDefinition = thrift.StructDefinition{
	Namespace: Namespace,
	AnnotatedDefinition: thrift.AnnotatedDefinition{
		Name:                  "MapType",
		LegacyAnnotations:     map[string]string{},
		StructuredAnnotations: []thrift.RegistrableStruct{},
	},
	Fields: []thrift.FieldDefinition{
		{
			AnnotatedDefinition: thrift.AnnotatedDefinition{
				Name:                  "key_type",
				LegacyAnnotations:     map[string]string{},
				StructuredAnnotations: []thrift.RegistrableStruct{},
			},
		},

		{
			AnnotatedDefinition: thrift.AnnotatedDefinition{
				Name:                  "value_type",
				LegacyAnnotations:     map[string]string{},
				StructuredAnnotations: []thrift.RegistrableStruct{},
			},
		},
	},
}

func (p *MapType) StructDefinition() thrift.StructDefinition {
	return mapTypeStructDefinition
}

var MapType_KeyType_DEFAULT *Type

func (p *MapType) GetKeyType() *Type {
	if !p.IsSetKeyType() {
		return MapType_KeyType_DEFAULT
	}
	return p.KeyType
}

func (p *MapType) SetKeyType(v *Type) {
	p.KeyType = v
}

var MapType_ValueType_DEFAULT *Type

func (p *MapType) GetValueType() *Type {
	if !p.IsSetValueType() {
		return MapType_ValueType_DEFAULT
	}
	return p.ValueType
}

func (p *MapType) SetValueType(v *Type) {
	p.ValueType = v
}
func (p *MapType) IsSetKeyType() bool {
	return p.KeyType != nil
}

func (p *MapType) IsSetValueType() bool {
	return p.ValueType != nil
}

func (p *MapType) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	var issetKeyType bool = false
	var issetValueType bool = false

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField1(iprot); err != nil {
					return err
				}
				issetKeyType = true
			} else {
				if err := iprot.Skip(fieldTypeId); err != nil {
					return err
				}
			}
		case 2:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField2(iprot); err != nil {
					return err
				}
				issetValueType = true
			} else {
				if err := iprot.Skip(fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	if !issetKeyType {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field KeyType is not set"))
	}
	if !issetValueType {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field ValueType is not set"))
	}
	return nil
}

func (p *MapType) ReadField1(iprot thrift.TProtocol) error {
	p.KeyType = NewType()
	if err := p.KeyType.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.KeyType), err)
	}
	return nil
}

func (p *MapType) ReadField2(iprot thrift.TProtocol) error {
	p.ValueType = NewType()
	if err := p.ValueType.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.ValueType), err)
	}
	return nil
}

func (p *MapType) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("MapType"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(oprot); err != nil {
			return err
		}
		if err := p.writeField2(oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *MapType) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("key_type", thrift.STRUCT, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:key_type: ", p), err)
	}
	if err := p.KeyType.Write(oprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.KeyType), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:key_type: ", p), err)
	}
	return err
}

func (p *MapType) writeField2(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("value_type", thrift.STRUCT, 2); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:value_type: ", p), err)
	}
	if err := p.ValueType.Write(oprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.ValueType), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 2:value_type: ", p), err)
	}
	return err
}

func (p *MapType) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf(
		"MapType({key_type: %v, value_type: %v})",
		p.GetKeyType(),
		p.GetValueType(),
	)
}

// Attributes:
//   - ElementType
type SetType struct {
	ElementType *Type `thrift:"element_type,1,required" db:"element_type" json:"element_type"`
}

func NewSetType() *SetType {
	return &SetType{}
}

var setTypeStructDefinition = thrift.StructDefinition{
	Namespace: Namespace,
	AnnotatedDefinition: thrift.AnnotatedDefinition{
		Name:                  "SetType",
		LegacyAnnotations:     map[string]string{},
		StructuredAnnotations: []thrift.RegistrableStruct{},
	},
	Fields: []thrift.FieldDefinition{
		{
			AnnotatedDefinition: thrift.AnnotatedDefinition{
				Name:                  "element_type",
				LegacyAnnotations:     map[string]string{},
				StructuredAnnotations: []thrift.RegistrableStruct{},
			},
		},
	},
}

func (p *SetType) StructDefinition() thrift.StructDefinition {
	return setTypeStructDefinition
}

var SetType_ElementType_DEFAULT *Type

func (p *SetType) GetElementType() *Type {
	if !p.IsSetElementType() {
		return SetType_ElementType_DEFAULT
	}
	return p.ElementType
}

func (p *SetType) SetElementType(v *Type) {
	p.ElementType = v
}
func (p *SetType) IsSetElementType() bool {
	return p.ElementType != nil
}

func (p *SetType) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	var issetElementType bool = false

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField1(iprot); err != nil {
					return err
				}
				issetElementType = true
			} else {
				if err := iprot.Skip(fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	if !issetElementType {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field ElementType is not set"))
	}
	return nil
}

func (p *SetType) ReadField1(iprot thrift.TProtocol) error {
	p.ElementType = NewType()
	if err := p.ElementType.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.ElementType), err)
	}
	return nil
}

func (p *SetType) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("SetType"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *SetType) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("element_type", thrift.STRUCT, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:element_type: ", p), err)
	}
	if err := p.ElementType.Write(oprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.ElementType), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:element_type: ", p), err)
	}
	return err
}

func (p *SetType) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf(
		"SetType({element_type: %v})",
		p.GetElementType(),
	)
}

// Attributes:
//   - ScalarType
//   - ListType
//   - MapType
//   - SetType
//   - ReferenceType
type Type struct {
	ScalarType *ScalarType `thrift:"scalar_type,1" db:"scalar_type" json:"scalar_type,omitempty"`
	ListType   *ListType   `thrift:"list_type,2" db:"list_type" json:"list_type,omitempty"`
	MapType    *MapType    `thrift:"map_type,3" db:"map_type" json:"map_type,omitempty"`
	SetType    *SetType    `thrift:"set_type,4" db:"set_type" json:"set_type,omitempty"`
	// unused fields # 5 to 7
	ReferenceType *core.Reference `thrift:"reference_type,8" db:"reference_type" json:"reference_type,omitempty"`
}

func NewType() *Type {
	return &Type{}
}

var typeStructDefinition = thrift.StructDefinition{
	Namespace: Namespace,
	IsUnion:   true,
	AnnotatedDefinition: thrift.AnnotatedDefinition{
		Name:                  "Type",
		LegacyAnnotations:     map[string]string{},
		StructuredAnnotations: []thrift.RegistrableStruct{},
	},
	Fields: []thrift.FieldDefinition{
		{
			AnnotatedDefinition: thrift.AnnotatedDefinition{
				Name:                  "scalar_type",
				LegacyAnnotations:     map[string]string{},
				StructuredAnnotations: []thrift.RegistrableStruct{},
			},
		},

		{
			AnnotatedDefinition: thrift.AnnotatedDefinition{
				Name:                  "list_type",
				LegacyAnnotations:     map[string]string{},
				StructuredAnnotations: []thrift.RegistrableStruct{},
			},
		},

		{
			AnnotatedDefinition: thrift.AnnotatedDefinition{
				Name:                  "map_type",
				LegacyAnnotations:     map[string]string{},
				StructuredAnnotations: []thrift.RegistrableStruct{},
			},
		},

		{
			AnnotatedDefinition: thrift.AnnotatedDefinition{
				Name:                  "set_type",
				LegacyAnnotations:     map[string]string{},
				StructuredAnnotations: []thrift.RegistrableStruct{},
			},
		},

		{
			AnnotatedDefinition: thrift.AnnotatedDefinition{
				Name:                  "reference_type",
				LegacyAnnotations:     map[string]string{},
				StructuredAnnotations: []thrift.RegistrableStruct{},
			},
		},
	},
}

func (p *Type) StructDefinition() thrift.StructDefinition {
	return typeStructDefinition
}

var Type_ScalarType_DEFAULT ScalarType

func (p *Type) GetScalarType() ScalarType {
	if !p.IsSetScalarType() {
		return Type_ScalarType_DEFAULT
	}
	return *p.ScalarType
}

func (p *Type) SetScalarType(v ScalarType) {
	p.ScalarType = &v
}

var Type_ListType_DEFAULT *ListType

func (p *Type) GetListType() *ListType {
	if !p.IsSetListType() {
		return Type_ListType_DEFAULT
	}
	return p.ListType
}

func (p *Type) SetListType(v *ListType) {
	p.ListType = v
}

var Type_MapType_DEFAULT *MapType

func (p *Type) GetMapType() *MapType {
	if !p.IsSetMapType() {
		return Type_MapType_DEFAULT
	}
	return p.MapType
}

func (p *Type) SetMapType(v *MapType) {
	p.MapType = v
}

var Type_SetType_DEFAULT *SetType

func (p *Type) GetSetType() *SetType {
	if !p.IsSetSetType() {
		return Type_SetType_DEFAULT
	}
	return p.SetType
}

func (p *Type) SetSetType(v *SetType) {
	p.SetType = v
}

var Type_ReferenceType_DEFAULT *core.Reference

func (p *Type) GetReferenceType() *core.Reference {
	if !p.IsSetReferenceType() {
		return Type_ReferenceType_DEFAULT
	}
	return p.ReferenceType
}

func (p *Type) SetReferenceType(v *core.Reference) {
	p.ReferenceType = v
}
func (p *Type) CountSetFieldsType() int {
	count := 0
	if p.IsSetScalarType() {
		count++
	}
	if p.IsSetListType() {
		count++
	}
	if p.IsSetMapType() {
		count++
	}
	if p.IsSetSetType() {
		count++
	}
	if p.IsSetReferenceType() {
		count++
	}
	return count

}

func (p *Type) Interface() interface{} {
	if p.IsSetScalarType() {
		return p.ScalarType
	}
	if p.IsSetListType() {
		return p.ListType
	}
	if p.IsSetMapType() {
		return p.MapType
	}
	if p.IsSetSetType() {
		return p.SetType
	}
	if p.IsSetReferenceType() {
		return p.ReferenceType
	}
	return nil

}

func (p *Type) IsSetScalarType() bool {
	return p.ScalarType != nil
}

func (p *Type) IsSetListType() bool {
	return p.ListType != nil
}

func (p *Type) IsSetMapType() bool {
	return p.MapType != nil
}

func (p *Type) IsSetSetType() bool {
	return p.SetType != nil
}

func (p *Type) IsSetReferenceType() bool {
	return p.ReferenceType != nil
}

func (p *Type) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.I32 {
				if err := p.ReadField1(iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(fieldTypeId); err != nil {
					return err
				}
			}
		case 2:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField2(iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(fieldTypeId); err != nil {
					return err
				}
			}
		case 3:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField3(iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(fieldTypeId); err != nil {
					return err
				}
			}
		case 4:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField4(iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(fieldTypeId); err != nil {
					return err
				}
			}
		case 8:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField8(iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *Type) ReadField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		temp := ScalarType(v)
		p.ScalarType = &temp
	}
	return nil
}

func (p *Type) ReadField2(iprot thrift.TProtocol) error {
	p.ListType = NewListType()
	if err := p.ListType.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.ListType), err)
	}
	return nil
}

func (p *Type) ReadField3(iprot thrift.TProtocol) error {
	p.MapType = NewMapType()
	if err := p.MapType.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.MapType), err)
	}
	return nil
}

func (p *Type) ReadField4(iprot thrift.TProtocol) error {
	p.SetType = NewSetType()
	if err := p.SetType.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.SetType), err)
	}
	return nil
}

func (p *Type) ReadField8(iprot thrift.TProtocol) error {
	p.ReferenceType = core.NewReference()
	if err := p.ReferenceType.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.ReferenceType), err)
	}
	return nil
}

func (p *Type) Write(oprot thrift.TProtocol) error {
	if c := p.CountSetFieldsType(); c != 1 {
		return fmt.Errorf("%T write union: exactly one field must be set (%d set).", p, c)
	}
	if err := oprot.WriteStructBegin("Type"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(oprot); err != nil {
			return err
		}
		if err := p.writeField2(oprot); err != nil {
			return err
		}
		if err := p.writeField3(oprot); err != nil {
			return err
		}
		if err := p.writeField4(oprot); err != nil {
			return err
		}
		if err := p.writeField8(oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *Type) writeField1(oprot thrift.TProtocol) (err error) {
	if p.IsSetScalarType() {
		if err := oprot.WriteFieldBegin("scalar_type", thrift.I32, 1); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:scalar_type: ", p), err)
		}
		if err := oprot.WriteI32(int32(*p.ScalarType)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.scalar_type (1) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 1:scalar_type: ", p), err)
		}
	}
	return err
}

func (p *Type) writeField2(oprot thrift.TProtocol) (err error) {
	if p.IsSetListType() {
		if err := oprot.WriteFieldBegin("list_type", thrift.STRUCT, 2); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:list_type: ", p), err)
		}
		if err := p.ListType.Write(oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.ListType), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 2:list_type: ", p), err)
		}
	}
	return err
}

func (p *Type) writeField3(oprot thrift.TProtocol) (err error) {
	if p.IsSetMapType() {
		if err := oprot.WriteFieldBegin("map_type", thrift.STRUCT, 3); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:map_type: ", p), err)
		}
		if err := p.MapType.Write(oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.MapType), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 3:map_type: ", p), err)
		}
	}
	return err
}

func (p *Type) writeField4(oprot thrift.TProtocol) (err error) {
	if p.IsSetSetType() {
		if err := oprot.WriteFieldBegin("set_type", thrift.STRUCT, 4); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:set_type: ", p), err)
		}
		if err := p.SetType.Write(oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.SetType), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 4:set_type: ", p), err)
		}
	}
	return err
}

func (p *Type) writeField8(oprot thrift.TProtocol) (err error) {
	if p.IsSetReferenceType() {
		if err := oprot.WriteFieldBegin("reference_type", thrift.STRUCT, 8); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 8:reference_type: ", p), err)
		}
		if err := p.ReferenceType.Write(oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.ReferenceType), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 8:reference_type: ", p), err)
		}
	}
	return err
}

func (p *Type) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf(
		"Type({scalar_type: %v, list_type: %v, map_type: %v, set_type: %v, reference_type: %v})",
		p.GetScalarType(),
		p.GetListType(),
		p.GetMapType(),
		p.GetSetType(),
		p.GetReferenceType(),
	)
}
