/**
 * Autogenerated by Thrift Compiler (2.7.0-upfluence)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "deprecation_constants.h"

namespace types { namespace annotation { namespace deprecation {

const deprecationConstants g_deprecation_constants;

deprecationConstants::deprecationConstants() {
}

}}} // namespace

