/**
 * Autogenerated by Thrift Compiler (2.5.4-upfluence)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "deprecation_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace types { namespace annotation { namespace deprecation {


Deprecated::~Deprecated() throw() {
}


const char* Deprecated::ascii_fingerprint = "99914B932BD37A50B983C5E7C90AE93B";
const uint8_t Deprecated::binary_fingerprint[16] = {0x99,0x91,0x4B,0x93,0x2B,0xD3,0x7A,0x50,0xB9,0x83,0xC5,0xE7,0xC9,0x0A,0xE9,0x3B};

uint32_t Deprecated::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    xfer += iprot->skip(ftype);
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t Deprecated::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  oprot->incrementRecursionDepth();
  xfer += oprot->writeStructBegin("Deprecated");

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  oprot->decrementRecursionDepth();
  return xfer;
}

void swap(Deprecated &a, Deprecated &b) {
  using ::std::swap;
  (void) a;
  (void) b;
}

Deprecated::Deprecated(const Deprecated& other0) {
  (void) other0;
}
Deprecated& Deprecated::operator=(const Deprecated& other1) {
  (void) other1;
  return *this;
}
std::ostream& operator<<(std::ostream& out, const Deprecated& obj) {
  using apache::thrift::to_string;
  (void) obj;
  out << "Deprecated(";
  out << ")";
  return out;
}

}}} // namespace
