/**
 * Autogenerated by Thrift Compiler (v2.6.8-upfluence)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef deprecation_CONSTANTS_H
#define deprecation_CONSTANTS_H

#include "deprecation_types.h"

namespace types { namespace annotation { namespace deprecation {

class deprecationConstants {
 public:
  deprecationConstants();

};

extern const deprecationConstants g_deprecation_constants;

}}} // namespace

#endif
