/**
 * Autogenerated by Thrift Compiler (2.7.0-upfluence)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "exception_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace types { namespace annotation { namespace exception {

int _kKindValues[] = {
  Kind::Unknown,
  Kind::Transient,
  Kind::Permanent,
  Kind::Stateful
};
const char* _kKindNames[] = {
  "Unknown",
  "Transient",
  "Permanent",
  "Stateful"
};
const std::map<int, const char*> _Kind_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(4, _kKindValues, _kKindNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));

std::ostream& operator<<(std::ostream& out, const Kind::type& val) {
  std::map<int, const char*>::const_iterator it = _Kind_VALUES_TO_NAMES.find(val);
  if (it != _Kind_VALUES_TO_NAMES.end()) {
    out << it->second;
  } else {
    out << static_cast<int>(val);
  }
  return out;
}

std::string to_string(const Kind::type& val) {
  std::map<int, const char*>::const_iterator it = _Kind_VALUES_TO_NAMES.find(val);
  if (it != _Kind_VALUES_TO_NAMES.end()) {
    return std::string(it->second);
  } else {
    return std::to_string(static_cast<int>(val));
  }
}

int _kBlameValues[] = {
  Blame::Unknown,
  Blame::Client,
  Blame::Server,
  Blame::ThirdParty
};
const char* _kBlameNames[] = {
  "Unknown",
  "Client",
  "Server",
  "ThirdParty"
};
const std::map<int, const char*> _Blame_VALUES_TO_NAMES(::apache::thrift::TEnumIterator(4, _kBlameValues, _kBlameNames), ::apache::thrift::TEnumIterator(-1, NULL, NULL));

std::ostream& operator<<(std::ostream& out, const Blame::type& val) {
  std::map<int, const char*>::const_iterator it = _Blame_VALUES_TO_NAMES.find(val);
  if (it != _Blame_VALUES_TO_NAMES.end()) {
    out << it->second;
  } else {
    out << static_cast<int>(val);
  }
  return out;
}

std::string to_string(const Blame::type& val) {
  std::map<int, const char*>::const_iterator it = _Blame_VALUES_TO_NAMES.find(val);
  if (it != _Blame_VALUES_TO_NAMES.end()) {
    return std::string(it->second);
  } else {
    return std::to_string(static_cast<int>(val));
  }
}


Safe::~Safe() noexcept {
}

std::ostream& operator<<(std::ostream& out, const Safe& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t Safe::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    xfer += iprot->skip(ftype);
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t Safe::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("Safe");

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(Safe &a, Safe &b) {
  using ::std::swap;
  (void) a;
  (void) b;
}

Safe::Safe(const Safe& other0) {
  (void) other0;
}
Safe& Safe::operator=(const Safe& other1) {
  (void) other1;
  return *this;
}
void Safe::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "Safe(";
  out << ")";
}

}}} // namespace
