/**
 * Autogenerated by Thrift Compiler (2.7.0-upfluence)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef exception_CONSTANTS_H
#define exception_CONSTANTS_H

#include "exception_types.h"

namespace types { namespace annotation { namespace exception {

class exceptionConstants {
 public:
  exceptionConstants();

};

extern const exceptionConstants g_exception_constants;

}}} // namespace

#endif
