/**
 * Autogenerated by Thrift Compiler (v2.6.8-upfluence)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "naming_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace types { namespace annotation { namespace naming {


PreviouslyKnownAs::~PreviouslyKnownAs() noexcept {
}


void PreviouslyKnownAs::__set_namespace_(const std::string& val) {
  this->namespace_ = val;
__isset.namespace_ = true;
}

void PreviouslyKnownAs::__set_name(const std::string& val) {
  this->name = val;
__isset.name = true;
}
std::ostream& operator<<(std::ostream& out, const PreviouslyKnownAs& obj)
{
  obj.printTo(out);
  return out;
}


uint32_t PreviouslyKnownAs::read(::apache::thrift::protocol::TProtocol* iprot) {

  ::apache::thrift::protocol::TInputRecursionTracker tracker(*iprot);
  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->namespace_);
          this->__isset.namespace_ = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->name);
          this->__isset.name = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t PreviouslyKnownAs::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  ::apache::thrift::protocol::TOutputRecursionTracker tracker(*oprot);
  xfer += oprot->writeStructBegin("PreviouslyKnownAs");

  if (this->__isset.namespace_) {
    xfer += oprot->writeFieldBegin("namespace_", ::apache::thrift::protocol::T_STRING, 1);
    xfer += oprot->writeString(this->namespace_);
    xfer += oprot->writeFieldEnd();
  }
  if (this->__isset.name) {
    xfer += oprot->writeFieldBegin("name", ::apache::thrift::protocol::T_STRING, 2);
    xfer += oprot->writeString(this->name);
    xfer += oprot->writeFieldEnd();
  }
  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(PreviouslyKnownAs &a, PreviouslyKnownAs &b) {
  using ::std::swap;
  swap(a.namespace_, b.namespace_);
  swap(a.name, b.name);
  swap(a.__isset, b.__isset);
}

PreviouslyKnownAs::PreviouslyKnownAs(const PreviouslyKnownAs& other0) {
  namespace_ = other0.namespace_;
  name = other0.name;
  __isset = other0.__isset;
}
PreviouslyKnownAs& PreviouslyKnownAs::operator=(const PreviouslyKnownAs& other1) {
  namespace_ = other1.namespace_;
  name = other1.name;
  __isset = other1.__isset;
  return *this;
}
void PreviouslyKnownAs::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "PreviouslyKnownAs(";
  out << "namespace_="; (__isset.namespace_ ? (out << to_string(namespace_)) : (out << "<null>"));
  out << ", " << "name="; (__isset.name ? (out << to_string(name)) : (out << "<null>"));
  out << ")";
}

}}} // namespace
