/**
 * Autogenerated by Thrift Compiler (2.5.4-upfluence)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "naming_constants.h"

namespace types { namespace annotation { namespace naming {

const namingConstants g_naming_constants;

namingConstants::namingConstants() {
}

}}} // namespace

