// Autogenerated by Thrift Compiler (v2.6.8-upfluence)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package annotation_definition

import (
	"bytes"
	"context"
	"fmt"
	"github.com/upfluence/thrift/lib/go/thrift"
	"github.com/upfluence/thrift/lib/go/thrift/types/core"
	"github.com/upfluence/thrift/lib/go/thrift/types/value"
	"reflect"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = context.Background
var _ = reflect.DeepEqual
var _ = bytes.Equal

var _ = core.GoUnusedProtection__
var _ = value.GoUnusedProtection__

// Attributes:
//   - Type
//   - Value
type StructuredAnnotationDefinition struct {
	Type  *core.Reference        `thrift:"type,1,required" db:"type" json:"type"`
	Value *value.ValueDefinition `thrift:"value,2,required" db:"value" json:"value"`
}

func NewStructuredAnnotationDefinition() *StructuredAnnotationDefinition {
	return &StructuredAnnotationDefinition{}
}

var structuredAnnotationDefinitionStructDefinition = thrift.StructDefinition{
	Namespace: Namespace,
	AnnotatedDefinition: thrift.AnnotatedDefinition{
		Name:                  "StructuredAnnotationDefinition",
		LegacyAnnotations:     map[string]string{},
		StructuredAnnotations: []thrift.RegistrableStruct{},
	},
	Fields: []thrift.FieldDefinition{
		{
			AnnotatedDefinition: thrift.AnnotatedDefinition{
				Name:                  "type",
				LegacyAnnotations:     map[string]string{},
				StructuredAnnotations: []thrift.RegistrableStruct{},
			},
		},

		{
			AnnotatedDefinition: thrift.AnnotatedDefinition{
				Name:                  "value",
				LegacyAnnotations:     map[string]string{},
				StructuredAnnotations: []thrift.RegistrableStruct{},
			},
		},
	},
}

func (p *StructuredAnnotationDefinition) StructDefinition() thrift.StructDefinition {
	return structuredAnnotationDefinitionStructDefinition
}

var StructuredAnnotationDefinition_Type_DEFAULT *core.Reference

func (p *StructuredAnnotationDefinition) GetType() *core.Reference {
	if !p.IsSetType() {
		return StructuredAnnotationDefinition_Type_DEFAULT
	}
	return p.Type
}

func (p *StructuredAnnotationDefinition) SetType(v *core.Reference) {
	p.Type = v
}

var StructuredAnnotationDefinition_Value_DEFAULT *value.ValueDefinition

func (p *StructuredAnnotationDefinition) GetValue() *value.ValueDefinition {
	if !p.IsSetValue() {
		return StructuredAnnotationDefinition_Value_DEFAULT
	}
	return p.Value
}

func (p *StructuredAnnotationDefinition) SetValue(v *value.ValueDefinition) {
	p.Value = v
}
func (p *StructuredAnnotationDefinition) IsSetType() bool {
	return p.Type != nil
}

func (p *StructuredAnnotationDefinition) IsSetValue() bool {
	return p.Value != nil
}

func (p *StructuredAnnotationDefinition) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	var issetType bool = false
	var issetValue bool = false

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField1(iprot); err != nil {
					return err
				}
				issetType = true
			} else {
				if err := iprot.Skip(fieldTypeId); err != nil {
					return err
				}
			}
		case 2:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField2(iprot); err != nil {
					return err
				}
				issetValue = true
			} else {
				if err := iprot.Skip(fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	if !issetType {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Type is not set"))
	}
	if !issetValue {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Value is not set"))
	}
	return nil
}

func (p *StructuredAnnotationDefinition) ReadField1(iprot thrift.TProtocol) error {
	p.Type = core.NewReference()
	if err := p.Type.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Type), err)
	}
	return nil
}

func (p *StructuredAnnotationDefinition) ReadField2(iprot thrift.TProtocol) error {
	p.Value = value.NewValueDefinition()
	if err := p.Value.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Value), err)
	}
	return nil
}

func (p *StructuredAnnotationDefinition) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("StructuredAnnotationDefinition"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(oprot); err != nil {
			return err
		}
		if err := p.writeField2(oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *StructuredAnnotationDefinition) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("type", thrift.STRUCT, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:type: ", p), err)
	}
	if err := p.Type.Write(oprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Type), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:type: ", p), err)
	}
	return err
}

func (p *StructuredAnnotationDefinition) writeField2(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("value", thrift.STRUCT, 2); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:value: ", p), err)
	}
	if err := p.Value.Write(oprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Value), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 2:value: ", p), err)
	}
	return err
}

func (p *StructuredAnnotationDefinition) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf(
		"StructuredAnnotationDefinition({type: %v, value: %v})",
		p.GetType(),
		p.GetValue(),
	)
}

// Attributes:
//   - Name
//   - StructuredAnnotations
//   - LegacyAnnotations
type AnnotationDefinition struct {
	Name                  string                            `thrift:"name,1,required" db:"name" json:"name"`
	StructuredAnnotations []*StructuredAnnotationDefinition `thrift:"structured_annotations,2,required" db:"structured_annotations" json:"structured_annotations"`
	LegacyAnnotations     map[string]string                 `thrift:"legacy_annotations,3,required" db:"legacy_annotations" json:"legacy_annotations"`
}

func NewAnnotationDefinition() *AnnotationDefinition {
	return &AnnotationDefinition{}
}

var annotationDefinitionStructDefinition = thrift.StructDefinition{
	Namespace: Namespace,
	AnnotatedDefinition: thrift.AnnotatedDefinition{
		Name:                  "AnnotationDefinition",
		LegacyAnnotations:     map[string]string{},
		StructuredAnnotations: []thrift.RegistrableStruct{},
	},
	Fields: []thrift.FieldDefinition{
		{
			AnnotatedDefinition: thrift.AnnotatedDefinition{
				Name:                  "name",
				LegacyAnnotations:     map[string]string{},
				StructuredAnnotations: []thrift.RegistrableStruct{},
			},
		},

		{
			AnnotatedDefinition: thrift.AnnotatedDefinition{
				Name:                  "structured_annotations",
				LegacyAnnotations:     map[string]string{},
				StructuredAnnotations: []thrift.RegistrableStruct{},
			},
		},

		{
			AnnotatedDefinition: thrift.AnnotatedDefinition{
				Name:                  "legacy_annotations",
				LegacyAnnotations:     map[string]string{},
				StructuredAnnotations: []thrift.RegistrableStruct{},
			},
		},
	},
}

func (p *AnnotationDefinition) StructDefinition() thrift.StructDefinition {
	return annotationDefinitionStructDefinition
}

func (p *AnnotationDefinition) GetName() string {
	return p.Name
}

func (p *AnnotationDefinition) SetName(v string) {
	p.Name = v
}

func (p *AnnotationDefinition) GetStructuredAnnotations() []*StructuredAnnotationDefinition {
	return p.StructuredAnnotations
}

func (p *AnnotationDefinition) SetStructuredAnnotations(v []*StructuredAnnotationDefinition) {
	p.StructuredAnnotations = v
}

func (p *AnnotationDefinition) GetLegacyAnnotations() map[string]string {
	return p.LegacyAnnotations
}

func (p *AnnotationDefinition) SetLegacyAnnotations(v map[string]string) {
	p.LegacyAnnotations = v
}
func (p *AnnotationDefinition) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	var issetName bool = false
	var issetStructuredAnnotations bool = false
	var issetLegacyAnnotations bool = false

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField1(iprot); err != nil {
					return err
				}
				issetName = true
			} else {
				if err := iprot.Skip(fieldTypeId); err != nil {
					return err
				}
			}
		case 2:
			if fieldTypeId == thrift.LIST {
				if err := p.ReadField2(iprot); err != nil {
					return err
				}
				issetStructuredAnnotations = true
			} else {
				if err := iprot.Skip(fieldTypeId); err != nil {
					return err
				}
			}
		case 3:
			if fieldTypeId == thrift.MAP {
				if err := p.ReadField3(iprot); err != nil {
					return err
				}
				issetLegacyAnnotations = true
			} else {
				if err := iprot.Skip(fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	if !issetName {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Name is not set"))
	}
	if !issetStructuredAnnotations {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field StructuredAnnotations is not set"))
	}
	if !issetLegacyAnnotations {
		return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field LegacyAnnotations is not set"))
	}
	return nil
}

func (p *AnnotationDefinition) ReadField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.Name = v
	}
	return nil
}

func (p *AnnotationDefinition) ReadField2(iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin()
	if err != nil {
		return thrift.PrependError("error reading list begin: ", err)
	}
	tSlice := make([]*StructuredAnnotationDefinition, 0, size)
	p.StructuredAnnotations = tSlice
	for i := 0; i < size; i++ {
		_elem0 := NewStructuredAnnotationDefinition()
		if err := _elem0.Read(iprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", _elem0), err)
		}
		p.StructuredAnnotations = append(p.StructuredAnnotations, _elem0)
	}
	if err := iprot.ReadListEnd(); err != nil {
		return thrift.PrependError("error reading list end: ", err)
	}
	return nil
}

func (p *AnnotationDefinition) ReadField3(iprot thrift.TProtocol) error {
	_, _, size, err := iprot.ReadMapBegin()
	if err != nil {
		return thrift.PrependError("error reading map begin: ", err)
	}
	tMap := make(map[string]string, size)
	p.LegacyAnnotations = tMap
	for i := 0; i < size; i++ {
		var _key1 string
		if v, err := iprot.ReadString(); err != nil {
			return thrift.PrependError("error reading field 0: ", err)
		} else {
			_key1 = v
		}
		var _val2 string
		if v, err := iprot.ReadString(); err != nil {
			return thrift.PrependError("error reading field 0: ", err)
		} else {
			_val2 = v
		}
		p.LegacyAnnotations[_key1] = _val2
	}
	if err := iprot.ReadMapEnd(); err != nil {
		return thrift.PrependError("error reading map end: ", err)
	}
	return nil
}

func (p *AnnotationDefinition) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("AnnotationDefinition"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(oprot); err != nil {
			return err
		}
		if err := p.writeField2(oprot); err != nil {
			return err
		}
		if err := p.writeField3(oprot); err != nil {
			return err
		}
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *AnnotationDefinition) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("name", thrift.STRING, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:name: ", p), err)
	}
	if err := oprot.WriteString(string(p.Name)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.name (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:name: ", p), err)
	}
	return err
}

func (p *AnnotationDefinition) writeField2(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("structured_annotations", thrift.LIST, 2); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:structured_annotations: ", p), err)
	}
	if err := oprot.WriteListBegin(thrift.STRUCT, len(p.StructuredAnnotations)); err != nil {
		return thrift.PrependError("error writing list begin: ", err)
	}
	for _, v := range p.StructuredAnnotations {
		if err := v.Write(oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", v), err)
		}
	}
	if err := oprot.WriteListEnd(); err != nil {
		return thrift.PrependError("error writing list end: ", err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 2:structured_annotations: ", p), err)
	}
	return err
}

func (p *AnnotationDefinition) writeField3(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("legacy_annotations", thrift.MAP, 3); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:legacy_annotations: ", p), err)
	}
	if err := oprot.WriteMapBegin(thrift.STRING, thrift.STRING, len(p.LegacyAnnotations)); err != nil {
		return thrift.PrependError("error writing map begin: ", err)
	}
	for k, v := range p.LegacyAnnotations {
		if err := oprot.WriteString(string(k)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
		}
		if err := oprot.WriteString(string(v)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
		}
	}
	if err := oprot.WriteMapEnd(); err != nil {
		return thrift.PrependError("error writing map end: ", err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 3:legacy_annotations: ", p), err)
	}
	return err
}

func (p *AnnotationDefinition) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf(
		"AnnotationDefinition({name: %v, structured_annotations: %v, legacy_annotations: %v})",
		p.GetName(),
		p.GetStructuredAnnotations(),
		p.GetLegacyAnnotations(),
	)
}
