// Autogenerated by Thrift Compiler (2.7.0-upfluence)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package value

import (
	"bytes"
	"context"
	"fmt"
	"github.com/upfluence/thrift/lib/go/thrift"
	"reflect"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = context.Background
var _ = reflect.DeepEqual
var _ = bytes.Equal

var GoUnusedProtection__ int

const Namespace = "types.value"

func init() {
	thrift.RegisterStruct((*NullValue)(nil))
	thrift.RegisterStruct((*ListValue)(nil))
	thrift.RegisterStruct((*MapEntry)(nil))
	thrift.RegisterStruct((*MapValue)(nil))
	thrift.RegisterStruct((*Value)(nil))
	thrift.RegisterStruct((*StructValue)(nil))
}
